### ISSUE TITLE
Git clone is not working when passing an oid instead of the branch name

### ISSUE THREAD

**Issue by jorgeclaro** [isomorphic-git/isomorphic-git#1022]
Using it with Node 12

**Comment by wmhilton** [comment]
Actually it does. How were you trying to do it?

See, here's an example script that clones using an oid:
```sh
mkdir foo
cd foo
npx isomorphic-git clone --url=https://github.com/isomorphic-git/isomorphic-git.git --ref=49fb8739cb7e9c6b13965ee648ec0fe919740e7c
```

**Comment by jorgeclaro** [comment]
Had some issues, when using branches that suffered some `--force` commits. Not sure if directly related with checkout or fetch.

**Comment by wmhilton** [comment]
Well... if users force-pushed some branches and overwrote the old commits, then you might not be able to check out the old commits anymore.

If you run into the problem again and can explain how to reproduce it, feel free to re-open the issue!
