### ISSUE TITLE
Octal escape sequences are not allowed in template strings

### ISSUE THREAD

**Issue by EryouHao** [isomorphic-git/isomorphic-git#1032]
Hi @wmhilton , thanks for your work. I like this library so mush.
```javascript
import * as git from 'isomorphic-git/dist/for-node/isomorphic-git/index'

const pushRes = await git.push({
  fs,
  dir: this.outputDir,
  remote: 'origin',
  ref: setting.branch,
  force: true,
})
```
when I use push method, it's work fine in development env, but build is failed.(electron build)
![image](https://user-images.githubusercontent.com/17328747/74081108-40b68d00-4a86-11ea-87e1-032545900bae.png)

Can you help me?

**Comment by EryouHao** [comment]
oh~, I remove javascript `use strict`, it's works again.

**Comment by EryouHao** [comment]
only the `push` method is not work, other method is ok

**Comment by wmhilton** [comment]
See my reply in the PR: https://github.com/isomorphic-git/isomorphic-git/pull/1034#issuecomment-583913258
