### ISSUE TITLE
Staging a deleted file throws "Could not read file"

### ISSUE THREAD

**Issue by cyanzhong** [isomorphic-git/isomorphic-git#1042]
Hey guys, thanks for working on this awesome project! I'm using it with Node.js, and it works pretty well.

The only confusing stuff to me is that I don't know how to **add a deleted file to the staging area**.

I'm trying to use [git.add](https://isomorphic-git.org/docs/en/add) to accomplish this, but when the file is a deleted file (manually deleted in the file system), it throws a **Could not read file "FILE NAME"** exception.

Is there any way to do that? I suppose there must be something I missed, but I couldn't find it in the documentation site.

Thanks in advance.

**Comment by jcubic** [comment]
In git Web terminal I've used this code:
```javascript
if (!long_options.includes(/--cached/)) {
    git.remove({fs, dir, filepath}).then(() => fs.unlink(path_name));
} else {
    git.remove({fs, dir, filepath})
}
```

**Comment by cyanzhong** [comment]
Thanks @jcubic for the workaround, I will try!

Regarding:

> Maybe git.remove should handle deleted files

That sounds kind of different from my expectation, my thought is that "git.add" should handle it, because I'm "adding changes" to the staging area, no matter what the change type is (add/modify/delete)?

**Comment by wmhilton** [comment]
> my thought is that "git.add" should handle it, because I'm "adding changes" to the staging area, no matter what the change type is (add/modify/delete)?

Yeah. That's probably not a bad idea. Or maybe we could make two new commands and call them `stage` and `unstage`. That would be pretty intuitive.

But yes, the short answer / workaround for now is `git.remove` removes files from the staging area. Which is another way of saying "add a deleted file to the staging area" I suppose.

**Comment by cyanzhong** [comment]
Thanks for replies! Closing as it's clear now.

**Comment by tmpmachine** [comment]
I'm working on a case where I renamed a file which resulted in 1 untracked and 1 deleted file. 

> ```js
> if (!long_options.includes(/--cached/)) {
>     git.remove({fs, dir, filepath}).then(() => fs.unlink(path_name));
> } else {
>     git.remove({fs, dir, filepath})
> }
> ```
> 
> So you can use hack, create empty file in place of deleted file use git.remove and then unlink. Maybe git.remove should handle deleted files.

It works but I'm still confused. I though `git.remove()` is for removing file from staging? But the new file is still in working directory, right? So, what there is to remove if the file is not even in staging?

Anyway, to add up, we can remove the deleted from staging by creating an empty file of the same name and add it to staging. A little weird, but the [status matrix](https://isomorphic-git.org/docs/en/statusMatrix.html) does match up with a local git repository.

```js
await compoFile.TaskAddFile('style.css', '');
git.add({fs, dir:'/', filepath:'style.css'}).then(() => fs.promises.unlink('/style.css'));
```
