### ISSUE TITLE
Info messages while pushing/fetching

### ISSUE THREAD

**Issue by juancampa** [isomorphic-git/isomorphic-git#106]
Is there a way to get the informational messages sent by the server while pushing/fetching? I'm talking about what is normally prefixed by `  remote: ....` in regular command-line git.

**Comment by juancampa** [comment]
This is what I'm getting from a successful push:
```
{
 "ok": [
  "unpack",
  "refs/heads/master"
 ]
}
```
But my git server is sending messages that are not shown here. It would be nice if the returned promise was also a readable stream for these messages. @wmhilton if you point me in the right direction I could help you get this done

**Comment by wmhilton** [comment]
OK so. I know I implemented this for pull... I'm not sure if I implemented it for push. (goes and looks at code) Nope didn't implement it for push yet. 

For `fetch`, you need create an EventEmitter that listens to 'message' events and pass it as an argument to fetch (or clone). (I know that's kinda weird, but I tried a couple different ideas and this was the only one that still let me make fetch `async` function that returns when the operation is completed.)

Here's a snippet from `__tests__/test-fetch.js` to demonstrate:
```js
...
    let emitter = new EventEmitter()
    emitter
      .on('message', output.push.bind(output))
      .on('progress', progress.push.bind(progress))
    // Test
    await fetch({
      fs,
      gitdir,
      emitter,
      depth: 1,
      singleBranch: true,
      remote: 'origin',
      ref: 'test-branch-shallow-clone'
    })
...
```

The 'message' events are the raw messages. The 'progress' events are a synthetic thing that I added in case you just want to use them for a progress bar.

Um... that should help you get started. I'll have to fix my code for "push" though so it also emits message events. Just out of curiosity, what messages is your git server sending on push that you're interested in?

**Comment by juancampa** [comment]
Thanks! I'll work on this when I get a moment

> what messages is your git server sending on push that you're interested in?

My git server transpiles the code and install all dependencies using the server-side update hook. It's nice to see those messages as an indication of progress.

**Comment by wmhilton** [comment]
> My git server transpiles the code and install all dependencies using the server-side update hook. It's nice to see those messages as an indication of progress.

Holy 🐄 that's awesome!! Is that something you wrote? That sounds like an awesome git server. I'm working on adding git server features to isomorphic-git, so it'll be possible to use it as an Express middleware to do stuff like that. I hadn't thought about git-hooks yet though. I guess that would be an interesting starting point for the API.

**Comment by juancampa** [comment]
> Holy 🐄 that's awesome!! Is that something you wrote?

Yeah, thanks! it's for this sort of hosted OS that I'm working on. The repos you push are programs that run on your OS so they have the same structure. The git server rejects a push if the head ref of the master branch (a convention) can't be transpiled or doesn't have the right file structure. It works pretty nicely, I think Heroku works similarly, or it used to.

**Comment by juancampa** [comment]
Status update: spending some time today looking into this

**Comment by juancampa** [comment]
Hey @wmhilton. I misunderstood your first response and thought you were giving me instructions on how to implement it for push (as opposed to just using it), and I thought, hmm, looks simple enough, but of course, it's not :)

I'm still giving it a shot, I might be able to figure out how to implement the push version.

I added a test to `server-only.test-push.js` but I'm pretty sure it's not being run. Is there something special I have to do?

**Comment by wmhilton** [comment]
>  Also, is there a way to only run this test (as opposed to the whole suite) while implementing it?

I guess I really do need a better "How to Contribute" section to the README. I never expected this many contributors before I hit 1.0! Heck, this repo's not even at 100 stars.

Short answer is: Yes! try `jest --watch push`. Long broad sort-of-helpful answer is check out the Jest [documentation](https://facebook.github.io/jest/docs/en/getting-started.html) or just google "how to X with jest javascript". This is the first project I've used Jest with.

Even longer answer is there's ALSO Jasmine tests that run in karma. Because I didn't realize that Jest didn't run in the browser when I started writing tests.

All that being said......... lemme see if I can just knock this out for ya!

**Comment by juancampa** [comment]
> All that being said......... lemme see if I can just knock this out for ya!

👏👏👏👏👏

**Comment by wmhilton** [comment]
I pushed a `push-messages` branch that I *think* adds support... but for some reason I'm not seeing any messages in the test scripts. I'm not sure if I *should* though, because I'm not sure what messages to look for. I might need your help making a test case for this.

**Comment by juancampa** [comment]
Hmm I'm not seeing any of the two events being fired. I wanna take a closer look but I have to leave for now. I'll run another test when I come back

**Comment by wmhilton** [comment]
To generate such messages, do I just use "echo" in a post-recieve git hook? (Is that what you're using?)

**Comment by juancampa** [comment]
Yeah that's exactly what I'm using

**Comment by juancampa** [comment]
Actually the hook is called "update"

**Comment by wmhilton** [comment]
Ha! OK. I figured out how to do it without setting up apache. :) Now I will see if I can use this new knowledge to write a unit test using such a git remote.

**Comment by wmhilton** [comment]
I've now written my first karma plugin, https://npm.im/karma-git-http-server-middleware! It exposes the main directory so that tests can directly do git.clone on "http://localhost:9876/__tests__/__fixtures__/test-clone.git". Unfortunately I forgot I'd need a way to start and stop the git server for non-karma tests (yay isomorphic tests) so I still need to add that.

**Comment by wmhilton** [comment]
https://github.com/isomorphic-git/isomorphic-git/pull/113 is an attempt to add support for http-servable git repo fixtures. If it works, it should support creating new repo test fixtures complete with "update" and "post-receive" git hooks!

**Comment by wmhilton** [comment]
#116 changes the git response parser to a streaming parser. That's necessary for the git push messages to be streamed instead of returned all at once at the end. Much more useful to know what's going on and get some feedback during the push.

**Comment by wmhilton** [comment]
#128 adds emitting status messages during git push, but I still need to add real tests. I'm not sure if it works yet lol.

**Comment by juancampa** [comment]
Sorry I haven't been able to help you here. I've been working on other
things. I'll try this out as soon as possible though

**Comment by juancampa** [comment]
I just tried to build the `push-messages` branch and failed with this message:

```
[build.sw] ERROR: Source map doesn't work with input from STDIN
[build.internalApis] ERROR: Source map doesn't work with input from STDIN
[build.umd] ERROR: Source map doesn't work with input from STDIN
[build.sw] The script called "build.sw" which runs "browserify            --entry dist/for-serviceworker/index.js            --standalone git            --debug | uglifyjs                      --compress                      --mangle                      --source-map "content=inline,url=service-workder-bundle.umd.min.js.map"                      -o dist/service-worker-bundle.umd.min.js" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.0/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
[build.sw] nps build.sw exited with code 1
--> Sending SIGTERM to other processes..
[build.umd] nps build.umd exited with code null
[build.internalApis] nps build.internalApis exited with code null
The script called "build.browserify" which runs "node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold,bgGreen.bold" --prefix "[{name}]" --names "build.sw,build.umd,build.internalApis" 'nps build.sw' 'nps build.umd' 'nps build.internalApis'" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.0/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "build" which runs "nps build.rollup && nps build.browserify && nps build.indexjson" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.0/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
error Command failed with exit code 1.
```

Any thoughts?

**Comment by juancampa** [comment]
False alarm, I was using yarn instead of npm to install dependencies. Probably had the wrong dependencies

**Comment by juancampa** [comment]
This doesn't seem like a false alarm though:

```
error TypeError: bufferstream.slice is not a function
    at read (models.js:629)
    at nextBit (managers.js:613)
    at GitRemoteHTTP.stream (managers.js:647)
```

Might be an error in mbostock's `stream-source` though

**Comment by juancampa** [comment]
My guess is that the stream returned by `simple-get` looks like a WhatWG stream from the point of view of `stream-source` (i.e. it has a `read` function) but it's not fully compliant (i.e. it doesn't have a `slice` function)

**Comment by wmhilton** [comment]
> Update: I'm getting this with v0.9.9 from npm as well. During pull.

Hmm. When it rains it pours. I'm not too worried you got errors trying to build the push-messages branch... I've been force-pushing to it multiple times today lol... but getting the error in the published version is sad.

> error TypeError: bufferstream.slice is not a function
>    at read (models.js:629)
>    at nextBit (managers.js:613)
>    at GitRemoteHTTP.stream (managers.js:647)

Most likely it's not a problem in `simple-get` or in `stream-source` but rather something about how I'm using it. Maybe `res` is `undefined` or the stream is empty (no new commits?) or something like that. Let's open up a new issue and continue the discussion there, since this one is about to get closed when I merge #128 (Travis willing).

**Comment by wmhilton** [comment]
Yay! I finally got it working and have tests to demonstrate it:
[`/__tests__/test-push.js`](https://github.com/isomorphic-git/isomorphic-git/blob/0e1bc77ec39cd43459516f5599e2d05be1579f9c/__tests__/test-push.js)
[`/__tests__/__fixtures__/test-push-server.git/hooks`](https://github.com/isomorphic-git/isomorphic-git/tree/0e1bc77ec39cd43459516f5599e2d05be1579f9c/__tests__/__fixtures__/test-push-server.git/hooks)


Usage Example:
```js
    let emitter = new EventEmitter()
      .on('message', msg => console.log('remote: ' + msg))
    // Test
    let res = await push({
      fs,
      gitdir,
      emitter,
      remote: 'karma',
      ref: 'refs/heads/master'
    })
```

**Comment by juancampa** [comment]
@wmhilton I tried testing this with 0.10 but I'm still getting the `TypeError: bufferstream.slice is not a function` :/ Any ideas? `res` doesn't seem to be undefined but it doesn't have the `slice` function

**Comment by wmhilton** [comment]
Hmm. My tests must be doing something different than what your code is doing, because I haven't seen that error. I might have to see how you're calling isomorphic-git. Can you open an issue with a code example? :bug:

**Comment by wmhilton** [comment]
@juancampa Are you using Webpack?! I just found (and solved) a very similar problem, I think.

**Comment by juancampa** [comment]
I am! I'll try it out. Is it the latest on npm?

**Comment by wmhilton** [comment]
That could be it then! And no, it's still on a branch. It's taking me a while to get all the build tests passing and stuff.

**Comment by wmhilton** [comment]
I've got it working on everything except Safari. But the Safari bug is proving extremely tricky to hunt down. When I first converted it to webpack, I wasn't using Babel and was shocked that the build was nearly 100% smaller. So now I'm trying to minimize the amount of transpiling. I dropped support for the "Android" browser and added support for the "ChromeAndroid" browser, and then `babel-preset-env` thought that only two transforms were needed, both for Edge browser. But that has proven not to be the case... Safari needs just a little help... and I need to figure out which of the dozen or so transforms it needs.

**Comment by juancampa** [comment]
I thought those days were over after `babel-preset-env` came out but I guess is not as bulletproof as it's meant to be

**Comment by juancampa** [comment]
I take it back, wasn't building correctly. I'm doing more test. Still trying

**Comment by wmhilton** [comment]
So what I had to do to get it to build was add an alias:
```
'stream-source': 'stream-source/index.node.js'
```

I would think that the compiled version would Just Work, but if people are going to be building it from source, maybe I should try a different fix. Like, maybe import `stream-source/index.node.js` directly?

**Comment by wmhilton** [comment]
OK try v0.11.0. I changed `import from 'stream-source'` to `import from 'stream-source/index.node.js'` so I think it should Just Work™️ for you now. If not, I'm going to open a new issue because it really bugs me that it's not working for you!

**Comment by juancampa** [comment]
Hey thanks again for being so helpful.

v0.11.0 is not working for me. Babel is complaining that it has object spread syntax which is not expecting in any node_modules file.

It seems like your .babelrc has `transform-object-rest-spread` which should do the trick but if you look at dist/for-future/isomorphic-git/index.js the spread operator is still there:

(line 454)
```
  parse () {
    return { message: this.message(), ...this.headers() }
  }
```

**Comment by juancampa** [comment]
The good news is that I passed `dist/for-future/isomorphic-git/index.js` through babel to remove the object spread stuff and it works!! I can see the messages coming in  👏👏🎉🎉

**Comment by wmhilton** [comment]
Wait... does Webpack or Babel or whatever use `for-future` by default? I thought it would be using `bundle.umd.min.js`... It's honestly called `for-future` for a reason lol... it's not transpiled for the present. I might have to tweak my `package.json`.

**Comment by wmhilton** [comment]
What version of Babel are you running? Maybe I need to make a note of that...

**Comment by juancampa** [comment]
Oh I know what's going on here. Next has server-side-rendering so it transpiles everything for both environments!
