### ISSUE TITLE
[1.0.0] Unable to build typescript project with new version

### ISSUE THREAD

**Issue by AxelTerizaki** [isomorphic-git/isomorphic-git#1063]
Hello.

I'm trying to upgrade to isomorphic-git 1.0.0. Congratulations on the milestone, by the way!

I'm running into an error with typescript in my node project whenever I try to build and run tsc --build :

```
node_modules/isomorphic-git/http/node/index.d.ts(90,27): error TS2339: Property 'onProgress' does not exist on type 'GitHttpRequest'.
node_modules/isomorphic-git/index.d.ts(931,121): error TS2339: Property 'debug' does not exist on type '{ fs: CallbackFsClient | PromiseFsClient; onProgress?: ProgressCallback; dir: string; gitdir?: string; ref?: string; filepaths?: string[]; ... 4 more ...; force?: boolean; }'.
```

I'm using typescript 3.8.2 and this was working perfectly with the previous isomorphic-git version.

Thanks for your help!

**Comment by chmac** [comment]
I tried a naive attempt to fix the first error.

The second issue is potentially related to this:

https://github.com/isomorphic-git/isomorphic-git/blob/d407ef570eeec0e33cee2862dc58c63db14c224a/src/api/checkout.js#L71-L72

This is what I get in my `node_modules/isomorphic-git/index.d.ts` file:

```typescript
export function checkout({ fs, onProgress, dir, gitdir, remote, ref: _ref, filepaths, noCheckout, noUpdateHead, dryRun, debug, force, }: {
    fs: CallbackFsClient | PromiseFsClient;
    onProgress?: ProgressCallback;
    dir: string;
    gitdir?: string;
    ref?: string;
    filepaths?: string[];
    remote?: string;
    noCheckout?: boolean;
    noUpdateHead?: boolean;
    dryRun?: boolean;
    force?: boolean;
}): Promise<void>;
```

It looks like somehow the `debug` parameter is included in the function definition, but not in the typing...

**Comment by chmac** [comment]
# Workaround

FYI, I've monkey patched this locally thanks to the awesome [patch-package](https://www.npmjs.com/package/patch-package) package, how very meta!

Here's my patch file which allows me to build:

```
diff --git a/node_modules/isomorphic-git/http/node/index.d.ts b/node_modules/isomorphic-git/http/node/index.d.ts
index d1c6a00..0cc5fc7 100644
--- a/node_modules/isomorphic-git/http/node/index.d.ts
+++ b/node_modules/isomorphic-git/http/node/index.d.ts
@@ -1,3 +1,5 @@
+import { ProgressCallback } from "isomorphic-git";
+
 export default index;
 export type GitHttpRequest = {
     /**
@@ -87,4 +89,4 @@ declare namespace index {
  * @param {GitHttpRequest} request
  * @returns {Promise<GitHttpResponse>}
  */
-export function request({ onProgress, url, method, headers, body, }: GitHttpRequest): Promise<GitHttpResponse>;
+export function request({ onProgress, url, method, headers, body, }: GitHttpRequest & {onProgress: ProgressCallback}): Promise<GitHttpResponse>;
diff --git a/node_modules/isomorphic-git/index.d.ts b/node_modules/isomorphic-git/index.d.ts
index a8ff5f3..bc97352 100644
--- a/node_modules/isomorphic-git/index.d.ts
+++ b/node_modules/isomorphic-git/index.d.ts
@@ -939,6 +939,7 @@ export function checkout({ fs, onProgress, dir, gitdir, remote, ref: _ref, filep
     noCheckout?: boolean;
     noUpdateHead?: boolean;
     dryRun?: boolean;
+    debug?: boolean;
     force?: boolean;
 }): Promise<void>;
 /**
```

This goes into `patches/isomorphic-git+1.0.0.patch`.

**Comment by wmhilton** [comment]
The `onProgress` on is on me. My http clients are too dumb and don't use it so I forgot to include it in the `src/typedefs.js`. I oughta be able to fix that in a jiffy.

The `debug` one I find a little more perplexing. Are either of you _using_ the `debug` argument to checkout? Because that's undocumented for a reason. 😆 Do you actually need it for something? I hadn't frozen the output format yet.

**Comment by wmhilton** [comment]
Update: 😬 Actually the typedef for `GitHttpRequest` was completely out of date and still had the v0 definitions for `core`, `emitter`, `emitterPrefix` instead of `onProgress`. 🤦‍♂

**Comment by wmhilton** [comment]
OK, v1.1.1 should have a fix for the `HttpClient` typing: https://github.com/isomorphic-git/isomorphic-git/blob/fdfdabe3ba731ec065c75f613bd07bb57a45da9e/src/typedefs-http.js#L20

The `debug` one I'm a little more confused about. We use isomorphic-git with TypeScript at work, so I'm surprised people are running into trouble with it. 😕  🤔  💭  You know what, we don't use it directly with TypeScript, we're using WebPack and `ts-loader`... ..... OH you know, I've got a branch where we use plain TypeScript....... lemme see if I merge these branches here if I can reproduce the error....

**Comment by wmhilton** [comment]
~Hmm. No dice. I don't get any `node_modules/isomorphic-git/index.d.ts` errors running `tsc` on my project. If I add `await git.checkout({ fs, dir: this.cwd, ref, debug: true });` then I get an error for _my_ file. But I that's expected.~

~Can one of you make a simple project that reproduces the error?~ HAHA wow I reproduced it by creating a fresh project. WTF. What is going on here. 👀

**Comment by wmhilton** [comment]
I think it's super weird that _TypeScript generated that file index.d.ts file_ and now TypeScript is upset about it. You know what, I don't even want to know. I'll just remove the undocumented `debug` parameter, since that'll fix it.

**Comment by wmhilton** [comment]
Lemme know if v1.1.2 works for ya! It works for me.

**Comment by AxelTerizaki** [comment]
I confirm it now builds, thank you :)
