### ISSUE TITLE
TypeScript: error TS2339: Property 'debug' does not exist

### ISSUE THREAD

**Issue by KSXGitHub** [isomorphic-git/isomorphic-git#1067]
TypeScript reports this error:

```
node_modules/isomorphic-git/index.d.ts:931:121 - error TS2339: Property 'debug' does not exist on type '{ fs: CallbackFsClient | PromiseFsClient; onProgress?: ProgressCallback | undefined; dir: string; gitdir?: string | undefined; ... 6 more ...; force?: boolean | undefined; }'.

    931 export function checkout({ fs, onProgress, dir, gitdir, remote, ref: _ref, filepaths, noCheckout, noUpdateHead, dryRun, debug, force, }: {
                                                                                                                                ~~~~~


    Found 1 error.
```

![image](https://user-images.githubusercontent.com/11488886/75442367-e6786000-5991-11ea-9026-80c12a94ecea.png)

**Comment by chmac** [comment]
Duplicate of #1063

**Comment by wmhilton** [comment]
Thanks for reporting this! I'm so sorry. SHould be fixed in v1.1.2 out on npm right now.

**Comment by KSXGitHub** [comment]
Another error appears.

<pre><font color="#34E2E2">node_modules/isomorphic-git/index.d.ts</font>:<font color="#FBE84F">260</font>:<font color="#FBE84F">14</font> - <font color="#EF2828">error</font><font color="#545652"> TS2304: </font>Cannot find name &apos;AbortSignal&apos;.

<span style="background-color:#F5F5F5"><font color="#111111">260</font></span>     signal?: AbortSignal;
<span style="background-color:#F5F5F5"><font color="#111111">   </font></span> <font color="#EF2828">             ~~~~~~~~~~~</font>


Found 1 error.
</pre>

I don't think you should trust the tool that you used to generate TypeScript definition. I think you should commit `index.d.ts` to the git repository, remove the tool from the build command (only use it for convenient), and add `tsc --noEmit index.d.ts` to the test command.

**Comment by KSXGitHub** [comment]
Actually, TypeScript can type-check JavaScript with JSDoc too. But you should still use `tsc --noEmit index.d.ts` to be safe.

**Comment by wmhilton** [comment]
@KSXGitHub you may need to upgrade your version of TypeScript or ts-lib or add @types/node.

**Comment by wmhilton** [comment]
https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_dom_d_.abortsignal.html

**Comment by KSXGitHub** [comment]
I use TypeScript 3.8

**Comment by KSXGitHub** [comment]
I will check `@types/node` and `tslib`

**Comment by KSXGitHub** [comment]
I had updated everything to latest versions but `AbortSignal` error is still there

**Comment by KSXGitHub** [comment]
`AbortSignal` does not exist in v13.7.7 of `@types/node`.

**Comment by wmhilton** [comment]
Is it part of the "DOM" library?

**Comment by wmhilton** [comment]
Hmm. No, my example project doesn't use any "lib" configuration. 🤷‍♂ 

Would it help if I posted an example TypeScript project that works?

**Comment by wmhilton** [comment]
Are you writing a node application or a web application?

**Comment by wmhilton** [comment]
This works for me:
```json5
// package.json
{
  "name": "typescript-node",
  "version": "0.0.0",
  "description": "",
  "scripts": {
    "start": "node ./dist/index.js",
    "build": "tsc",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "William Hilton <wmhilton@gmail.com>",
  "license": "MIT",
  "devDependencies": {
    "@types/node": "^13.7.7",
    "ts-lib": "0.0.5",
    "typescript": "^3.8.3"
  },
  "dependencies": {
    "isomorphic-git": "^1.1.2"
  }
}
```

**Comment by wmhilton** [comment]
OK. Here's an example project you can clone and use as a starting point:

https://github.com/isomorphic-git/examples

**Comment by KSXGitHub** [comment]
Thank for your example project. I now know where the problem comes from: `AbortSignal` was part of the DOM library.

Without `"lib"` being provided inside `tsconfig.json`, TypeScript assumes that user needs DOM. But with `"lib": []`, the error appears again.

This raises another issue: `isomorphic-git` shouldn't depend on DOM, should it? Its JavaScript works the same in Node.js as in browser.

**Comment by wmhilton** [comment]
> Without "lib" being provided inside tsconfig.json, TypeScript assumes that user needs DOM. But with "lib": [], the error appears again. Change it to "lib": ["DOM"] and the error goes away.

Wow. 🤦‍♂️ Oh TypeScript.

[Insert "Y U DO THIS?!" meme]

Thank goodness you figured it out though!

> This raises another issue: isomorphic-git shouldn't depend on DOM, should it? Its JavaScript works the same in Node.js as in browser.

You're absolutely right. Screw it, we don't need AbortSignal. I'll just get rid of it for now. But man, this is weird. Get this, even after adding lib:[] to declaration.tsconfig.json, `tsc -p declaration.tsconfig.json` doesn't print any error.

I'm also noticing that it's adding
```/// <reference types="node" />```
to the top of the file. Why would it do that if it's actually isomorphic? Hmmmm.

**Comment by wmhilton** [comment]
I've also noticed that TypeScript's compiler is doing some weird aliasing:

This code:
```js

/**
 * @typedef {0|1} HeadStatus
 */

/**
 * @typedef {0|1|2} WorkdirStatus
 */

/**
 * @typedef {0|1|2|3} StageStatus
 */

/**
 * @typedef {[string, HeadStatus, WorkdirStatus, StageStatus]} StatusRow
 */
```

is getting compiled to _this_ (notice the `import("v8").DoesZapCodeSpaceFlag` instead of `HeadStatus`):
```ts
export type HeadStatus = 0 | 1;
export type WorkdirStatus = 0 | 2 | 1;
export type StageStatus = 0 | 2 | 1 | 3;
export type StatusRow = [string, import("v8").DoesZapCodeSpaceFlag, 0 | 2 | 1, 0 | 2 | 1 | 3];
```

I dunno if I feel up to filing an actual bug with the Microsoft team though.

**Comment by wmhilton** [comment]
Aha! Well, fun fact, if I change this code to this:
```
/**
 * @typedef {number} HeadStatus
 */

/**
 * @typedef {number} WorkdirStatus
 */

/**
 * @typedef {number} StageStatus
 */

/**
 * @typedef {[string, HeadStatus, WorkdirStatus, StageStatus]} StatusRow
 */
```

It no longer injects `/// <reference types="node" />` at the top. So it's doing that specifically so it can do `import("v8").DoesZapCodeSpaceFlag` 🤦‍♂

**Comment by wmhilton** [comment]
ya know what, I _will_ file a bug with the TS team. 'Cause I can't be the only one affected.

**Comment by wmhilton** [comment]
Alright. Took 30 minutes, but I was able to reproduce it in a small test case:

https://github.com/wmhilton-contrib/ts-jsdoc-aliasing-bug

Will file a bug with microsoft/typescript later.

**Comment by wmhilton** [comment]
Meh. As usual, it's not _really_ a bug, it's a feature. All the `@types/*` modules are included by default. Just like how if you don't specify `lib` it includes `"DOM"`.

By adding `"types": []` to my tsconfig.json file, I am able to prevent the compiler from adding these weird `import("v8")` references. 🙄 

Another npm publish coming up........

**Comment by wmhilton** [comment]
@KSXGitHub how about v1.1.4? 😂 Does it work now? I _think_ there is now zero hidden dependencies on "DOM" or on "@types/node".

Thank you so very very much for your patience! I added you as a bug reporting contributor to the README because this has been extremely helpful. I really want the TypeScript experience to be top-notch, and spent many days on it even redesigning the library's API to work better, so I was heartbroken and irritated when the very first thing I learn is: it doesn't work well with TypeScript 😭. Hopefully, now all these issues are resolved!

**Comment by KSXGitHub** [comment]
Thank you. The latest release works without `"DOM"`.
