### ISSUE TITLE
Does this library work in mobile browsers?

### ISSUE THREAD

**Issue by shd101wyy** [isomorphic-git/isomorphic-git#1079]
First of all, thank you very much for the awesome project!

I am trying to implement a note taking application using `isomorphic-git` here: https://github.com/0xGG/notehub
I installed your package using yarn.  
And I deployed my app to https://0xgg.github.io/notehub/

It works well on laptop browsers. But when I try it on my iPhone it failed.  
So does that mean that `isomorphic-git` doesn't work in mobile browsers?
btw I am using `BrowserFS` as the fs backend. Is that the cause?

Thank you!

**Comment by shd101wyy** [comment]
Btw I tried the guide https://isomorphic-git.org/docs/en/quickstart on my iPhone Safari and it got stuck while cloning the repository.

**Comment by wmhilton** [comment]
It is tested with mobile browsers too. 🤔 Which version of iPhone Safari are you running? I'm currently testing against iOS 13:

https://github.com/isomorphic-git/isomorphic-git/blob/0c1ec5ad967c4a6d7c42357ce022f1c8d6467099/karma.conf.js#L84-L90

**Comment by wmhilton** [comment]
This is an excellent time for me to mention: you can see exactly which browsers the test suite ran again at the time of publishing for any given npm version! You can look in `node_modules/isomorphic-git` at `browser-tests.json` (or `dist/browser-tests.json` in the 0.x versions).

https://unpkg.com/browse/isomorphic-git@1.1.6/browser-tests.json

```json
[
  "HeadlessChrome 0.0.0 (Linux 0.0.0)",
  "Firefox 73.0.0 (Ubuntu 0.0.0)",
  "Chrome Mobile 80.0.3987 (Android 0.0.0)",
  "Chrome 79.0.3945 (Windows 10 0.0.0)",
  "Safari 13.0.3 (Mac OS X 10.15.1)",
  "Mobile Safari 13.0.0 (iOS 13.0.0)"
]
```

Well, it mostly works. Some of the version numbers show up as 0.0.0, and Edge 79 shows up as Chrome 79.

**Comment by shd101wyy** [comment]
Hi @wmhilton . Thank you for your reply. 
I am currently using iOS 13.3.1, which is the latest version.  
I will take a look at the test suite. Thank you

**Comment by shd101wyy** [comment]
BTW, does the guide website works on your phone? Thanks!

**Comment by wmhilton** [comment]
> BTW, does the guide website work on your phone?

Yup! The cloning takes a while, but it finishes successfully on my phone. (I'm running Android though.)

**Comment by shd101wyy** [comment]
Yep I tried it on my fathers android phone and worked well. 
I am closing this issue now cuz I assume the issue might be caused by my deployment.

**Comment by shd101wyy** [comment]
Thank you for the help!
