### ISSUE TITLE
Error when pushing without "ref"

### ISSUE THREAD

**Issue by juancampa** [isomorphic-git/isomorphic-git#108]
The documentation says that `push` doesn't require a `ref` but I get the following if I don't specify it:

```
Cannot read property 'startsWith' of undefined
    at Object.push (commands.js:841)
```

The error goes away if I pass a `ref`.

Thanks for this amazing library

**Comment by juancampa** [comment]
Documentation says

> Which branch to push. By default this is the currently checked out branch.

**Comment by TomasHubelbauer** [comment]
I would like to take a look at this this weekend, so I am assigning myself (hopefully that's okay?). If you get to it sooner or just want to do it yourself, please feel free to unassign me @wmhilton.

**Comment by wmhilton** [comment]
That's amazingly OK to assign yourself! To figure out what the current branch is you can use GitRefManager.resolve on 'HEAD' with a depth limit of... 2, I think? I should probably add a helper function to GitRefManager for getting the current branch.

**Comment by jcubic** [comment]
I use code like this to get the branch:

```javascript
    async function gitBranch(filepath) {
        try {
            var dir = await git.findRoot({fs, filepath});
            var ref = await git.resolveRef({fs, dir, ref: 'HEAD', depth: 1});
            return ref.match(/ref: refs\/heads\/(.*)/)[1];
        } catch(e) {
        }
    }
```

**Comment by TomasHubelbauer** [comment]
Actually @jcubic I am unable to work on this at the moment due to time reasons, would you like to take a shot yourself?
