### ISSUE TITLE
readObject v1 returns v0 tree representation

### ISSUE THREAD

**Issue by stefan-guggisberg** [isomorphic-git/isomorphic-git#1080]
Using Node, no bundler.

calling `readObject` to read a tree object should, as of v1 and according to the [doc](https://isomorphic-git.org/docs/en/readObject#parsed-tree-type), return the following object structure:

```js
{
  oid: string;
  type: 'tree';
  format: 'parsed';
  object: Array<TreeEntry>;
}
``` 

However, it still returns the v0 object structure:

```js
{
  oid: string;
  type: 'tree';
  format: 'parsed';
  object: 
  {
    entries: Array<TreeEntry>;
  };
}
```

`readTree` OTOH is consistent with the v1 [doc](https://isomorphic-git.org/docs/en/readTree).

**Comment by wmhilton** [comment]
No..... did I forget to update the tests?! (looks) I did. I didn't update the tests or the code huh. Gosh darn it. Now what do I do? Do I change the types to match the code or change the code to match the types? Ugh.

**Comment by wmhilton** [comment]
I'm leaning towards making it match the docs & types. 'Cause that's totally what I had _intended_ to do. :(

**Comment by stefan-guggisberg** [comment]
@wmhilton Thanks!
