### ISSUE TITLE
oAuth gitlabs unauthorized

### ISSUE THREAD

**Issue by not-Ryan** [isomorphic-git/isomorphic-git#1082]
Hi,
I'm using the Browser version of isomorphic-git via Nuxt and it works great with authentication via username and personal tokens. Now I tried implementing oAuth2 with Gitlab, which works as I thought it would have created an `access_token`. But I can't seem to clone the repository :cry:.

I tried using it like so:
```typescript
    const { data } = await axios.post('.../oauth', { ... oauth body ... });
    const access_token = data.access_token;
    await git.clone({ fs, dir, http, corsProxy, url, onAuth: () => ({ username: 'oauth2', password: access_token }) });
```
But everytime I do this, I get an `HttpError: HTTP Error: 401 Unauthorized`. 
I also tried checking the legitimacy of the access code by requesting `/oauth/token/info`, but that seems to work fine:
```json
{
  "resource_owner_id": 55,
  "scopes": [
    "read_repository",
    "write_repository"
  ],
  "expires_in_seconds": null,
  "application": {
    "uid": "jljvcv8dsf97nhg9jk7m980h7tr9u7u89trtw9rth23jk4bkl65407968017v8c9"
  },
  "created_at": 1583356660
}
```
I am using a self-hosted Gitlab server if that is relevant. If anyone can help me point in the right direction as to why this is happening, I would be very glad.

**Comment by wmhilton** [comment]
Hmm. Well... I'm not sure. But here's a couple ideas.

1. Maybe Bearer Authentication will work? Looking at https://docs.gitlab.com/ee/api/README.html#oauth2-tokens has me thinking this _might_ work?

```js
await git.clone({ fs, dir, http, corsProxy, url, 
  onAuth: () => ({ 
    headers: {
      Authorization: `Bearer ${access_token}`
    }
  })
});
```

2. Maybe it's not a username/password problem at all but an isomorphic-git problem? Try that username & password ('oauth2' & access_token) with the canonical git CLI client, just to rule that out.

**Comment by not-Ryan** [comment]
Yes, I did try that @wmhilton. However, using the `access_token` as Bearer doesn't seem to do anything and oAuth2 & `access_token` gave me an `403 Forbidden` error.
I did resolve my issue by adding `api` access to my oAuth2 requesting application. Also, don't forget to do this inside the code with the `api+write_repository+read_repository` inside the scope.
Still, many thanks for your thoughts!
