### ISSUE TITLE
Return a pretty error if `http` argument is missing

### ISSUE THREAD

**Issue by knownasilya** [isomorphic-git/isomorphic-git#1088]
Currently I get
> Uncaught (in promise) TypeError: Cannot read property 'request' of undefined

Which makes less obvious. I thought I had to add node http to webpack, but that didn't work. Took me a bit to realize that this was a new passed argument like `fs`.

**Comment by wmhilton** [comment]
Oops! Yeah, I'm missing some `assertParameter` calls. Uno momento...
