### ISSUE TITLE
push returning 401 Unauthorized

### ISSUE THREAD

**Issue by knownasilya** [isomorphic-git/isomorphic-git#1093]
Using the browser with latest version I get `No anonymous write access.` but all worked well before. Here's my code:

```js
import * as git from 'isomorphic-git';
import http from 'isomorphic-git/http/web';
import LFS from '@isomorphic-git/lightning-fs';

// ...

    yield git.push({
      fs,
      http,
      dir: '/',
      remote: 'origin',
      ref: branchName,
      oauth2format: 'github',
      token: this.session.accessToken
    });
```

<img width="536" alt="Screen Shot 2020-03-21 at 2 55 51 PM" src="https://user-images.githubusercontent.com/34726/77234361-1b886480-6b84-11ea-9ba8-acc7029320a8.png">

**Comment by wmhilton** [comment]
version 1.0 has a lot of breaking changes. you can read about them here: https://isomorphic-git.org/blog/2020/02/25/version-1-0-0#10-breaking-changes

**Comment by knownasilya** [comment]
Oh, missed the onAuth replacing old formats! Thanks!
