### ISSUE TITLE
 “clone” after “rm -rf dir”, cannot clone successfully

### ISSUE THREAD

**Issue by z008hy** [isomorphic-git/isomorphic-git#1096]
- whether you are using Node or the Browser
NODE

```js
import { remove } from 'fs-extra';
import path from 'path';
import fs from 'fs';
import git from 'isomorphic-git';
import http from 'isomorphic-git/http/node';

const repoDir = "***"
const gitRepo = "***"

await remove(repoDir);
await git.clone({
    fs,
    http,
    dir: repoDir,
    url: gitRepo,
    onMessage: console.log,
    singleBranch: true,
  });
```

when i first run this, It's ok. 
But when I second run this. 
There is only one  ".git"  file in the "repoDir" directory.
when i run "git status". It's show:
deleted:    package.json
deleted:    **.js
deleted:    **/**.js

I'm confused.

I just want reset my repoDir.

**Comment by jcubic** [comment]
i you delete the files and want to clone again  think you need to detele all the files inside including hidden like .git, or delete container directory.

But in my library I use this instead to reset the repo:
```javascript
async function gitReset({fs, dir, ref, branch, hard = false}) {
    var re = /^HEAD~([0-9]+)$/
    var m = ref.match(re);
    if (m) {
        var count = +m[1];
        var commits = await git.log({fs, dir, depth: count + 1});
        return new Promise((resolve, reject) => {
            if (commits.length < count + 1) {
                return reject('Not enough commits');
            }
            var commit = commits.pop().oid;
            fs.writeFile(`${dir}/.git/refs/heads/${branch}`, commit + '\n', (err) => {
                if (err) {
                    return reject(err);
                }
                if (!hard) {
                    resolve();
                } else {
                    // clear the index (if any)
                    fs.unlink(`${dir}/.git/index`, (err) => {
                        if (err) {
                            return reject(err);
                        }
                        // checkout the branch into the working tree
                        git.checkout({ dir, fs, ref: branch }).then(resolve);
                    });
                }
            });
        });
    }
    return Promise.reject(`Wrong ref ${ref}`);
}
```

**Comment by jcubic** [comment]
But I didn't test it with version 1.0 though.

**Comment by z008hy** [comment]
> i you delete the files and want to clone again think you need to detele all the files inside including hidden like .git, or delete container directory.
> 
> But in my library I use this instead to reset the repo:
> 
> ```js
> async function gitReset({fs, dir, ref, branch, hard = false}) {
>     var re = /^HEAD~([0-9]+)$/
>     var m = ref.match(re);
>     if (m) {
>         var count = +m[1];
>         var commits = await git.log({fs, dir, depth: count + 1});
>         return new Promise((resolve, reject) => {
>             if (commits.length < count + 1) {
>                 return reject('Not enough commits');
>             }
>             var commit = commits.pop().oid;
>             fs.writeFile(`${dir}/.git/refs/heads/${branch}`, commit + '\n', (err) => {
>                 if (err) {
>                     return reject(err);
>                 }
>                 if (!hard) {
>                     resolve();
>                 } else {
>                     // clear the index (if any)
>                     fs.unlink(`${dir}/.git/index`, (err) => {
>                         if (err) {
>                             return reject(err);
>                         }
>                         // checkout the branch into the working tree
>                         git.checkout({ dir, fs, ref: branch }).then(resolve);
>                     });
>                 }
>             });
>         });
>     }
>     return Promise.reject(`Wrong ref ${ref}`);
> }
> ```

Thanks for your help.😄
I test my problem again, I find it's not because of ”isomorphic-git“.
My case happened when using electron. I try without electron, It's ok.
