### ISSUE TITLE
git submodule foreach

### ISSUE THREAD

**Issue by vitorcamachoo** [isomorphic-git/isomorphic-git#1116]
Hii, 

Its it possible with this package to have something similiar to `git submodule foreach ....` ?

Thanks

**Comment by jcubic** [comment]
AFIK submodules are not supported by isomorphic-git you can help adding this feature if this is something you need.

PS: Sorry for the late reply but the project was in a suspended state, and I just become a new maintainer and I'm handling all issues, one by one.
