### ISSUE TITLE
Gitlab repositories need `.git` appended (for pull, at least)

### ISSUE THREAD

**Issue by Mstrodl** [isomorphic-git/isomorphic-git#1122]
I'm using node with a private gitlab repo:
```js
await IsoGit.pull({
  dir: hh.hhDir,
  fs,
  http,
  author,
  committer: author,
});
```
Fairly ordinary I would hope, `dir` points to a dir with a remote set up that includes auth headers in the url. The initial `/info/refs` request completes without error, but the `POST git-upload-pack` request fails with a 404 unless the url has `.git` appended to it.

I'm using `isomorphic-git@1.1.0`.
Possible duplicate of #671 ? Unsure though, as I don't believe there is any redirecting happening behind the scenes and this is just a straight 404...

**Comment by OriginalEXE** [comment]
Thank you. this was an issue for me as well when trying to clone a private GitHub repository. Just adding a `.git` at the end of the repo url fixed the issue.
