### ISSUE TITLE
`_readObject` caching?

### ISSUE THREAD

**Issue by hsablonniere** [isomorphic-git/isomorphic-git#1138]
Hey William and isomorphic-git team :wink:

We are going through a major update on our CLI at Clever Cloud (0.37.0 to latest) and we encountered some perf problems.

One of those problems concerns `push` and how `listObjects` and others use `_readObject`.

## Test context

We ran our tests on 2 projects:

Thank you `git-sizer`

* repo WWW
  * 2.2k commits
  * 10.7k trees
  * 164k tree entries
  * 4.7k blobs
  * 4.7 MiB for biggest blob
* repo CONSOLE
  * 3.4k commits
  * 14.8k trees
  * 266k tree entries
  * 8.1k blobs
  * 443 KiB for biggest blob

We timed the execution of a `push` in this situation:

Pushing to an empty repo.

## Tests results

* We added timers around `listCommitsAndTags`, `listObjects` and `_pack`.
* We also wrapped `_readObject` so we could count how many times _readObject was called.

Here's what we observed...

NOTES:

* `_readObjectCounts` is cumulative over the whole push and results are after the step.
* Those tests are based on the improvement from #1132 (early return in `_findMergeBase`)

Repo WWW:

```
_findMergeBase: 2.232ms
  _readObjectCounts: 0
listCommitsAndTags: 730.744ms
  _readObjectCounts: 2238
listObjects: 69063.461ms
  _readObjectCounts: 253215
_pack: 27804.190ms
  _readObjectCounts: 270889
GitRemoteHTTP.connect: 73617.976ms
```

OBSERVATIONS:

* `listCommitsAndTags` calls `_readObject` 2238 times for 2.2k commits, seems legit
* `listObjects` calls `_readObject` 250977 times, it seems a bit much for our stats
* `listObjects` takes 69 secs

Repo CONSOLE:

```
_findMergeBase: 2.564ms
  _readObjectCounts: 0
listCommitsAndTags: 859.625ms
  _readObjectCounts: 3435
listObjects: 51421.369ms
  _readObjectCounts: 275721
_pack: 20403.404ms
  _readObjectCounts: 302009
```

OBSERVATIONS:

* `listCommitsAndTags` calls `_readObject` 3435 times for 3.4k commits, seems legit
* `listObjects` calls `_readObject` 272286 times, it seems a bit much for our stats
* `listObjects` takes 51 secs

## Proposed solution

Our naïve solution to fit our context: add a wrapper around `_readObject` that caches the result in a Map, keyed by `oid:format`.

:tada: This was a major improvement:

Here's what we observed...

NOTES:

* `_readObjectCacheCounts` is the cumulative count of cache hits

Repo WWW:

```
_findMergeBase: 2.226ms
  _readObjectCounts: 0
  _readObjectCacheCounts: 0
listCommitsAndTags: 719.370ms
  _readObjectCounts: 2238
  _readObjectCacheCounts: 0
listObjects: 9190.249ms
  _readObjectCounts: 253215
  _readObjectCacheCounts: 240273
_pack: 25733.295ms
  _readObjectCounts: 270889
  _readObjectCacheCounts: 253215
```

OBSERVATIONS:

* `listObjects` calls `_readObject` 250977 times but 240273 of those calls (96%) hit the cache
  * We're not sure yet but we assure it's all those tree entries that are the same between commits.
* `listObjects` now takes 9 secs (instead of 69 secs)

Repo CONSOLE:

```
_findMergeBase: 0.695ms
  _readObjectCounts: 0
  _readObjectCacheCounts: 0
listCommitsAndTags: 4303.556ms
  _readObjectCounts: 3435
  _readObjectCacheCounts: 0
listObjects: 10974.619ms
  _readObjectCounts: 275721
  _readObjectCacheCounts: 257504
_pack: 14812.569ms
  _readObjectCounts: 302009
  _readObjectCacheCounts: 275721
```

OBSERVATIONS:

* `listObjects` calls `_readObject` 272286 times but 257504 of those calls (95%) hit the cache
  * We're not sure yet but we assure it's all those tree entries that are the same between commits.
* `listObjects` now takes ~11 secs (instead of 51 secs)

## Do we need a memory cache like?

Clearly we would understand how this could be a problem in many situations. So we're not saying let's do this but the perfomance gain are too impressive not to discuss the idea. WDYT?

## Other solutions

We also tried to directly cache `fs.readFile` from outsite isomorphic-git but the result were not as good as those.

**Comment by wmhilton** [comment]
Oh. I think I see the problem. There's no need to cache `_readObject`... we can just be smart and not call it more than we need to 🤦‍♂️. PR incoming...
