### ISSUE TITLE
clone throws error about setting `force:true` but value hard coded

### ISSUE THREAD

**Issue by knownasilya** [isomorphic-git/isomorphic-git#1140]
Using in the browser with lightning-fs, latest version 1.4

```js
AlreadyExistsError: Failed to create remote at origin because it already exists. (Hint: use 'force: true' parameter to overwrite existing remote.)
    at _addRemote (webpack://__ember_auto_import__/./node_modules/isomorphic-git/index.js?:5749:15)
    at async _clone (webpack://__ember_auto_import__/./node_modules/isomorphic-git/index.js?:8537:3)
    at async Module.clone (webpack://__ember_auto_import__/./node_modules/isomorphic-git/index.js?:8672:12)
```

Get this when cloning, but the value is hard coded in `clone` source when adding remote.

**Comment by knownasilya** [comment]
Any ideas how to get around this?

**Comment by knownasilya** [comment]
Ping?

**Comment by countnazgul** [comment]
Same question from me as well. 
Works fine with the example repo (`https://github.com/isomorphic-git/lightning-fs`). 

But I'm getting the same `AlreadyExistsError` with a brand new repository

**Comment by wmhilton** [comment]
I recommend running `clone` in an empty directory. (LightningFS has a `wipe` option you might find useful.)

**Comment by countnazgul** [comment]
Thanks for confirming this. Ive realised that it might be a file system issue and wiped (manually) all storage options in chrome and it worked ok. 

Thanks again for your reply!
