### ISSUE TITLE
Diff command missing

### ISSUE THREAD

**Issue by jtlimo** [isomorphic-git/isomorphic-git#1144]
Hi, I found this project, and I really like, but unfortunately I missing the diff command; I intend to use the lib to get git diff command to implements at mutation test; 

Thanks for all the work with this lib.

**Comment by jcubic** [comment]
This is probably out of scope, there are diff libraries out there that you can use. I've used [jsDiff](https://www.npmjs.com/package/diff) in my project.

**Comment by jtlimo** [comment]
> This is probably out of scope, there are diff libraries out there that you can use. I've used [jsDiff](https://www.npmjs.com/package/diff) in my project.

I want to get diff between commits;

```
git diff --name-only 754fba5a06c795be2e6b31a94d436d3d877efdaa 2093796fcbab0026ee855b05242b2240cf33d7cb
```

just like above git command;

**Comment by jcubic** [comment]
What you need is git status between two commits check #732 I should probably implement the same in my project (it's git terminal in browser) including full git diff between commits.

**Comment by jtlimo** [comment]
@jcubic Thanks for sharing the implementation; It's works fine! 

I'm working in implementation my idea in this repository: https://github.com/jtlimo/stryker-example

**Comment by jcubic** [comment]
I'm closing as out of scope
