### ISSUE TITLE
Regression when pusing repo with a submodule

### ISSUE THREAD

**Issue by hsablonniere** [isomorphic-git/isomorphic-git#1185]
Hi @wmhilton and team :wink: 

I'm trying to update to latest 1.7.0 which contains the 4 bugfix we were waiting for (thanks again for those :clap:):

* https://github.com/isomorphic-git/isomorphic-git/issues/1131
* https://github.com/isomorphic-git/isomorphic-git/issues/1134
* https://github.com/isomorphic-git/isomorphic-git/issues/1136
* https://github.com/isomorphic-git/isomorphic-git/issues/1138

It seems to work really well except on repos with submodules.
I get an error during `pack` on reading the oid which is actually the commit of the submodule.

After a quick investigation, I don't understand what happened here: https://github.com/isomorphic-git/isomorphic-git/pull/1151/files#diff-5fe65229494ade9f3425b0be5846f749

Seems like we had:

```
if (entry.type === 'blob' || entry.type === 'tree') {
  visited.add(entry.oid)
```

and we changed it to:

```
if (entry.type === 'blob' || entry.type === 'commit') {
  visited.add(entry.oid)
```

This means the oid of the commit from the submodule ends up in the list of objects and during a push, the `pack` function is unable to read this very object.

On our reduced test case (simple repo with one submodule), this fixes the problem:

```
if (entry.type === 'blob') {
  visited.add(entry.oid)
```

**Comment by wmhilton** [comment]
Oooooops. What was I thinking?
