### ISSUE TITLE
New branches are not shown in listBranches

### ISSUE THREAD

**Issue by robert-cronin** [isomorphic-git/isomorphic-git#1213]
Please be sure to mention:
- whether you are using Node or the Browser
Node, version 1.7.4
- how you are using it (if you are using a bundler what bundler; if you are using a `<script>` tag what CDN URL)
using it with ts-node in a test script

How to replicate:
1) create a new remote repository
2) use isomorphic git to do initial clone:
```
import fs from 'fs'
import http from 'isomorphic-git/http/node'
import git from 'isomorphic-git'

const dir = './test-git-dir'
await git.clone({
  fs,
  http,
  dir,
  url: 'https://github.com/robert-cronin/test-git.git'
})

console.log(await git.listBranches({fs, dir})); // [ 'master' ]
```
3) create `new-branch` on remote repository and pull:
```
await git.pull({
  fs,
  http,
  dir,
  author: {
    name: 'Robbie'
  }
})

console.log(await git.listBranches({fs, dir})); // [ 'master' ]
```

If I check with command line git, the branch is available for checking out and if I do that, isomorphic git now shows the `new-branch`

**Comment by CabezaCono** [comment]
I try this: create a commit for this new branch, and now show it

**Comment by robert-cronin** [comment]
@CabezaCono thanks for the tip, in the end I got it working a slightly different way and it looks like its consistent with how command line git is working
By default git doesn't download all branches, but on the CLI you can do `git branch -a` to see remote branches, I am not sure what the equivalent would be in isomorphic-git.
What I did to get the new branch was to checkout first and then list:
```
  await git.checkout({
    fs,
    dir,
    ref: 'new-branch'
  })
  console.log(await git.listBranches({ fs, dir })); // [ 'master' ]
```
