### ISSUE TITLE
IPFS/IPLD remote support, perhaps by plugin?

### ISSUE THREAD

**Issue by snickell** [isomorphic-git/isomorphic-git#1223]
It'd be really cool if you could use `isomorphic-git` to push to/from `IPFS` objects.

**Comment by snickell** [comment]
@wmhilton I'm considering tackling this, I know a couple/few years ago you might have thought through some details on this, do you have anything written up, or suggestions on the feasibility, where you'd start in the iso-git codebase, etc?

I like the properties of the IPFS object structure created by [git remote ipfs)(https://github.com/dhappy/git-remote-ipfs), so I was going to default to trying to extend ismorphic git to generate the same.

I'm guessing that large portions of iso-git won't be relevant.... I haven't found if iso-git has a similar remote hook structure to C git... that would of course be idea because I could swipe git-remote-ipfs code pall mall ;-)

**Comment by snickell** [comment]
After a quick scan of the codebase, it looks like the implementation path would be:
1. Implement GitRemoteIPFS, either as a subclass of [GitRemoteHTTP(https://github.com/isomorphic-git/isomorphic-git/blob/e66a6c2f8ee7a6630eeaeb0665a68c4eb4f2bb0f/src/managers/GitRemoteHTTP.js#L48), or (perhaps...) extract `class GitRemote` out of `class GitRemoteHTTP`, and subclass that. Or just implement the same protocol and call it a day. QUACK!

2. Edit [GitRemoteManager.js](https://github.com/isomorphic-git/isomorphic-git/blob/e66a6c2f8ee7a6630eeaeb0665a68c4eb4f2bb0f/src/managers/GitRemoteManager.js#L47) to not create a `new Map()` from scratch, and add a registerRemoteManager() function that extends a global map. Then use it to register GitRemoteHTTP.

3. Profit?

**Comment by snickell** [comment]
It looks like we'd have to see if the [git remote ipfs](https://github.com/dhappy/git-remote-ipfs) object structure would let us implement the pack protocol, namely the following:

```
GitRemoteIPFS.discover({ service: 'git-receive-pack' })
GitRemoteIPFS.discover({ service: 'git-upload-pack' })
GitRemoteIPFS.connect({ service: 'git-receive-pack' }) 
GitRemoteIPFS.connect({ service: 'git-upload-pack' })
```

**Comment by snickell** [comment]
Huh, am I correct in my read that isomorphic git doesn't support the v1 style "dumb client/server" git HTTP protocol, based around the fetch, push, etc capabilities?

**Comment by snickell** [comment]
Ah yes, it appears that the dumb protocol is not supported: https://github.com/isomorphic-git/isomorphic-git/issues/672 , making this more fun :-)

**Comment by snickell** [comment]
For my reference: https://git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols#:~:text=The%20smart%20protocol%20is%20a,a%20custom%20packfile%20for%20it.

**Comment by jcubic** [comment]
I would just implement a custom fs client that interacts with IPFS. See documentation for details https://isomorphic-git.org/docs/en/fs

PS: Sorry for the late reply but the project was in a suspended state, and I just become a new maintainer and I'm handling all issues, one by one.

**Comment by jcubic** [comment]
Note that if you implement something like this, you can share the link to the project I may include it in documentation.
