### ISSUE TITLE
error when trying to push after pull

### ISSUE THREAD

**Issue by gilsmdt** [isomorphic-git/isomorphic-git#1231]
I'm testing the following scenario
1. clone the repo
2. change file A locally (pfs.writeFile, git.add, git.commit)
3. change file B on remote repo
4. pull
5. commit
6. push

I'm trying to pull changes before pushing my changes back to the remote repo to avoid not-fast-forward error.
I get the following error
TypeError: Cannot read property 'packfiles' of undefined
    at s (isomorphic-git:8)
    at isomorphic-git:8
    at Generator.next (<anonymous>)
    at a (isomorphic-git:8)
    at s (isomorphic-git:8)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:167)

I've also tried to remove the commit step and I get the same error.
Following that I've downloaded the source code of isomorphic-git to try and locate the issue and located the mentioned error at the following line readPackIndex.js (line 23) file, seems like the cache object is undefined for some reason, not really sure why
if (!cache.packfiles) cache.packfiles = new Map()

When there are no changes on the remote repo everything is fine, meaning even if I call pull before push but there are no changes pushing the change to the remote repo is successful.

**Comment by wmhilton** [comment]
> seems like the cache object is undefined for some reason, not really sure why
> When there are no changes on the remote repo everything is fine, meaning even if I call pull before push but there are no changes pushing the change to the remote repo is successful.

Thanks! That should help me narrow it down quickly. Just found about about this in production at Stoplight too so working on a fix ASAP. Pretty sure was was introduced in 1.7.5 - using 1.7.4 for now should save the day.

**Comment by wmhilton** [comment]
@gilsmdt Would you mind terribly confirming whether my "fix" actually works? I'm fairly sure I fixed it but was unable to actually reproduce the original error so I'm not positive I fixed it. 🤷‍♂️
