### ISSUE TITLE
Github Contents API as backend for shallow repos

### ISSUE THREAD

**Issue by vadimkantorov** [isomorphic-git/isomorphic-git#1236]
Hi!

I'm building an client-side browser-only LaTeX editor (successfully compiled xetex+bibtex+dvipdfmx to WASM). It currently gets files from GitHub via Contents API (file-based CORS-friendly API). It currently pushes updates to GitHub via Contents API as well. It targets repos for scientific papers with only a few concurrent users that contain limited amount of tex files, so just Deploy Key or Personal Access Token authorization is enough.

I'd like to support some sort of git operations locally as well, as well as pulling new updates from GitHub, rebasing on top of them and pushing commits to GitHub. I don't want to always download all commits and their data from GitHub Git Data API, since it leads to too many API requests.

From what I understood, Isomorphic Git currently supports GitHub as a backend only via a CORS proxy. Would it be possible to add a GitHub API-based backend that would clone shallow repos? What kind of operations does it need to support?

**Comment by jcubic** [comment]
Sorry for the late reply but the project was in a suspended state, and I just become a new maintainer and I'm handling all issues, one by one.

I'm closing all the questions that I don't know answer to, You can try to ask on StackOverflow or sister projects.
