### ISSUE TITLE
Performance regression reading trees in 1.7.5

### ISSUE THREAD

**Issue by mdekstrand** [isomorphic-git/isomorphic-git#1237]
I am using isomorphic-git in Node to scan Git history to get last-modified times for my static web site build.

Beginning with 1.7.5, the scanning process (listing commits with `log`, and then iteratively scanning commit trees with `readTree`) is unusably slow. My code is running as expected with 1.7.4. I discovered this when upgrading (last update was using 1.3), and then incrementally tried published versions to isolate the problem to the 1.7.5 upgrade.

Here is the function from my code that is unusably slow:

```javascript
const scanDir = {
  pages: true,
  pubs: true,
  blog: true
};

async function* scanPathEvents(dir) {
  let seen = {};

  async function* scanTree(commit, oid, path) {
    let treeR = await git.readTree({fs, dir, oid: oid});
    let tree = treeR.tree;
    for (let e of tree) {
      if (seen[e.oid]) continue;
      if (path == '' && !scanDir[e.path]) continue;
      seen[e.oid] = true;

      if (e.type == 'tree') {
        yield* scanTree(commit, e.oid, path + e.path + '/');
      } else if (e.type == 'blob') {
        yield {
          path: path + e.path,
          date: commit.author.timestamp
        };
      }
    }
  }

  let log = await git.log({fs, dir});
  logger.info('got %d history entries', log.length);
  log.reverse();
  for (let rc of log) {
    yield* scanTree(rc.commit, rc.commit.tree, '');
  }
}
```

The `log` call is not exhibiting slowdown; it seems the problem is in `readTree`.

I would be happy to give an Isomorphic developer access to the repository exhibiting this problem if it would help with debugging.

**Comment by wmhilton** [comment]
Yikes. Yes it's like the difference between 50 seconds and 600 milliseconds testing locally with very similar code on my `docs` folder.

Ugh. It makes me so sad, that fixing a memory leak destroyed performance for so many by default. Ugh. Well, at least the `cache` parameter is relatively simple. And I can always change the default behavior later to use an LRU cache or something I suppose.

**Comment by mdekstrand** [comment]
I have upgrade to 1.8.0 and updated my code to use the new `cache` parameter, and it is back to acceptable performance.

Thank you very much, @wmhilton, and thank you for making isomorphic-git. It's been a great library for my needs.
