### ISSUE TITLE
resolveRef cannot find HEAD~1

### ISSUE THREAD

**Issue by thomas-jakemeyn** [isomorphic-git/isomorphic-git#1238]
I am using **isomorphic-git 1.7.8** (aka the latest published version at the time of writing) with **Node**. I get the error below when passing `HEAD~1` as `ref` to the function `resolveRef`.

```
NotFoundError: Could not find HEAD~1.
```

Since the `ref` is passed as a command-line argument to my tool, a workaround is to fall back on `git` and pass `$(git rev-parse HEAD~1)` from the shell. But this is obviously not ideal...

Thank you for your support and for this great library!

**Comment by jcubic** [comment]
Unfortunately relative references are not handled by the library. You need to use git.log to get the proper ref. This is how I use this in my code (it use version before 1.x but it should be the same in latest version):

```javascript
async function gitReset({git, dir, ref, branch, hard = false}) {
    var re = /^HEAD~([0-9]+)$/;
    var m = ref.match(re);
    if (m) {
        var count = +m[1];
        var commits = await git.log({dir, depth: count + 1});
        return new Promise((resolve, reject) => {
            if (commits.length < count + 1) {
                return reject('Not enough commits');
            }
            var commit = commits.pop().oid;
            fs.writeFile(`${dir}/.git/refs/heads/${branch}`, commit + '\n', (err) => {
                if (err) {
                    return reject(err);
                }
                if (!hard) {
                    resolve();
                } else {
                    // clear the index (if any)
                    fs.unlink(`${dir}/.git/index`, (err) => {
                        if (err) {
                            return reject(err);
                        }
                        // checkout the branch into the working tree
                        git.checkout({ dir, ref: branch }).then(resolve);
                    });
                }
            });
        });
    }
    return Promise.reject(`Wrong ref ${ref}`);
}
```

**Comment by jcubic** [comment]
Sorry for the late reply but the project was in suspended state, and I just become new maintainer and I'm handling all issues, one by one.

**Comment by jcubic** [comment]
So you can use my code to create resolveRef like you need:
```javascript
async function ref({git, dir, fs }) {
    var re = /^HEAD~([0-9]+)$/;
    var m = ref.match(re);
    if (m) {
        var count = +m[1];
        var commits = await git.log({dir, fs, depth: count + 1});
        return commits.pop().oid;
    }
   return git.resolveRef({ dir, fs, ref });
}
```

**Comment by mmkal** [comment]
@jcubic would you be open to pull request adding something like the above to the library? Btw, thank you for picking development back up!

**Comment by jcubic** [comment]
I think it will be really hard to make it right. there are lot of references in git you can use a lot of different syntaxes. You would need to have a parser to implement them all. To give you perspective there are ^ that pick the branch if this is a merged branch. So you can use funky stuff like HEAD~2^1 and you probably I didn't test combine ^ and ~ into the longer chain.

This is just an edge case that will need to complicate the library and it's worth it. if something will need ^ he will need to implement this herself.

I prefer to document this as separated code where I show how to implement single `HEAD~2^2` and someone wants more he can implement a full parser on top of isomorphic-git.

Actually, I can implement this in my project [Git Web Terminal](https://github.com/jcubic/git) which is a better place for something like this. If I ever implement `HEAD .. ^` I probably be the only project that uses this.
