### ISSUE TITLE
Is readObject() actually deprecated?

### ISSUE THREAD

**Issue by chmac** [isomorphic-git/isomorphic-git#1239]
I saw this for the first time in VSCode:

<img width="161" alt="image" src="https://user-images.githubusercontent.com/690997/95554539-a0e44100-0a10-11eb-999a-27edb086e5b1.png">

Turns out that the ~strikethrough~ means that `readObject()` is deprecated. I see the note that this function is overly complicated and you recommend using the others *WHEN* you know what type of object to retrieve. However, in my case, I'm getting every object in the repo, so I'm putting every objectId into a Set and then grabbing them all. In this case, I don't know, nor do I care, what type of object it is.

As I read the text, it seems like the notice is more of a warning rather than a deprecation. Unless you plan to remove the `readObject()` API in a future release?

**Comment by jcubic** [comment]
There is `@deprecated` typing added to this function, but I don't think it will ever be removed from the library. I think that depression is only used to add warnings in generated documentation to use a different methods if possible.

**Comment by jcubic** [comment]
Sorry for the late reply but the project was in suspended state, and I just become new maintainer and I'm handling all issues, one by one.

**Comment by chmac** [comment]
@jcubic I think that the `@deprecated` tag means that this code will be removed in future. I'd suggest removing it and instead using something in the docs to warn against using the function unless strictly necessary. It seems to me like if there's no plan to remove the function, it doesn't meet the requirements to be deprecated and so the tag is misleading...
