### ISSUE TITLE
GitHub is deprecating password authentication

### ISSUE THREAD

**Issue by alex996** [isomorphic-git/isomorphic-git#1244]
From [Basic Authentication](https://docs.github.com/en/free-pro-team@latest/rest/overview/other-authentication-methods#via-oauth-and-personal-access-tokens) in GitHub REST API docs:

> **Deprecation Notice:** GitHub will discontinue password authentication to the API. You must now authenticate to the GitHub API with an API token, such as an OAuth access token, GitHub App installation access token, or personal access token, depending on what you need to do with the token. Password authentication to the API will be removed on November 13, 2020. For more information, including scheduled brownouts, see the [blog post](https://developer.github.com/changes/2020-02-14-deprecating-password-auth/).

The linked blog post suggests that

```sh
curl -u my_user:my_password https://api.github.com/user/repos`
```

should be changed to

```sh
curl -H 'Authorization: token my_personal_access_token' https://api.github.com/user/repos
```

It is not clear whether Basic auth [via OAuth and personal access tokens](https://docs.github.com/en/free-pro-team@latest/rest/overview/other-authentication-methods#via-oauth-and-personal-access-tokens) will continue to work. In other words, will the following still work once the API changes are rolled out?

```sh
curl -u my_user:my_personal_access_token https://api.github.com/user/repos
```

Either way, I noticed that the library is using Basic Auth for both password and token (OAuth, PAT) authentication ([GitRemoteHTTP.js:22](https://github.com/isomorphic-git/isomorphic-git/blob/629b4e1b4dc4d56fbd2b9e00c0995562a0e0c167/src/managers/GitRemoteHTTP.js#L22) and [calculateBasicAuthHeader.js:2](https://github.com/isomorphic-git/isomorphic-git/blob/63f3a9c7b96bca5ae68f5a553dee9d7c12cc8928/src/utils/calculateBasicAuthHeader.js#L2), also documented [here](https://isomorphic-git.org/docs/en/onAuth#personal-access-tokens)), which will probably break soon.

Thought I'd bring it to your attention. Thanks!

**Comment by wmhilton** [comment]
Thanks! This library doesn't use the GitHub API, it uses the Git HTTP Protocol, which will probably continue to use Basic Auth for another decade or more. But thanks for the info.

**Comment by wmhilton** [comment]
Well. GitHub just announced they will be deprecating using username:password for git operations including git command line stuff: https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

Personal access token based authentication will still be supported though, so I encourage users to a) enable 2FA on their accounts if they haven't already and b) convert the personal access token to basic auth using the procedure here: https://isomorphic-git.org/docs/en/onAuth#personal-access-tokens
