### ISSUE TITLE
Unable to clone repository

### ISSUE THREAD

**Issue by sginer** [isomorphic-git/isomorphic-git#1254]
Using isomorphic in node

The same code work fine in isomorphic 0.67.3 but alwais return 404 in isomorphic 1.7.8

`
// Clone remote repository from this URL

const git = require("isomorphic-git");
const fs = require("fs");
const axios = require('axios')

function cloneGitHubRepository(dir, url, pat, gitUser, tag) {
    return git.clone({
        fs : fs,
        http: axios,
        dir: dir,
        url: url,
        username : gitUser,
        token : pat,
        ref: tag
    }).then(() => {
        return "ok";
    }).catch((error) => {
        console.log("Unable to clone repository !")
        console.log(error);
        return Promise.reject(error);
    })
}

module.exports = cloneGitHubRepository;
`

**Comment by sginer** [comment]
Sorry 
I dont sée that username and token must ne set on thé onAuth func nos.

Regard!

**Comment by y-nk** [comment]
@sginer you also need to pass token as password.

```
git.clone({ onAuth: () => ({ username: 'github_username', password: 'personal_token' }) })
```
