### ISSUE TITLE
Demo don't work

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#1258]
Just checked the demo on the website and it don't work:

```
UrlParseError: Cannot parse remote URL: "github.com/facebook/react.git
```

tested in Google Chrome on Fedora GNU/Linux. Just to be sure I've tried in incoginito mode where I don't have any extensions and  got the same error. Sorry I'm not sure why it's happening, but this is urgent since most new visitors can try to the library.

**Comment by jcubic** [comment]
The problem is this line:

value = value.replace(/^https?:\/\//, '')

in https://isomorphic-git.org/js/try-it-out-giturl.js if I remove that line (I've stopped the script in debugger just after that line and added back the "https://") then it works. I have no idea why this line is there?

**Comment by micalevisk** [comment]
thus basically the workaround to test the demo is type `https://https://github.com/facebook/react` instead.

**Comment by wmhilton** [comment]
> I have no idea why this line is there?

to use a protocol relative url (`//github.com/facebook/react.git`) maybe? Not sure. Will remove.
