### ISSUE TITLE
How do you read a blob from a staging index?

### ISSUE THREAD

**Issue by paramaw** [isomorphic-git/isomorphic-git#1261]
I've looked at the documentation, but could not find a way to read a Blob from the staging index.

I need this blob so that I can do a diff between the file on the HEAD and on the staging index.

Please advise,

Thanks.

**Comment by ROWEND36** [comment]
There is no blob in the staging index only a shasum. You can know if a file has changed using git.status but thats all.

**Comment by jcubic** [comment]
@paramaw does this solve your issue?

**Comment by paramaw** [comment]
I'm currently not working on the piece of code related to this anymore. Thanks for the suggestion.
