### ISSUE TITLE
Is it possible to reset ALL files in the current index (staging area)?

### ISSUE THREAD

**Issue by Muhlex** [isomorphic-git/isomorphic-git#1262]
I am using isomorphic-git on the server side to pull a repo without any contents, because I just want to add a single file and push that change. The last challenge I'm facing is that when cloning the repo without checking out files (because I don't want to download the whole thing), all of the file "removals" are staged in the index.
```js
await git.clone({ fs, http, dir, url,
  depth: 1,
  singleBranch: true,
  noCheckout: true
});
```

Now I would like to unstage all those file deletions (effectively unstage all files that exist in the current commit), so that I can only commit the addition of my new file afterwards. The `resetIndex` method allows me to do that for a single file only. I don't have references to the files though, as I'm not pulling them. Basically the functionality of `git reset` would be perfect. Is there a way to do this currently?

**Comment by Muhlex** [comment]
After consulting the docs more, this is actually quite trivial to do. My solution:

```js
const files = await git.listFiles({ fs, dir, ref: 'HEAD' });
for (const filepath of files) {
  await git.resetIndex({ fs, dir, filepath })
}
```

**Comment by MarsOrBust24** [comment]
> all of the file "removals" are staged in the index.

This seems like a major bug. I encountered this when running `add + commit` on one file caused all other files to be deleted. Seems like a bug on the stage status system, the default should be `identical-to-head` not `absent`, regardless of whether noCheckout was used.
