### ISSUE TITLE
Why is CORS even an issue when iso-git is used on node.js?

### ISSUE THREAD

**Issue by Eric24** [isomorphic-git/isomorphic-git#1273]
I understand the CORS issue when the client is a browser, but I'm really puzzled as to why it's necessary to use a CORS proxy when my client is node.js. Am I missing something?

**Comment by benjdlambert** [comment]
I don't think it is necessary. It works for me without the proxy, but the client just needs the additional header.

**Comment by Eric24** [comment]
Oh, what header is that?

**Comment by benjdlambert** [comment]
Something like this works for github at least:

https://github.com/backstage/backstage/blob/blam/isomorphic-git/plugins/scaffolder-backend/src/scaffolder/stages/prepare/github.ts#L63-L79

**Comment by Eric24** [comment]
Ah, thanks! Very strange that this header is needed, but it does seem to work.
