### ISSUE TITLE
Authenticate using deploy key on nodejs 

### ISSUE THREAD

**Issue by diginfo** [isomorphic-git/isomorphic-git#1276]
I am trying to use this module to replace bash commands in a deployed environment, meaning that really all I want to do is to pull and possibly checkout but never push.

The repo is private, and having googled and trawled many pages, I cannot see any way of doing this.

My idea was to create a deploy key that could be encrypted and given to a user, and my node app will decrypt it and use the deploy key to pull updates.

Is this possible ?

**Comment by MarcDAFrame** [comment]
did you figure this out @diginfo ?
