### ISSUE TITLE
clone does not clean up on failure

### ISSUE THREAD

**Issue by strangedev** [isomorphic-git/isomorphic-git#1283]
Please be sure to mention:
- whether you are using Node or the Browser: Node
- how you are using it (if you are using a bundler what bundler; if you are using a `<script>` tag what CDN URL): With TypeScript using `tsc`

Hi everyone 👋 
I've noticed that when clone fails due to an unreachable remote, a `.git` directory is left behind in the chosen `dir`.

Here is what I understand is the source of this problem:
In the [`clone` command, `init()` is called](https://github.com/isomorphic-git/isomorphic-git/blob/26f761e540709da7920db1288469cb9ed5be5c1c/src/commands/clone.js#L62) to create and populate the local directory.
After this, the remote is added, fetched from and finally the default branch is checked out.
Any of these steps may fail, leaving us with a partially complete repository.
In [the API for clone](https://github.com/isomorphic-git/isomorphic-git/blob/26f761e540709da7920db1288469cb9ed5be5c1c/src/api/clone.js#L108), there is an error handler, but it does not do any cleanup.

I feel there should be an error handler from [here](https://github.com/isomorphic-git/isomorphic-git/blob/26f761e540709da7920db1288469cb9ed5be5c1c/src/commands/clone.js#L62) to [here](https://github.com/isomorphic-git/isomorphic-git/blob/26f761e540709da7920db1288469cb9ed5be5c1c/src/commands/clone.js#L92), which should remove the partial repository completely. After fetch has succeeded, it is very likely the repository is viable and does not need to be removed.

I believe binary git handles all error cases in clone by cleaning up partial state completely and I think it would be intuitive for isomorphic git to emulate this behavior.

Thank you for the great project, this is a minor inconvenience and I have otherwise thoroughly enjoyed using it so far!

**Comment by jcubic** [comment]
I think that we can just remove the git directory on failure since when you start the clone you're always in an empty directory (or at least with `.git` repo) you can't clone into git rep.

If anyone want to fix this you're welcome to create a PR.

**Comment by strangedev** [comment]
Hey @jcubic, I've started working on this but discovered that `src/models/FileSystem.js` does not seem to support the recursive option for `fs.rmdir()` or `fs.rm()`. This means we can't currently easily delete the `gitdir` without recursing through it ourselves.

I'll write something to handle this, but maybe you know of some easier way of handling this using the current codebase?

**Comment by mojavelinux** [comment]
> I'll write something to handle this, but maybe you know of some easier way of handling this using the current codebase?

Eventually, I would like to see `fs.rm` used here. Perhaps what we could do is detect if `fs.rm` is a function on the fs object. If it is not, isomorphic-git can patch in its own implementation. That way, we can phase it out as soon as Node.js are dropped.

**Comment by mojavelinux** [comment]
I just noticed that this new code, and some existing code, is using `fs.rm` already. As far as I know, that function isn't available until Node.js 16. It should be `fs.unlink`. How is this code working on Node.js 10?

**Comment by jcubic** [comment]
fs.rm is part of Node if it's added to lighting-fs we can just update the docs, but this may be breaking change since the API will change, users may use their own implementation of fs client.

**Comment by jcubic** [comment]
and about `fs.rm` missing in Node.js maybe it's added by the webpack or babel. Something that need to checked. Maybe looking at bundle file and check if there is `fs.rm`.

**Comment by mojavelinux** [comment]
> about fs.rm missing in Node.js maybe it's added by webpack or babel

It's added by isomorphic-git. See https://github.com/isomorphic-git/isomorphic-git/blob/main/src/models/FileSystem.js#L123-L132

**Comment by mojavelinux** [comment]
> fs.rm is part of Node if it's added to lighting-fs we can just update the docs, but this may be breaking change since the API will change, users may use their own implementation of fs client.

What I'm suggesting would be transparent to the user. I think the `rm` wrapper that isomorphic-git adds should check if `rm` is defined on the underlying `fs` object. If it is, then isomorphic-git should use it. Otherwise, it should use it's own implementation to remove recursively.

It might be best at this point to open a separate issue for this discussion.

**Comment by jcubic** [comment]
But docs should be updated anyway, this way this can be marked as a feature where there is a new method in fs that is utilized.

**Comment by strangedev** [comment]
I agree we should find a portable solution that is a little more sophisticated than the code I hacked up for this issue. At least we should probably integrate the added functionality into the existing fs wrapper. 

I'd be happy to help out 😊 
Feel free to ping me when you open a new issue.

**Comment by jcubic** [comment]
I've added another issue, let's continue the discussion there.
