### ISSUE TITLE
The README is super confusing. How do I use this in the browser?

### ISSUE THREAD

**Issue by carlyounger** [isomorphic-git/isomorphic-git#1307]
This library looks great, but the only clues the README provides for using this library in the browser are broken or confusing.

The **Installation** section only explains how to use Node.

The example code for the browser (the code that loads a bunch of stuff from `unpkg.com`) does not work (if I copy, paste and run the code, the `then` method just logs `undefined`).

The README claims you can do stuff like `import git from 'isomorphic-git'`, but there's no export named `git` (or a default) in the module I have. I probably have the wrong module, but the README provides no clue where to get one from, so I tried the CDN from the broken example code.

I'd ideally like to use this library (and Lightning FS) as ES6 modules, and need to load them from a local server (in development), but do not even know which files I need (I've been doing Web development for over ten years, and normally have no trouble with stuff like this).

Any advice would be appreciated. Thanks.

**Comment by FractalHQ** [comment]
This was my experience as well.  Have you had any luck?

**Comment by crutchcorn** [comment]
Because of [existing issues with `Buffer`](https://github.com/isomorphic-git/isomorphic-git/issues/698) being in the library, you temporarily have to use the `umd.min.js` file in the browser (usually with a bundler like webpack). This comes complete with it's own TS definition/etc, just a bit more to type to import:

```javascript
import git, {ProgressCallback} from 'isomorphic-git/index.umd.min.js';
```

**Comment by carlyounger** [comment]
Thanks for taking the time @crutchcorn, and sorry for the late reply. I need to look at the issue you linked to, but in short, does it prevent a bundle being released (by this project)? I remember using Browserfy to bundle some stuff once, and was able to share the result as a simple package.

The current situation is clearly holding back adoption to some extent.

**Comment by crutchcorn** [comment]
@carlyounger you don't have to bundle yourself is what I'm saying. If you run `npm i isomorphic-git` and then look in your `node_modules`, you will find a pre-prepared `.umd.min.js` file. If you're using webpack (or any other bundler), you can simply import from there:

```
​import​ ​git​,​ ​{​ProgressCallback​}​ ​from​ ​'isomorphic-git/index.umd.min.js'​;
```

It's just a slight modification of the typical import

**Comment by carlyounger** [comment]
Ahhhh. Nice. Thank you, @crutchcorn. It makes much more sense now.

**Comment by crutchcorn** [comment]
@carlyounger if you want to avoid using NPM, you can also utilize something like an NPM CDN to download the file in-browser:

https://cdn.jsdelivr.net/npm/isomorphic-git@1.8.1/index.umd.min.js

**Comment by carlyounger** [comment]
That's perfect. Thank you, @crutchcorn.
