### ISSUE TITLE
TS2614: Module '"../node_modules/isomorphic-git"' has no exported member 'plugins'

### ISSUE THREAD

**Issue by SamuelMarks** [isomorphic-git/isomorphic-git#1308]
I've tried:
```ts
import {plugins, clone} from 'isomorphic-git'
```

Also tried:
```ts
import * as git from 'isomorphic-git'

git.plugins.set('fs', fs)
```

Running TypeScript `3.9.7` and isomorphic-git `1.8.0`.

EDIT: In the meantime I am providing `http` and `fs` as args to `clone`

**Comment by jcubic** [comment]
Plugins was removed in 1.x the new API is passing fs to every function. See [breaking changes in version 1.0](https://isomorphic-git.org/blog/2020/02/25/version-1-0-0#10-breaking-changes).
