### ISSUE TITLE
add command does not write posix path for symlink on Windows

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#1381]
Symlinks in a git repository must be expressed using a posix path (the path separator should be a forward slash) (e.g., `dir/file`). On Windows, the add command in isomorphic-git writes the path using backslash as the path separator. This happens because isomorphic-git uses fs.readlink to read the link target. On Windows, this function returns the path using backslash as the path separator (e.g., `dir\file`). isomorphic-git does not correct this, and ends up writing the non-posix path into the blob object.

This can be fixed by checking for the existence of backslashs in the return value of fs.readlink and correcting them to forward slashes.

Platform: Node.js
isomorphic-git version: 1.8.6

**Comment by mojavelinux** [comment]
I will submit a PR to fix this problem.

**Comment by mojavelinux** [comment]
This bug is back again starting in 1.14.0 as a result of the change for #1514. Specifically, the posixifyPathBuffer filter was removed that corrects the symlink target when resolved on a Windows machine.

**Comment by jcubic** [comment]
@mojavelinux I think your commit will not trigger a new version. I would just remove it and create a PR.

**Comment by mojavelinux** [comment]
I'm fine with waiting for another fix to come through. Though I thought https://github.com/isomorphic-git/isomorphic-git/commit/24d658c8aa2b34036235cab27da80e4cd6e4b9df would do it, but it seems like it didn't get merged with the correct commit message. Isn't there a way to trigger a release manually?

**Comment by jcubic** [comment]
I'm not sure what is triggering the build, maybe a merge of a PR.

**Comment by mojavelinux** [comment]
Yes, when certain PRs are merged. But only if the commit message follows the conventional commits format. I had made an error when I titled the PR.

**Comment by jcubic** [comment]
Yes, I know about the commit message, but I'm not sure if the build is listening only on PR merge. We can test if just the commit also triggers the build.

**Comment by mojavelinux** [comment]
Ah, great point. That sounds very plausible.
