### ISSUE TITLE
Safe to recommend `git.add({ dir, filename: '.' })` in FAQ entry for staging all untracked files?

### ISSUE THREAD

**Issue by mtlewis** [isomorphic-git/isomorphic-git#1402]
Hi folks! I'm looking into opportunities to optimize the performance of a system which uses isomorphic-git. It needs to stage every file in a new repository in order to create an initial commit containing all the files. It currently does this by using globby to find all the files, then adding each file in one by one, following [the recommended approach in the docs](https://isomorphic-git.org/docs/en/faq#how-to-add-all-untracked-files-with-gitadd). I've found that this approach takes minutes to complete when the number of files is large. Conversely, passing the top level directory of the repo using `git.add({ dir: '<repo root>', filename: '.' })` seems to work correctly for the use cases I've tested, and completes in a comparable time to running `git add .` in the terminal.

With this in mind, I'm wondering whether this is a safe change for us to make. If so, I'd be happy to send a PR updating the recommended approach for this use case in the FAQ!

**Comment by jcubic** [comment]
I personally don't like git add . it works differently depending on directory you're in and you will co it everything that is directory for the repo. I personally have a lot of case when I don't want to commit everything. Even if you want to commit everything you may want to split it into few commits. I don't think it's good idea to recommend git add . that may work not as user expect.

**Comment by mtlewis** [comment]
I see what you're saying, and I agree that it's usually not the right strategy to stage everything in a given directory for commit. My day-to-day git workflow is definitely a lot more selective than that 😁.

That said, this issue is specifically about the most efficient way of handling that exact use case, and the example in the docs is too; the title of [the entry](https://isomorphic-git.org/docs/en/faq#how-to-add-all-untracked-files-with-gitadd) is "How to add all untracked files with git.add?". I can see that maybe the issue is worded a bit too generally. I'll tweak it, thanks!

**Comment by jcubic** [comment]
Updating the FAQ is good idea.
