### ISSUE TITLE
Does not work with bared repos on IPFS gateway ?

### ISSUE THREAD

**Issue by anarkrypto** [isomorphic-git/isomorphic-git#1404]
The following tutorial explains how we can store git repos in IPFS:
https://docs.ipfs.io/how-to/host-git-style-repo/

But I can't clone the repo with isomorphic git, I get this error:

```
isomorphic-git:1 Uncaught (in promise) SmartHttpError: Remote did not reply using the "smart" HTTP protocol. Expected "001e# service=git-upload-pack" but received: fb4397bb3f8fcd8d9483f1ca554c94ecb0e3302f	refs/heads/main

    at isomorphic-git:8
    at Generator.throw (<anonymous>)
    at h (isomorphic-git:8)
    at s (isomorphic-git:8)
```

Code:
```js
<script src="https://unpkg.com/@isomorphic-git/lightning-fs"></script>
<script src="https://unpkg.com/isomorphic-git"></script>
<script type="module">
import http from 'https://unpkg.com/isomorphic-git@beta/http/web/index.js'
const fs = new LightningFS('fs')

const dir = '/test-clone'
git.clone({ fs, http, dir, noCheckout: true, url: 'https://ipfs.io/ipfs/bafybeifal46cb2647dduybxmbvcgh42xtka2vfdp7nkj63tet3h6kzzal4', corsProxy: 'https://cors.isomorphic-git.org' }).then(console.log)
git.listFiles({ fs, dir: '/test-clone' }).then(console.log)
</script>
```
- Bared Repo Link (Throught IPFS gateway): https://ipfs.io/ipfs/bafybeifal46cb2647dduybxmbvcgh42xtka2vfdp7nkj63tet3h6kzzal4
- Browser: Brave V1.26.77 Chromium: 91.0.4472.164 (Versão oficial) 64 bits
- OS: Ubuntu Ubuntu 20.04.2 LTS

**Comment by jcubic** [comment]
I don't think that there is support for IPFS. Isomorphic-git AFIK works only with smart HTTP protocol. You would need to implement support before you can use something else. Unfortunately I don't think I would be able to add this feature, but if you would like to implement the feature yourself. I'll be happy to integrate it with the library (after review).

**Comment by jcubic** [comment]
I know nothing about IPFS but if there is an error that it doesn't talk smart HTTP protocol it means that this type of repo is not supported.

**Comment by anarkrypto** [comment]
> I don't think that there is support for IPFS. Isomorphic-git AFIK works only with smart HTTP protocol. You would need to implement support before you can use something else. Unfortunately I don't think I would be able to add this feature, but if you would like to implement the feature yourself. I'll be happy to integrate it with the library (after review).

through the gateway the files are downloaded via http.

**Comment by anarkrypto** [comment]
> I know nothing about IPFS but if there is an error that it doesn't talk smart HTTP protocol it means that this type of repo is not supported.

Yes. I didn't understand why. But as you can see from the link I sent, the files can be downloaded via HTTP, so you can download them from any browser or even with Curl / wget.

**Comment by jcubic** [comment]
Yes, but I don't think that IPFS talk the same protocol. You can download the files maybe because it's dump HTTP protocol that is not supported #672
