### ISSUE TITLE
push to github authentization error: ECONNRESET

### ISSUE THREAD

**Issue by henryhu712** [isomorphic-git/isomorphic-git#1406]
I use node.js to make a push following [the api](https://isomorphic-git.org/docs/en/push)

```
let pushResult = await git.push({
  fs,
  http,
  dir: '/tutorial',
  remote: 'origin',
  ref: 'main',
  onAuth: () => ({ username: process.env.GITHUB_TOKEN }),
})
```

But after waiting for a while, I got the error:

    {"errno":-4077,"code":"ECONNRESET","syscall":"read","caller":"git.push"}

How to fix it?

**Comment by jcubic** [comment]
it should be:
```javascript
onAuth: () => ({ username: "name", password: process.env.GITHUB_TOKEN }),
```

**Comment by henryhu712** [comment]
I found the reason. I am in China and Github is blocked, so it failed.
