### ISSUE TITLE
statusMatrix() did not find modified files when working with package capacitor-fs

### ISSUE THREAD

**Issue by tachibana-shin** [isomorphic-git/isomorphic-git#1412]
I am using Browser and Webpack 5, [capacitor-fs](https://npmjs.org/package/capacitor-fs)

I cloned a repo and found the files that were changed but nothing came back

My code;

``` js
import FS from "capacitor-fs"
import git from "isomorphic-git"
import http from "isomorphic-git/http/web/index.js"

const fs = new FS({
  rootDir: "/",
  base64Alway: false
})

await git.clone({
  fs,
  http,
  dir: "/fcanvas",
  url: "https://github.com/shin-tachibana/fcanvas"
})

await fs.writeFile("/fcanvas/new file.txt", "hello new file.txt", "utf8")
await fs.writeFile("/fcanvas/README.md", "change content readme " + Math.random(), "utf8")

const matrix = await git.statusMatrix({
  fs,
  dir: "/fcanvas"
})

console.log(matrix) 
/*
  [
    ["new file.txt", 0, 2, 0]
  ]

  expectations:
  [
    ["new file.txt", 0, 2, 0],
    ["README.md", 2, 1, 2]
  ]
*/
```

My packages:

``` json
{
  "dependencies": {
    "@capacitor/core": "^3.1.2",
    "@capacitor/filesystem": "^1.0.2",
    "isomorphic-git": "^1.9.2",
    "buffer": "^6.0.3",
    "capacitor-fs": "^0.0.25",
    "core-js": "^3.6.5",
    "path-cross": "^0.0.3",
    "quasar": "^2.0.0",
    "vue-i18n": "^9.0.0-beta.0",
    "vue-timeago.js": "0.0.2",
    "vuex": "^4.0.1",
    "vuex-persistedstate": "^4.0.0"
  }
}
```

**Comment by jcubic** [comment]
I'm not sure I would need to check if capacitor-fs is actually compatible with the Node FS module. It may lack `fs.stat` (or similar) that returns proper values.

**Comment by Shin-Tachibana** [comment]
capacitor-fs still supports fs.stat, fs.lstat it returns a Stat object like the fs module. I don't see any error on console

**Comment by Shin-Tachibana** [comment]
capacitor-fs is identical to lightning-fs.

tôi nhận ra vấn đề của mình sẽ được giải quyết nếu xóa đoạn code này của hàm .statusMatrix

``` js
        const stageType = stage && (await stage.type());
//         if (stageType === 'commit') return null
//         if (stageType === 'tree' || stageType === 'special') return
```

All files return stageType = "tree" why we need to ignore it?

**Comment by jcubic** [comment]
Sorry I have no idea, why it works like this and what is the problem. I'm the maintainer of the project, but I'm not that familiar with the code base. I will need to investigate. Maybe see if with lightiningFS there is the same error. If so I think this would be a bug in iso-git but I don't want to remove those lines if I don't know why they are there.

Maybe @wmhilton will know why those lines are there and why they are needed. He's the author of the project.

**Comment by Shin-Tachibana** [comment]
@wmhilton please tell me why we need to skip it

**Comment by wmhilton** [comment]
> All files return stageType = "tree"

That should not be the case. That would mean that git thinks every file is a directory. What is the `mode` value for files you get with `fs.stat`?

**Comment by wmhilton** [comment]
> why we need to skip it

It is not skipping it. By returning from the `map` function at that point, we are saying "this is a directory, we don't need to return a value for this entry but we need to recurse into it".

---

> ```js
>   expectations:
>   [
>     ["new file.txt", 0, 2, 0],
>     ["README.md", 2, 1, 2]
>   ]
> ```

I don't think that output should be possible either. The table of all possible values is shown at the bottom of the [StatusMatrix](https://isomorphic-git.org/docs/en/statusMatrix) docs page, and 2 is not a possible value for the first column.

Based on the code, I'd expect the output to be:
```js
  [
    ["new file.txt", 0, 2, 0],
    ["README.md", 1, 2, 1]
  ]
```

**Comment by tachibana-shin** [comment]
when i run fs.stat it returns class Stat:

```
Stat: {
ctimeMs: 1629241254297
dev: 1
gid: 1
ino: 967
mode: 16822
mtimeMs: 1629241254297
size: 124
type: "file"
uid: 1
[[Prototype]]: Object
constructor: class Stat
isDirectory: ƒ isDirectory()
isFile: ƒ isFile()
isSymbolicLink: ƒ isSymbolicLink()
}
```

**Comment by tachibana-shin** [comment]
I see that

``` js
const workdirType = workdir && (await workdir.type());
if (workdirType === 'tree' || workdirType === 'special') return
```
removed directories from the returned results. what i get after this line is simply files with stageType="tree"

Perhaps this is an exception of capacitor-fs.stat as it has to make its own default values ​​that are not provided by the file system

**Comment by tachibana-shin** [comment]
Maybe this is an error due to capacitor-fs.stat because when i run with node:fs .statusMatrix() works properly

Can you add a filter Tree: boolean option to the .statusMatrix() function? I think that will help with cross-platform systems like cordova or electron because.

**Comment by wmhilton** [comment]
I recommend you just workaround this bug in capacitor-fs for now, and try to submit a fix to capacitor-fs if you can.

I tried very hard to make `isomorphic-git` work across multiple platforms, and in the 0.x days we might have added more workarounds but the philosophy of 1.x is that workarounds should live outside the main repo.

statusMatrix is fairly unique in that it doesn't use any internal APIs and no internal APIs use it. In fact, at this point it mostly serves as a starting point / example code for users. For your use case, the thing to do is copy-paste statusMatrix into your own code and modify it to your heart's delight! Actually, hang on and I'll do that for you real quick...

**Comment by wmhilton** [comment]
Whoops I lied. It uses GitIgnoreManager which isn't exposed yet. Hang on, I'll fix that. I really like this idea of making statusMatrix its own repo though, it's at https://github.com/isomorphic-git/statusMatrix

**Comment by wmhilton** [comment]
OK! Here, try copying https://github.com/isomorphic-git/statusMatrix/blob/main/statusMatrix.mjs into your project (upgrade to isomorphic-git version 1.10.0 for the `isIgnored` command) and then you can make whatever adjustments you need!

Honestly, `statusMatrix` has rather confusing output, so it wouldn't surprise me if most people prefer to start with that as a base and then modify it rather than use the version I wrote 🤷🏻.
