### ISSUE TITLE
401: Authentication fails with GitLab

### ISSUE THREAD

**Issue by anarkrypto** [isomorphic-git/isomorphic-git#1420]
First I tried to clone with the url "https://username:password@gitlab.com/user/repo.git", works in terminal, but did not work with isomorphic-git: Error 401 (Unauthorized)

So I tried using onAuth, but it also gave the same error, even changing the password to an access token.

``
                    git.clone({
                        fs,
                        http,
                        dir: this.dir,
                        url: "https://gitlab.com/user/repo.git",
                        onAuth: () => ({ username: 'myUsername', password: 'myPassword' }),
                    })
                        .then((res) => {
                            console.log(res)
                        })
                        .catch((err) => {
                            console.error(err)
                        })
``

**Comment by jcubic** [comment]
Do you use two-factor authentication? If so you need to generate the personal Auth token. This is the only way to authenticate when you have 2FA.

**Comment by jcubic** [comment]
Hmm, I've never used GitLab I need to investigate.

**Comment by anarkrypto** [comment]
> Do you use two-factor authentication? If so you need to generate the personal Auth token. This is the only way to authenticate when you have 2FA.

No, but I created an Access Token and used it, but also not works either.

**Comment by ppoulard** [comment]
This code works fine for me :
```typescript
    const onAuth: AuthCallback = url => ({
        username: 'oauth2', password: apiToken
    })
```

**Comment by anarkrypto** [comment]
> ```ts
> AuthCallback
> ```

What is AuthCallback ? How do I set this ?

**Comment by anarkrypto** [comment]
@ppoulard, thanks! Fixed. 

Also, it is important to use https://gitlab.com/user/repo.git instead https://gitlab.com/user/repo
The second one not works.
