### ISSUE TITLE
Peeled oid is used instead of annotated tag oid when writing refs/tags

### ISSUE THREAD

**Issue by SamVerschueren** [isomorphic-git/isomorphic-git#1441]
Hi 👋 

First of all, `isomorphic-git` is an awesome project! Really great work you do over here!

I'm trying to implement `git for-each-ref` and ran into an issue with cloning and annotated tags. When a repository is cloned with an annotated tag, the resolved object id is used to write the tag to disk instead of the object id of the tag itself.

I used [chalk](https://github.com/chalk/chalk) to test my implementation, so using that repo as an example as well.

When cloning chalk with the real git cli, and running `for-each-ref` in the repository, you can see that the object is a `tag` with object id `11ddcee`.

```
$ git for-each-ref 'refs/tags/v0.1.0'
11ddceeb4ceff07c2e7eec2b017cf88e4878d13b tag    refs/tags/v0.1.0
```

When cloning chalk with `isomorphic-git`, and running `for-each-ref`, you can see that it points to `466710d` as if it was a lightweight tag.

```
$ git for-each-ref 'refs/tags/v0.1.0'
466710d17eaa8d5a8728e8173492f0825b29d2d6 commit refs/tags/v0.1.0
```

This can be verified by running

```
$ git ls-remote https://github.com/chalk/chalk 'refs/tags/v0.1.0*'
11ddceeb4ceff07c2e7eec2b017cf88e4878d13b	refs/tags/v0.1.0
466710d17eaa8d5a8728e8173492f0825b29d2d6	refs/tags/v0.1.0^{}
```

Then I came across the [following issue](https://github.com/isomorphic-git/isomorphic-git/issues/15) where it looks like this currently just doesn't work.

But I was curious and thus dived into the codebase and found [this line](https://github.com/isomorphic-git/isomorphic-git/blob/main/src/managers/GitRefManager.js#L73-L74). So basically the code prefers the `^{}` reference instead of the regular one. By changing that line to the following works.

```ts
const oid = refs.get(serverRef);
```

After doing that and cloning the repository with `isomorphic-git`, the output for `for-each-ref` is now correct.

```
$ git for-each-ref 'refs/tags/v0.1.0'
11ddceeb4ceff07c2e7eec2b017cf88e4878d13b tag    refs/tags/v0.1.0
```

Can we change that line by not taking `^{}` into account? Or would that break other use cases? Because that line is only for tags, I don't think it should affect anything else and actually make it more correct.

I can send a PR if you want. Would be awesome to get this fixed.

Kind regards 🙏 

### Additional information

- Environment: Node.js & Browser
- Webpack
- Version: 1.10.0

**Comment by jcubic** [comment]
It's hard to say, I would just clone the repo, modify the code and run unit tests. But there is an issue in running tests locally. There is open PR #1436 to fix unit test, it seems that they work locally again but build is failing because ESLint (only on the sever)
