### ISSUE TITLE
Buffer not defined with Webpack 5

### ISSUE THREAD

**Issue by bojanvidanovic** [isomorphic-git/isomorphic-git#1446]
Incompatibility with Webpack 5, whereas it will throw an error "Buffer not defined".

**Comment by jcubic** [comment]
Can you explain more? Maybe you can create reproducible example for the issue you're reporting?

Note that there are no active maintainer that can write code right now, the original author of the library is not actively working on the project (recently he added one PR). So if you will not willing to fix the issue yourself, it will probably be not fixed for a while, especially that you don't say what is the exact issue. Unless someone else that needed it will fix the issue for you.

**Comment by Sound1ab** [comment]
I ran into the same after updating CRA. The problem is that Webpack 5 no longer polyfills node packages. The packages need to be installed manually and added to the `resolve.fallback` object. [More info in the webpack docs](https://webpack.js.org/configuration/resolve/#resolvefallback).

```JSON5
module.exports = {
  //...
  resolve: {
    fallback: {
      buffer: require.resolve('buffer'),
      process: require.resolve('process/browser'),
      stream: require.resolve('stream-browserify'),
    },
  },
};
```

You will also need to add these plugins:

```javascript
const webpack = require('webpack');

module.exports = {
  // ...
  plugins: [
      new webpack.ProvidePlugin({
          Buffer: ['buffer', 'Buffer'],
      }),
      new webpack.ProvidePlugin({
          process: 'process/browser',
      }),
  ],
}
```

**Comment by seanpoulter** [comment]
It seems like we can close this issue. Did that work for you @bojanvidanovic?

**Comment by jcubic** [comment]
Maybe it's worth adding this to FAQ before closing.

**Comment by bojanvidanovic** [comment]
> It seems like we can close this issue. Did that work for you @bojanvidanovic?

Oh yes, that solves the issue. But as @jcubic mentioned, it should be documented.
