### ISSUE TITLE
Add support for --no-track with git.checkout

### ISSUE THREAD

**Issue by KwintenP** [isomorphic-git/isomorphic-git#1459]
👋 

I'm trying to implement `git checkout --no-track -b foobar`. After digging in the code, I *think* it's not possible to do today. It seems that here: https://github.com/isomorphic-git/isomorphic-git/blob/main/src/commands/checkout.js#L59-L78

It will always create a new ref `refs/heads/foobar` but it will always set the remote tracking branch info as well. I'm trying to avoid this as it what `--no-track` should do.

Is there another way around this?
If not, happy to send a PR your way.

🙏

**Comment by jcubic** [comment]
I have no idea, I'm a current maintainer, but I don't do much coding myself and I'm not much familiar with the codebase. But I suspect that if you didn't find the code for this, then is not present. But if you want to implement this feature go ahead. Remember to add documentation (if it's a new feature), and add unit tests if possible.

**Comment by mojavelinux** [comment]
I agree the the current behavior is not consistent with canonical git. By default, canonical git does not set up a remote tracking branch. You can emulate this behavior in isomorphic-git by following the checkout with the following three commands:

```js
await git.setConfig({ ...repo, path: 'branch.name-of-branch.remote' })
await git.setConfig({ ...repo, path: 'branch.name-of-branch.merge' })
await git.setConfig({ ...repo, path: 'branch.name-of-branch' })
```

While testing this, I also noticed that isomorphic-git creates the wrong config if the branch name contains dots (e.g., v3.0.x). It only uses the part of the branch name up to the first dot when defining the config category. So you end up with something like:

```
[branch "v3"]
    remote = origin
[branch "v3"]
    merge = refs/heads/v3.0.x
```

We should look into why that is happening.

**Comment by mojavelinux** [comment]
To be clear, I support adding a `noTrack` option to the `checkout` command.

**Comment by KwintenP** [comment]
Awesome, I'll create the PR for that today.
