### ISSUE TITLE
Make work in Next.js without hacks.

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#146]

**Comment by wmhilton** [comment]
Currently testing in a dummy project using `next` v5.1.0 and `react` v16.3.2. Turns out that the `config` function has a Rest Properties operator, so I need to get that out as well.

**Comment by wmhilton** [comment]
For some reason Firefox is giving me issues in CI tests and I haven't been able to merge #148 yet. I don't think it's got anything to do with this change though - it's been happening in all the PRs.

**Comment by wmhilton** [comment]
Alright! @juancampa try isomorphic-git@0.11.3. I was able to use it with `next` 5.1.0 without any problems. I just tested git clone though. Setting up browserfs is still a bit of a pain. I'm actually working on simplifying the initial setup so you can simply pass in the BrowserFS config and it will return both "git" and a promisified "fs" that run in a Web Worker thread in the background (so that cloning doesn't cause the main page to freeze up).

**Comment by juancampa** [comment]
Hey @wmhilton, it works beautifully! Thanks for the amazing work

**Comment by wmhilton** [comment]
Just make something cool with isomorphic-git, is all the reward I need. :)
