### ISSUE TITLE
Native nodejs zlib

### ISSUE THREAD

**Issue by willstott101** [isomorphic-git/isomorphic-git#1478]
I've noticed #740 in a short dig thinking about how to improve the file-streaming situation mentioned in #1344

Now that `DecompressionStream` exists it seems to me like `pako` should be loaded by a code split only when needed. I'm happy to have a bash at that - partly because I think it'd be cool if we used zlib on node - and having lazy importing in that file would make that much more doable.

However I'd be surprised if there weren't some bundlers that'd choke on trying to import `node:zlib` - even when imported lazily and guarded. Is there any prior examples anyone can think of for code that's nodejs only in a library?

**Comment by willstott101** [comment]
Aha! Never-mind I've just realised nodejs 17+ implements `DecompressionStream` - so if an app adds that to the global objects at startup isomorphic ought to use it! Neat.

**Comment by jcubic** [comment]
Do you need to do something here? If not please close the issue.

**Comment by willstott101** [comment]
I was planning on testing my suggestion above and providing an example for anyone coming across this issue. But no one else needs to do anything, so I'll close it first.
