### ISSUE TITLE
Pass through agent to simple-get in the http plugin for Node.js

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#1491]
isomorphic-git does not provide support for HTTP proxies by default. However, all HTTP calls in isomorphic-git are routed through the http plugin. If the http plugin were to pass through the agent parameter to the underlying http client library (simple-get), then it would be easy to add HTTP proxy support using a custom agent. (There are plenty of such agents available in npm, including hpagent). However, since the http plugin does not pass through this parameter, it's necessary to completely replace the http plugin with a custom implementation.

Here's how it could work:

```js
'use strict'

const { request: delegate } = require('isomorphic-git/http/node')
const { HttpProxyAgent, HttpsProxyAgent } = require('hpagent')
  
async function request ({ url, method, headers, body }) {
  const proxy = url.startsWith('https:')
    ? { Agent: HttpsProxyAgent, url: process.env.https_proxy } 
    : { Agent: HttpProxyAgent, url: process.env.http_proxy }
  const agent = proxy.url ? new proxy.Agent({ proxy: proxy.url }) : undefined
  return delegate({ url, method, headers, agent, body })
}

module.exports = { request }
```

Here's the change that is needed to support this:

```diff
diff --git src/http/node/index.js src/http/node/index.js
index c4d2ff13..4d7980ac 100644
--- src/http/node/index.js
+++ src/http/node/index.js
@@ -16,6 +16,7 @@ export async function request({
   url,
   method = 'GET',
   headers = {},
+  agent,
   body,
 }) {
   // If we can, we should send it as a single buffer so it sets a Content-Length header.
@@ -30,6 +31,7 @@ export async function request({
         url,
         method,
         headers,
+        agent,
         body,
       },
       (err, res) => {
```

**Comment by mojavelinux** [comment]
I'm happy to submit a PR if this proposal is approved.

**Comment by jcubic** [comment]
Sure, I think that it will be a good idea to make the library used in more use cases.

**Comment by mojavelinux** [comment]
See #1493

**Comment by mojavelinux** [comment]
Thanks @jcubic!

**Comment by jahnli** [comment]
@mojavelinux    Check whether the proxy parameter is available and whether the corresponding introduction or demo can be added on the official website

**Comment by mojavelinux** [comment]
Yes it's available. But the website is failing to update during a release and we haven't figured out why. So no amount of adding documentation is going to help until we solve that problem. See discussion in #1496.

**Comment by jahnli** [comment]
@mojavelinux   async function request({ onProgress, url, method = "GET", headers = {}, agent, body }) {
  // If we can, we should send it as a single buffer so it sets a Content-Length header.
  if (body && Array.isArray(body)) {
    body = Buffer.from(await collect(body));
  } else if (body) {
    body = asyncIteratorToStream(body);
  }
  return new Promise((resolve, reject) => {
    get(
      {
        url,
        method,
        headers,
        agent: tunnel.httpsOverHttp({
          proxy: {
            host: "127.0.0.1",
            port: 7890
          }
        }),
        body
      },
      (err, res) => {
        if (err) return reject(err);
        const iter = fromNodeStream(res);
        resolve({
          url: res.url,
          method: res.method,
          statusCode: res.statusCode,
          statusMessage: res.statusMessage,
          body: iter,
          headers: res.headers
        });
      }
    );
  });
}
module.exports = {
  request
};

I don't know if it fits

I tried to change the node/index HTTP client to a custom HTTP client, and it seems to work

**Comment by mojavelinux** [comment]
Please use the code I provided in the description. If you need more help, please ask in [gitter](https://gitter.im/isomorphic-git/Lobby). A closed issue is not the correct place to ask for support.
