### ISSUE TITLE
Add API for `update-index --cacheinfo`

### ISSUE THREAD

**Issue by SamVerschueren** [isomorphic-git/isomorphic-git#1494]
I'm looking for an API that could cover `git update-index --cacheinfo` functionality. Currently `isomorphic-git` is able to write objects to the object database with `writeObject()`, but after that it's not possible to do something with that data.

The `git update-index --cacheinfo` method allows to update the index with data that's already in the object database, but does not exist in the working directory. This is possible with `git hash-object -w --stdin` where the data that's coming from stdin gets hashed and written to the object database. The hash is returned, and can then be used to update the index with `git update-index --add --cacheinfo`.

I'm not sure how fine-grained an API should be. Should we create one API that covers a lot of the `updateIndex` functionality, or focus on `git update-index --cacheinfo` specifically (which should solve my use case).

Having a `updateIndex()` method that covers everything from `git update-index` might be a bit too much. So something specific for this use case might be better?

```ts
addCacheObject({
	// usual isomorphic-git options like fs, gitdir, dir, cache
	mode: 100644,
	object: 'b6fc4c620b67d95f953a5c1c1230aaab5db5a1b0',
	filepath: 'readme.md'
});
```

**Comment by SamVerschueren** [comment]
@mojavelinux @jcubic Any feedback on this proposal? Could create a PR for this right now. Or do you want to wait until we know which direction we want to go to with #1495? I think it still does make sense to expose a function like this.

**Comment by mojavelinux** [comment]
I'm unfamiliar with this functionality in git, so I'm not really in a position to comment on the proposal. Could you explain a use case when this is needed / how it is used?

**Comment by jcubic** [comment]
@SamVerschueren I'm not familiar with this API either. But if this is related to the index, I've already promised in #1495 GitIndex as a way to interact with the index. I would see this as:

```javascript
GitIndex.addCacheObject({
	// usual isomorphic-git options like fs, gitdir, dir, cache
	mode: 100644,
	object: 'b6fc4c620b67d95f953a5c1c1230aaab5db5a1b0',
	filepath: 'readme.md'
});
```

Unless this is not about the index. I don't see a place for this function in high-level functions that are current API.

And if git Cache is a separated entity maybe:
```javascript
import { Cache } from '@isomorphic-git/core'

Cache.add({
	// usual isomorphic-git options like fs, gitdir, dir, cache
	mode: 100644,
	object: 'b6fc4c620b67d95f953a5c1c1230aaab5db5a1b0',
	filepath: 'readme.md'
});
```

**Comment by SamVerschueren** [comment]
Yes exactly, I think that makes sense. It's about the index, not the cache. The object is already in the object database (cache I assume?) because of `writeObject()`.

The use case for this is when tools allow staging partial changes. For instance, in VSCode you can select only certain lines and then right-click + "Stage Selected Ranges".

![image](https://user-images.githubusercontent.com/1913805/154965317-e4556be8-559f-4a0b-99f6-c0f8955846a2.png)

Under the hood what this does is,
1. `git hash-object -w --stdin` which will receive only the lines that you want to stage over `stdin` and writes that object to the object database. This is somewhat a virtual entry, because the file itself does not exist on disk because it's only partial.
2. `git update-index --add --cacheinfo 100644 b6fc4c620b67d95f953a5c1c1230aaab5db5a1b0 readme.md` which will then add the object that was created and written by `hash-object` to the index with the provided mode and filepath.

And this is also the use case where I need it for. So feel free to close this issue in favour of the discussion going on in #1495.

**Comment by mojavelinux** [comment]
> Having a updateIndex() method that covers everything from git update-index might be a bit too much. 

In looking at this issue again, and analyzing the use case you shared, I actually think adding an `updateIndex` is the right way forward. The isomorphic-git commands roughly follow the porcelain git commands, so `updateIndex` fits right in there.

I don't think that adding the dedicated command `addCacheObject`, which is not found in git, is the right way forward. It's too specific. The `updateIndex` command may not be complete at first, but we should at least attempt to make it functional, then enhance it as we go. The `add` command, for example, doesn't do everything that `git add` does, but it's enough to be functional.

**Comment by jcubic** [comment]
@mojavelinux what about if there will be a requirement for more stuff with index? Like git plumbing methods. I'm not an expert in git but I assume that there are more things you can do with index than just update. Or am I wrong?

PS: I've had this wonderful article about the internals of git, but I was not able to find time to read it. The article was explaining how to make common tasks with low-level git commands.

**Comment by mojavelinux** [comment]
...then we add methods for those others things, crossing that bridge when we get to it. That doesn't mean the functions can't share code underneath (as they currently do)...but each porcelain operation the user needs should be available through well-designed and well-factored functions. isomorphic-git is not an object-oriented library.

**Comment by jcubic** [comment]
I've found that awesome article, warning it's big [A Hacker's Guide to Git](https://wildlyinaccurate.com/a-hackers-guide-to-git/). I've saved it in my notes since it's hard to find git in browser history. We can include that article in the contribution guide. It may be easier for people to contribute if they have a guide on how git works.

**Comment by SamVerschueren** [comment]
Yes, adding an `addCacheObject` method doesn't really make sense looking at how isomorphic-git is designed. So having an `updateIndex` method makes sense looking at the other commands that exist today.

If you both agree, I can create a PR for `updateIndex` and we can see how it turns out. If not, we continue the discussion :).

**Comment by mojavelinux** [comment]
I'm in favor of moving forward with the `updateIndex` proposal.

**Comment by jcubic** [comment]
I'm fine with this.

**Comment by jcubic** [comment]
@SamVerschueren there is also a shorter intro in this video: [Inside the Hidden Git Folder - Computerphile](https://www.youtube.com/watch?v=bSA91XTzeuA) I probably also include that in contribution. Videos are easier to consume.
