### ISSUE TITLE
Push broken on WebContainers (unpacker error)

### ISSUE THREAD

**Issue by rayfoss** [isomorphic-git/isomorphic-git#1523]
The following shell command run fine in Node 16/14 on an Ubuntu machine, but fail on [WebContainers](https://github.com/stackblitz/webcontainer-core). Pushing without making a commit works as expected, but pushing any commit does not.

```
/tmp/test-dir
> npx isomorphic-git push --corsProxy='https://cors-proxy.myproxy.app' --url='https://JohnDoe:glpat-123@gitlab.com/my-repo.git'
success Install finished in 2.27s

One or more branches were not updated: 
  - refs/heads/main: unpacker error
GitPushError: One or more branches were not updated: 
  - refs/heads/main: unpacker error
    at _push (/home/.turbo/npx/LOzMwT/node_modules/isomorphic-git/index.cjs:11731:11)
    at async Object.push (/home/.turbo/npx/LOzMwT/node_modules/isomorphic-git/index.cjs:11809:12)
    at async eval (/home/.turbo/npx/LOzMwT/node_modules/isomorphic-git/cli.cjs:14:20) {
  caller: 'git.push',
  code: 'GitPushError',
  data: {
    prettyDetails: '\n  - refs/heads/main: unpacker error',
    result: {
      ok: false,
      error: 'unpack-objects abnormal exit',
      refs: { 'refs/heads/main': { ok: false, error: 'unpacker error' } },
	  headers: {
	      'cache-control': 'no-cache',
	      'content-type': 'application/x-git-receive-pack-result',
	      date: 'Mon, 28 Mar 2022 16:14:39 GMT',
	      server: 'nginx/1.21.0',
	      'transfer-encoding': 'chunked'
	  }
    }
  }
}
```

Everything else seems to work fine. The same error occurs when running from a script instead of the CLI.

The issue seems to be some incompatibility with WebContainer FS, HTTP, or jsh.

## Versions

Node: WebContainer Node 14
isomorphic-git: 1.17.0
Chrome: 98

**Comment by jcubic** [comment]
I think that you should report this to StackBlitz. This is the platform that doesn't work properly. Unless the same can be reproduced in native NodeJS, nothing we can do about this.

**Comment by rayfoss** [comment]
WebContainers are open source and support debugger statements. It's possible the issue affects Deno, Module node projects, lightweight Linux distros and other environments like php-v8 and RunKit. 

https://github.com/isomorphic-git/isomorphic-git/pull/139
@wmhilton Ideas on what may be the root cause?

We could rule out the file system module with some code that doesnt use fs, but memory instead. WebContainers are out of beta and have been extremely solid in my experience,  aside from  dependencies that assume binary executeable support.

**Comment by jcubic** [comment]
If you want to test in memory with GIT I've recently added a feature to LightingFS that allows changing the inner DB object, which is way better than changing the backend is like writing a whole new FS library.

But I didn't test it yet with isomorphic-git:

Here is my testing code:

```javascript
class MemoryBackend {
  constructor(data) {
    this._store = new Map();
  }
  saveSuperblock(superblock) {
    this._store.set('!root', superblock);
  }
  loadSuperblock() {
    return this._store.get('!root');
  }
  readFile(inode) {
    return this._store.get(inode);
  }
  writeFile(inode, data) {
    return this._store.set(inode, data);
  }
  unlink(inode) {
    return this._store.delete(inode);
  }
}
const db = new MemoryBackend();
const fs = new LightningFS("fs", { db });
```

I've created this so I can save and load filesystem images. I will probably write an article about this after I create the demo I'm working on right now.

@wmhilton is not active anymore, I'm a maintainer right now, but I'm not super familiar with the code. So the only way to make this fixed is you figure out on your own.

**Comment by rayfoss** [comment]
Turned out to be an issue when POST ing binary payloads through the WebContainer http module. Will be fixed in a coming update
