### ISSUE TITLE
checkout commit fails

### ISSUE THREAD

**Issue by isysd** [isomorphic-git/isomorphic-git#155]
Passing a commit hash instead of a branch to `checkout` results in an unexpected error. At least it is inconsistent with the standard git checkout command, though not the documentation for isomorphic-git.

Assume `83fa48b946132214648f0283a1e81fd4049fbb42` is a valid commit in the repository at `/keys/pgp`.

```
git.checkout({
   fs: fs, 
   dir: '/keys/pgp',
   ref: '83fa48b946132214648f0283a1e81fd4049fbb42'
})
```

Throws error:

```
 Error: invalid type passed to GitIndex constructor
    at new GitIndex (node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:845:13)
    at Function.from (node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:849:12)
    at node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:1827:26
    at process._tickCallback (internal/process/next_tick.js:178:7)
```

Expected behavior would be to set HEAD to 83fa48b946132214648f0283a1e81fd4049fbb42.

Engine: nodeJS v10.0.0

Version: 0.11.2

**Comment by wmhilton** [comment]
Hmmmmmmm I think this might be a Node 10.x issue rather than an actual problem with `checkout`. They made a major change to the Buffer constructor (see https://nodesource.com/blog/understanding-the-buffer-deprecation-in-node-js-10).

But I'll add a test case to `test-checkout` to make sure that passing a git sha works.

Does it happen in 9.x?

**Comment by isysd** [comment]
Agreed that this is a Buffer issue and not a specific problem with checkout.

Yes it does happen in 9.x, and the patch also fixes it for 9.x. Added node 10 to travis, regardless.

**Comment by isysd** [comment]
Yes, it did! Thank you for researching a proper solution. :+1:

**Comment by wmhilton** [comment]
Thank you for reporting this bug and helping me find the best fix!
