### ISSUE TITLE
Invalid checksum in GitIndex buffer during commit in remix

### ISSUE THREAD

**Issue by moonman369** [isomorphic-git/isomorphic-git#1565]
Please be sure to mention:
- whether you are using Node or the Browser
- how you are using it (if you are using a bundler what bundler; if you are using a `<script>` tag what CDN URL)

I am using `Remix - Ethereum IDE` at `https://remix.ethereum.org/#optimize=false&runs=200&evmVersion=null&version=soljson-v0.8.13+commit.abaa5c0e.js`
I am getting Error Message:
`Invalid checksum in GitIndex buffer: expected efbfbdefbfbd7d676153276f2c4eefbfbdefbfbd but saw 9ff1a97ef395f357b48243dfa81397458cd4131a`

**Comment by jcubic** [comment]
Please explain, is your app Remix - Ethereum IDE that uses Isomorphic-git or the code that is inside?

I don't see any git error.

**Comment by moonman369** [comment]
> Please explain, is your app Remix - Ethereum IDE that uses Isomorphic-git or the code that is inside?
> 
> I don't see any git error.


It is the app that uses isomorphic-git, sir.

Error: `Invalid checksum in GitIndex buffer`

I am getting this error when I am trying to commit changes.

**Comment by jcubic** [comment]
Is "Remix - Ethereum IDE" your app? Can you show the source code of this app? If not then maybe you should report to the Remix developers.
