### ISSUE TITLE
503 Response by Isomorphic Proxy

### ISSUE THREAD

**Issue by tuphan-dn** [isomorphic-git/isomorphic-git#1566]
Please be sure to mention:
- whether you are using Node or the Browser: **Browser**
- how you are using it (if you are using a bundler what bundler; if you are using a `<script>` tag what CDN URL): **npm packages**

I met this kind of this error in the last 2 days for `clone` a repo. I think there are problems with the current proxy. Could the team help to check or point out what I'm missing?

```
Access to fetch at 'https://cors.isomorphic-git.org/github.com/DescartesNetwork/sen-academy-warehouse/info/refs?service=git-upload-pack' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
VM10:1          GET https://cors.isomorphic-git.org/github.com/DescartesNetwork/sen-academy-warehouse/info/refs?service=git-upload-pack net::ERR_FAILED 503
```

**Comment by jcubic** [comment]
cors.isomorphic-git.org proxy doesn't work anymore and we can't fix it. I also can't contact with original author to give us access to the place where this proxy is hosted.

You will need to host the CORS proxy yourself.
