### ISSUE TITLE
ENOENT: /path/.../.git/packed-refs

### ISSUE THREAD

**Issue by eropple** [isomorphic-git/isomorphic-git#1603]
Hey there! Running into a really odd behavior that I don't understand. I'm attempting to clone a GitHub repository into LightningFS, which works fine. I can see the repository and I can navigate around it via LightningFS's API and I can see the files in the FS's working directory. I can also see a populated `.git` directory, with `refs` et al as expected. However, when I attempt to do any operation that involves talking to a ref (git.checkout, for example), I receive the above error:

`ENOENT: /path/.../.git/packed-refs`

Sure enough, there's no `/path/.../.git/packed-refs` to be found! I've looked through docs and both open and closed issues and can't find a duplicate of this, so I'm certainly willing to consider that I'm doing something silly, but I'm unclear how one would go about fixing this. There's no `git pack-refs` equivalent that I can find, and in tracing the code I do see where it reads `/.git/packed-refs`, and it seems like the library assumes it's going to succeed. Clearly...it's not, here!

This happens with both large and small repos, and happens for me against `github.com/isomorphic-git/isomorphic-git` just the same as a one-commit repo.

Any pointers to how to resolve or to at least get further debug information would be greatly appreciated.

## Environment

- Browser (Firefox current, Chrome current); NextJS/React, but I don't think this really matters
- `isomorphic-git@latest`
- `@isomorphic-git/lightning-fs@latest`
- using both `cors.isomorphic-git.org` and my own CORS proxy, which both exhibit identical behavior

**Comment by eropple** [comment]
Huh - and as if by magic, I rubber-duck a solution!

> NextJS/React, but I don't think this really matters

This right here is hubris. I was getting a double refresh early in my instantiation routine and it was causing my well-intentioned cleanup code to invalidate and recreate the IndexedDB underneath in a really weird way.

PEBKAC, apologies, closing!

**Comment by jcubic** [comment]
Great that you've found the issue and solved the problem.
