### ISSUE TITLE
`git.clone()` docs example is broken

### ISSUE THREAD

**Issue by colebemis** [isomorphic-git/isomorphic-git#1612]
## Problem

The interactive `git.clone()` example on https://isomorphic-git.org/docs/en/clone throws a `Failed to fetch` error when you run it:

![CleanShot 2022-07-20 at 08 46 26](https://user-images.githubusercontent.com/4608155/180026243-7195b745-a6c2-4588-9a54-701eacac441e.png)

I'm using Chrome Version 103.0.5060.114 (Official Build) (x86_64)

**Comment by InSuperposition** [comment]
It appears to be a CORS issue with the proxy and the error message is handled:

<img width="1428" alt="Screen Shot 2022-07-23 at 6 33 50 PM" src="https://user-images.githubusercontent.com/433871/180628603-f11e1aea-af9e-481a-919c-e294c74c38fb.png">

**Comment by stephyswe** [comment]
its the same with all examples, is anyone who knows more of this gonna comment? Otherwise the guide at the moment leads to errors and not many who isn't involved in the project will understand why. and how to fix the error

**Comment by jcubic** [comment]
@stephyswe Unfortunately we don't control the CORS application. I've contacted the cloud provider that host it and they send a single not informative reply after I've asked the question on chat and just give me the screenshot of the conversation like it was an end. I think that I will need to contact them each time again when I have more comments.

**Comment by stephyswe** [comment]
> @stephyswe Unfortunately we don't control the CORS application. I've contacted the cloud provider that host it and they send a single not informative reply after I've asked the question on chat and just give me the screenshot of the conversation like it was an end. I think that I will need to contact them each time again when I have more comments.

...
Sure,
but in the meanwhile how about update the guide with info how to create a working example without the provider?

**Comment by jcubic** [comment]
CORS is restored. I hope it will not break anytime soon.

**Comment by jcubic** [comment]
I'm closing this issue. If the issue appears again you can comment I will reopen the issue.

**Comment by stephyswe** [comment]
> I'm closing this issue. If the issue appears again you can comment I will reopen the issue.

Hi, Um Its great it working for you guys in the doc but is there a example how to make it work for a personal project? I would love to learn!

**Comment by jcubic** [comment]
If you use lightingFS like this, then it uses [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) you can't easily access HDD from the browser, there is a new API [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API), but I don't have experience with that (I think that I was testing it one time long ago).
