### ISSUE TITLE
[FR] addMatrix

### ISSUE THREAD

**Issue by MarsOrBust24** [isomorphic-git/isomorphic-git#1624]
I'm finding myself writing an `addMatrix` function, basically what `statusMatrix` is to `status`, a recursive version of `add`. `statusMatix` is a HUGE help... but it's still not trivial with the dozen or so edge cases. This is obviously a kin to `git add --all`.

Basically one method that makes everything match the work tree directory and returns a statusMatrix. The stage statuses for all files would then be identical to workdir or absent if not in workdir.

While the existence of statusMatrix should be enough to justify this alone... I'm finding my self using this in WebContainer/jsh/CF Workers backed environments being used as WYSIWYG editors for content, StoryBlock/Strapi style.

## Update

Here's what I have so far... A dirty stage could cause problems, so an option to force/clean the stage is probably needed.

There is one big hurdle... commit deletes all files that were not added to the stage, by default! [**is this intentional**](https://github.com/isomorphic-git/isomorphic-git/issues/1262#issuecomment-1217432706)? This only happens when the initial clone was for gitDir only, leaving the working tree as is with noCheckout. Come to think of it, clone with noCheckout sounds like just a broken fetch call.

addMatrix should probably return a matrix... with all files and yet another set of integer values, always in relation to head. Reset index on all should probably be mandatory when using `git add --all`. Git normally wants you to stash uncommitted changes in the stage.

`AddMatrix = Array<Array< FilePath: string, operation: 'created' | 'removed' | 'modified' >>`

Though ideally it should return the initial statusMatrix, the operation performed and the resulting status matrix, of each file, as a matrix... that would be messy to say the least as one long 2D matrix. We could instead just return the result statusMatrix, and infer removed and (created/modified) based on the absent/identical-to-head/identical-to-workdir status.

It may not be worth it to go this route just for consistency, rather than adding a recursive option to add, or an addAll function.

```javascript

const makeMapReversible = (map) => map.forEach((v, k, m) => m.set(v, k))
const HEAD_STATUS = new Map([
  ['absent', 0],
  ['present', 1]
])
const WORKDIR_STATUS = new Map([
  ['absent', 0],
  ['identical_to_head', 1],
  ['different_from_head', 2]
])
const STAGE_STATUS = new Map([
  ['absent', 0],
  ['identical_to_head', 1],
  ['identical_to_workdir', 2],
  ['different_from_workdir', 3]
])
const STATUS_MAPS = [HEAD_STATUS, WORKDIR_STATUS, STAGE_STATUS]
STATUS_MAPS.forEach(makeMapReversible)
const gitStatus = async () => {
  const matrix = await statusMatrix({
    ...gitConfig,
    filter: (f) => f !== SECRETS_FILE_PATH
  })
  return matrix
}

const gitAddMatrix = async (matrix) => {
  const result = {
    unchanged: 0,
    added: [],
    removed: [],
    other: []
  }
  for (const status of matrix) {
    const [filePath, headStatus, workdirStatus, stageStatus] = status
    if (workdirStatus === WORKDIR_STATUS.get('different_from_head')) {
      result.added.push(filePath)
      add({
        ...gitConfig,
        filepath: filePath
      })
    } else if (
      headStatus === HEAD_STATUS.get('present') &&
      workdirStatus === WORKDIR_STATUS.get('identical_to_head')
    ) {
      result.unchanged++
      add({
        // isomorphic-git's commit function will delete anything not in stage
        ...gitConfig,
        filepath: filePath
      })
    } else if (
      headStatus === HEAD_STATUS.get('present') &&
      workdirStatus === WORKDIR_STATUS.get('absent')
    ) {
      // remove not neccessary due to isomorphic-git quirk
      result.removed.push(filePath)
    } else {
      result.other.push(status)
    }
  }

  if (result.other.length > 0) {
    const prettyOther = result.other.map(
      ([filePath, headStatus, workdirStatus, stageStatus]) => {
        console.log({
          filePath,
          headStatus: HEAD_STATUS.get(headStatus),
          workdirStatus: WORKDIR_STATUS.get(workdirStatus),
          stageStatus: STAGE_STATUS.get(stageStatus)
        })
      }
    )
    console.warn(
      `${NS}: addMatrix: stage is in an unexpected state. Please stash your changes to the stage.`,
      JSON.stringify(prettyOther, null, 2)
    )
  }

  return result
}
```

## References:

- [git reset head / git stash implementation](https://github.com/isomorphic-git/isomorphic-git/issues/1262#issuecomment-723960562)

**Comment by jcubic** [comment]
And what you expect, by posting your code. Because I don't understand. This is not a question and not a feature request. Then what is it? Do you expect something?

**Comment by MarsOrBust24** [comment]
I'll keep working on it and make a PR if I have something good.

https://gitlab.com/vblip/g4c/-/blob/91be834f40afd80a439cea62fbc3313f22497b71/src/main.mjs#L192
