### ISSUE TITLE
See if BrowserStack is more reliable than SauceLabs

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#163]
![browserstack-logo](https://user-images.githubusercontent.com/587740/39730004-f8cb2f58-522c-11e8-9ada-d47872bad9ef.png)

**Comment by wmhilton** [comment]
That's still big for a README. Let's try 
![browserstack-logo](https://user-images.githubusercontent.com/587740/39730225-625453c2-522e-11e8-97af-e2ad0ce6715f.png)

**Comment by wmhilton** [comment]
![browserstack-logo](https://user-images.githubusercontent.com/587740/39730261-9c65c4d8-522e-11e8-9f12-16b349377a35.png)

**Comment by DanielRuf** [comment]
You can also use HTML in the readme to set the needed size (<img src="" width="" height="" ...) =)

**Comment by wmhilton** [comment]
Inconclusive.
