### ISSUE TITLE
.gitignore ** rules not consistent with regular git syntax

### ISSUE THREAD

**Issue by NomarCub** [isomorphic-git/isomorphic-git#1641]
`folder/other-folder/**/**js` does not ignore `folder/other-folder/dir/main.js`.
Double asterisks should be interpreted here as two asterisks, which match anything - see https://git-scm.com/docs/gitignore#_pattern_format

I am using isogit in a plugin to the Obsidian note-taking app on Android. The issue came up there: https://github.com/denolehov/obsidian-git/issues/297

**Comment by Vinzent03** [comment]
> Double asterisks should be interpreted here as ~~two~~ one asterisks

**Comment by NomarCub** [comment]
The doc says this:
> Other consecutive asterisks are considered regular asterisks

So I think it really is two asterisks.

**Comment by jcubic** [comment]
@NomarCub Since you need to feature maybe you want to do the fix? This project is driven by contributors. I'm a maintainer but I don't write code myself for this project. And there is no primary author, that will do all the hard work.

**Comment by NomarCub** [comment]
I kinda have a lot on my plate now, but I might take a look eventually.
I made this issue not so much because I *need* a fix very badly, but more to confirm and inform devs and users alike that this discrepancy exists, because I would have liked to know this info earlier when I went Googling about this.

**Comment by ar-nelson** [comment]
`isomorphic-git` uses `ignore` (https://github.com/kaelzhang/node-ignore) to parse `.gitignore` files and determine which files to ignore, so this is actually a bug in `ignore`.

**Comment by mojavelinux** [comment]
Thanks for pointing that out. It also looks it has been reported (or at least a variation of this case): https://github.com/kaelzhang/node-ignore/issues/57

**Comment by NomarCub** [comment]
I have no means to verify for my examples anymore, but apparently this has been solved in node-ignore.
