### ISSUE TITLE
`listBranches` return nothing on init project

### ISSUE THREAD

**Issue by Zorin95670** [isomorphic-git/isomorphic-git#1650]
Scenario:
1. Create a project
2. Make a `git.init` command
3. get all local branch with
```
git.listBranches({
  fs,
  dir: 'CURRENT_PROJECT_DIR',
}),
```

I expect to have `['master']` as branche list, but I receive `[]`.
And when I use this command: 
```
  git.currentBranch({
    fs,
  dir: 'CURRENT_PROJECT_DIR',
    fullname: false,
  });
```
I receive `'master'`

So I think, there I think there is a bug :)

Using with browser and browserfs with import statement in my vue 3 composable: 
```
import git from 'isomorphic-git';
import http from 'isomorphic-git/http/web';
```

**Comment by jcubic** [comment]
This project is driven by contributors it doesn't have the main author that does all the work for free, so if you want to make this fixed you will need to do this yourself or find someone that will do this for you.

**Comment by dead-end** [comment]
The c implementation works the same way. After the initialization, the current branch is shown but the list of branches is empty:

```bash
$ git init
Initialized empty Git repository in /tmp/test/.git/

$ git branch --show-current
master

$ git branch
```

The listing of the branches works after the first commit:

```bash
$ touch test.txt

$ git add test.txt 

$ git commit -m 'init'
[master (root-commit) c0d8784] init
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test.txt

$ git branch
* master
```

The listing in isomorphic-git also works after the root-commit.

The root commit writes the sha to the master file:
```
cat .git/refs/heads/master 
b6353c1035aad5c789ff03aa5858f9f7d8248e08
```

Before the first commit the directory `.git/refs/heads` is empty.

And the files inside the `.git/refs/heads` directory are uses to get the branch listing:
```
  static async listBranches({ fs, gitdir, remote }) {
      ...
    } else {
      return GitRefManager.listRefs({ fs, gitdir, filepath: `refs/heads` })
    }
  }
```

I think the simple truth is that the initialization of the repository is completed after the first commit.

To fix the issue, the `listBranches` function needs a fallback if the `.git/refs/heads` directory is empty. And the fallback is to return the current branch as a list.
