### ISSUE TITLE
Simple Chrome CORS extension to enable clone/push from the browser.

### ISSUE THREAD

**Issue by ptoner** [isomorphic-git/isomorphic-git#1659]
https://github.com/ptoner/isomorphic-git-cors-extension

A simple Chrome extension to add CORS headers to GitLab/GitHub requests.

Allows isomorphic-git to push to GitLab and GitHub without CORS issues.

Uses Chrome's [declarativeNetRequest](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest) to enable this with a simple rule-based approach and no executable code.

Currently it only supports GitLab because that's what I'm testing with but it will be trivial to add the same for GitHub. 🤞

**Comment by jcubic** [comment]
Nice, but note that most people create apps for people where isomorphic-git run on users' browsers. Asking people to download extensions to run the application is not an option.

Do you expect something from the project?

**Comment by ptoner** [comment]
Not sure I understand the question.

Just linking it here in case any users would like to easily work around the CORS issue themselves. I am using isomorphic-git in a browser-based app and a proxy is not an option. This is a simple option.

**Comment by jcubic** [comment]
I don't think that asking users to install the extension is an option. It may work when you're the only user but not when you have actual users of the application.

**Comment by ptoner** [comment]
Isn't that my problem and not yours? I'm using it for development and it was far easier than setting up a proxy server. My users are devs and have git installed. Installing a super simple extension to enable compatibility with major git providers isn't a big ask at all. 

Why so hostile to a contribution? It's useful to me and I shared it in case it was useful to others. Don't use it if it's not?

**Comment by jcubic** [comment]
What contribution? You shared a link, in an issue that supposes to be for bug reports and feature requests. I don't see any of them here. What do you expect me to do with that link?

**Comment by ptoner** [comment]
This addresses a common request for major git providers. The original author of this plugin lobbied aggressively to try to get GitLab to change the CORS headers. There are a lot of users who have 👍 the issue in the GitLab thread. A proxy is NOT a secure solution. A Chrome extension IS even though it is not ideal. It's certainly easier than having to set up a whole node server or rely on insecure proxy servers.

It would certainly be better if GitLab and GitHub just addressed the issue directly but they are NOT.  This is at least an option. 

Personally I think this should be an option BEFORE the proxy. This allows users to use isomorphic-git directly in the browser and clone/pull without sending their credentials to...WHO exactly? My target audience would rather use a Chrome extension. 

All you did is call this a dumb idea and tell me to kick rocks. No discussion? No time for others to chime in? And now you're back acting like this doesn't even qualify as a contribution? Like...ok. Good luck with that.

**Comment by ptoner** [comment]
Any other project would at least figure out a simple "Community Contributions" place to link things and a thank you. I didn't even actually ask for anything. I just wanted to share. You called my idea dumb and basically hide this out of view.

**Comment by mojavelinux** [comment]
I think what Jakub was suggesting was for you to submit a PR for the docs that could be merged, something actionable. The issue tracker isn't a general discussion forum, so it's not a great place for important information to live (since the issue can't remain open indefinitely and once the issue is closed it is out of view). Would you be willing to submit a PR to the docs with the information you want to share with other users? I would certain be supportive of making that information available to users of this package.

**Comment by mojavelinux** [comment]
I like the idea of adding it to the snippets page. That page is framed as helpful hints for others in similar circumstances, and often brought forward by users. And since many users, including the original author, are very interested and passionate about this topic, I think it is indeed great information to share there.

Like I said, I don't think the intent was to shoot your idea down or diminish your excitement. This is just a very PR-oriented project. So let's just channel the feedback to the right outlet.

**Comment by jcubic** [comment]
@ptoner there is a section about CORS in README you can add information about extension there. But I would wait before you can have GitHub support since this is probably the most used git hosting. Or you can add info right now but with info that this is experimental.

**Comment by ptoner** [comment]
Ok. I'll add GitHub and test for a bit more and later submit a PR to include a link in the README. Thank you.

**Comment by ptoner** [comment]
Just a follow-up:

https://github.com/isomorphic-git/isomorphic-git/issues/780

Because of the issue described in this thread, this approach actually doesn't work on Github. Just GitLab.

"However, GitHub appears to explicitly reject it by returning a 405 response to the OPTIONS pre-flight request."

Which is a bummer and I haven't really found a work-around even with a Chrome/Firefox extension.

**Comment by jcubic** [comment]
From what I know GitLab support CORS so you don't any extension.

**Comment by ptoner** [comment]
Nope. The thread I linked earlier discusses it. https://gitlab.com/gitlab-org/gitlab/-/issues/20590
