### ISSUE TITLE
can't pass a relative path when cloning - proxy related

### ISSUE THREAD

**Issue by y-nk** [isomorphic-git/isomorphic-git#1666]
### Context

I'm using isomorphic-git in the browser, in the context of a NextJS app. As you may know or not, Next as a built-in feature for a proxy, which i hoped to use in order to avoid using the public proxy or hosting a separate server.

It comes like this: 

1. In your framework config file, you'll add a `rewrites` function such as:
```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return [
      {
        source: '/github/:path*',
        destination: 'https://github.com/:path*',
      },
    ]
  },
}

module.exports = nextConfig
```

2. In your code app, you should make requests to `/github/` instead of `https://github.com/` and the rest flows properly.

### Problem

When cloning, the lib expects a url of the form of `https://github.com`. It looks like there's a provider detection based on the url.

```
UrlParseError: Cannot parse remote URL: "/github/####" (### → url of the repository)
    at GitRemoteManager.getRemoteHelperFor (index.js?163f:6873:1)
    at _fetch (index.js?163f:7403:1)
    at async _clone (index.js?163f:7781:40)
    at async clone (index.js?163f:7904:1)
    at async eval (index.tsx?cd06:40:7)
```

any idea how to bypass that? Is there a way to pass directly the provider's name `"github"` in some parameter to shortcut the `GitRemoteManager.getRemoteHelperFor` call?

**Comment by jcubic** [comment]
The way HTTP and the Web works you should be able to use full URL not path `https://yourserver.com/github` and your code should work just fine.

**Comment by y-nk** [comment]
Full URL depends on the server it's deployed to (locally or some remote location). I'd rather avoid hardcoding the url of a server if the value changes depending on the environment it's used in; it's just not good DX.

Thanks for the (slightly mean) lesson on how the web works tho.

**Comment by jcubic** [comment]
You can read the server you're running your script. [How can I get the server name for where node.js is running?](https://stackoverflow.com/q/27324247/387194)

**Comment by y-nk** [comment]
I don't know where is it in the way HTTP and the web works that the hostname of a machine (`os.hostname`) is correlated to the dns of a server.

**Comment by jcubic** [comment]
Just put the full URL, and get a domain name from the server. Every sever has access to the server name on which it runs.
