### ISSUE TITLE
populateStat is not a function

### ISSUE THREAD

**Issue by kotAPI** [isomorphic-git/isomorphic-git#1667]
Please be sure to mention:
- On Nodejs electron app
- Using via NPM package

I've tried the snippet posted on this issue - https://github.com/isomorphic-git/isomorphic-git/issues/732

Assuming it's a bit older the only change i could notice was that the snipped used `walkBeta1` but the new version (1.21.0) only has `walk`. 

When I tried logging A,B I get this error
<img width="773" alt="image" src="https://user-images.githubusercontent.com/4013556/201506117-9999c7f4-021f-4bb1-b9d7-221acd92af01.png">

My code version -
```
 
export const getChangedFiles = async (localGitFolderPath) => {
    try {
        const commits = await log({ fs, dir:localGitFolderPath, depth: 2 })
        const oids = commits.map(commit => commit.oid)
        console.log(oids)

        const A = await TREE({ fs, dir: localGitFolderPath, oid: oids[0] })
        const B = await TREE({ fs, dir: localGitFolderPath, oid: oids[oids.length - 1] })
        console.log(A,B)
        return walk({
            fs,
            dir:localGitFolderPath,
            trees: [
               A,B
            ],
            map: async function ([A, B]) {
             
                // ignore directories
                if (A.fullpath === '.') {
                    return
                }
                await A.populateStat()
                if (A.type === 'tree') {
                    return
                }
                await B.populateStat()
                if (B.type === 'tree') {
                    return
                }
             

                // generate ids
                await A.populateHash()
                await B.populateHash()

                // determine modification type
                let type = 'equal'
                if (A.oid !== B.oid) {
                    type = 'modify'
                }
                if (A.oid === undefined) {
                    type = 'add'
                }
                if (B.oid === undefined) {
                    type = 'remove'
                }
                if (A.oid === undefined && B.oid === undefined) {
                    console.log('Something weird happened:')
                    console.log(A)
                    console.log(B)
                }

                return {
                    path: `/${A.fullpath}`,
                    type: type
                }
            }
        })
    } catch (err) {
        console.log(err)
    }
}
```

**Comment by jcubic** [comment]
This is an old issue and as you can see the API changed. Don't rely on old snippets created before 1.0. I have no idea what `populateStat` is if it's not documented you will need to read the source code. The author of this snippet doesn't work on the project anymore.

**Comment by kotAPI** [comment]
> This is an old issue and as you can see the API changed. Don't rely on old snippets created before 1.0. I have no idea what `populateStat` is if it's not documented you will need to read the source code. The author of this snippet doesn't work on the project anymore.

 I had noticed that, Any other way to get this to work that you can think of?

**Comment by jcubic** [comment]
No, sorry. I have no idea. As I've said if it's not documented you will need to read the source code to understand how `walk()` works.

**Comment by mojavelinux** [comment]
I recently had to use the `walk` function to apply a transformation to the worktree. I decided to share that snippet to help others who need to do similar kinds of operations with `walk`. See https://github.com/isomorphic-git/isomorphic-git/pull/1668

**Comment by mojavelinux** [comment]
Regarding this issue, I think the problem you are facing is that the properties on a tree entry are now async functions. You can see an example in the snippet I shared for how to get the mode. It needs to look something like `await entry.oid()`, not `entry.oid`.

**Comment by kotAPI** [comment]
> Regarding this issue, I think the problem you are facing is that the properties on a tree entry are now async functions. You can see an example in the snippet I shared for how to get the mode. It needs to look something like `await entry.oid()`, not `entry.oid`.

Oh I see, this is helpful information, I'm going to try out something and update later. Thanks!
