### ISSUE TITLE
Want to bundle script using webpack

### ISSUE THREAD

**Issue by bajrangCoder** [isomorphic-git/isomorphic-git#1707]
I have created a nodejs script that clone repo using isomorphic-git and it's working due to awesome isomorphic-git library but i want to bundle my script into bundle using webpack, i have tried some ways but it gives errors .

Is there any effective way to do this?or any other way
I had also tried isomorphicgit with lighting fs then compiles without error but at time of coloning it gives error , `Error : ENOENT:.`
ANY SOLUTION OF IT?

**Comment by zensayyy** [comment]
what was the solution here? I ran into a similar issue

**Comment by jcubic** [comment]
@zensayyy can you provide an example code? Try to create [Minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).
