### ISSUE TITLE
Error: ENOENT: /tutorial/.git/config in Safari 16.1

### ISSUE THREAD

**Issue by VariantXYZ** [isomorphic-git/isomorphic-git#1730]
I've been trying to follow the quick-start guide and the clone documentation in the Browser to do a quick clone test and I seem to be hitting this error:

```Error: ENOENT: /tutorial/.git/config```

My setup is just a minimal version of the quick start guide (I tried with and without the create dir).

I did make sure to have cross-origin restrictions disabled since I'm testing locally, so I would've figured the proxy wouldn't matter, but I tried with and without it to no avail.

```
<script src="https://unpkg.com/@isomorphic-git/lightning-fs"></script>
<script src="https://unpkg.com/isomorphic-git@beta"></script>
<script type="module">
import http from 'https://unpkg.com/isomorphic-git@beta/http/web/index.js'

window.fs = new LightningFS('fs', { wipe: true })
window.pfs = window.fs.promises

// Example from https://isomorphic-git.org/docs/en/clone
await git.clone({
  fs,
  http,
  dir: '/tutorial',
  corsProxy: 'https://cors.isomorphic-git.org',
  url: 'https://github.com/isomorphic-git/isomorphic-git',
  singleBranch: true,
  depth: 1
})
console.log('done')

</script>
```

Any ideas? Did I make a mistake in my usage?

**Comment by jcubic** [comment]
Do you have any errors?

**Comment by VariantXYZ** [comment]
@jcubic , sorry for not mentioning it in the description, but the error is the issue title.

**Comment by jcubic** [comment]
I will need to test. Do you maybe the page with this error online. I will check in BrowserStack.

**Comment by VariantXYZ** [comment]
I'm using GitHub Pages to host one that clones my own repository here, is this sufficient? https://vxyz.me/LatorGit/

The repository is different, but it's the same error, I'm using the JavaScript console to breakpoint and catch exceptions:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/3066132/218367469-2d1249a5-1612-40bb-8661-26e4a53383c8.png">

**Comment by jcubic** [comment]
Thanks, I will check in few days when I get back home.

**Comment by VariantXYZ** [comment]
@jcubic , no need, it seems like this was entirely a misunderstanding on my end. Things seem to work, it seems that just catching the exceptions was causing it to fail (even when I forwarded through all of them).

It seems to work just fine now.
