### ISSUE TITLE
Update Auth documentation

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#1749]
I think that this page is outdated:

https://isomorphic-git.org/docs/en/authentication

It needs to be updated according to API documentation. direct username and password/token don't work in version 1.x

**Comment by jubesab** [comment]
@jcubic This was already done in https://github.com/isomorphic-git/isomorphic-git/pull/1728 but maybe not published to the site?

**Comment by jcubic** [comment]
Thanks, it seems that the PR modified the wrong file. The edit need to happen on a different repository in the file:

https://github.com/isomorphic-git/isomorphic-git.github.io/edit/source/docs/authentication.md

**Comment by anuoua** [comment]
Looks like document is still outdate，and when the proxy and authentication are used together, there will be problems. The address behind the proxy does not contain the username and password.

**Comment by jcubic** [comment]
@anuoua do you want to contribute?

**Comment by IAmSSH** [comment]
Hey @jcubic,
I would like to work on this and update the documentation.
Is there anything missing in the wrongly updated file?.. i.e., do we need any other info apart from the one already updated in `docs/authentication.md`

**Comment by jcubic** [comment]
@IAmSSH documentation is wrong, this is how you authenticate using isomorphic-git.

I also think that authentication.md is also not the correct way to authenticate.

You can see the proper arguments to push:

https://isomorphic-git.org/docs/en/push

the proper way to authenticate is to use onAuth callback.

**Comment by IAmSSH** [comment]
Ok, thanks 👍
I'll start working on it

**Comment by IAmSSH** [comment]
Hey @jcubic 
Created the PR [here](https://github.com/isomorphic-git/isomorphic-git.github.io/pull/92). Please review.
Thanks 😁
