### ISSUE TITLE
[feat] Add benchmark

### ISSUE THREAD

**Issue by loynoir** [isomorphic-git/isomorphic-git#1750]
Seems there are many git library.

- 6.8K https://github.com/isomorphic-git/isomorphic-git
- 5.4K https://github.com/nodegit/nodegit
- 3K https://github.com/steveukx/git-js

I guess each library has its own advantages, but it is not clear the performance of each library compared to raw git command.

Would be nice if these project can add some benchmark on some real world cases, like

https://stackoverflow.com/questions/610208/how-to-retrieve-a-single-file-from-a-specific-revision-in-git

**Comment by jcubic** [comment]
Do you want to contribute such a benchmark? I'm afraid that if you will don't do that no one will have the time to do this for you.

**Comment by loynoir** [comment]
@jcubic 

Done. 

https://github.com/loynoir/git-bench/blob/main/bench.txt

```txt
┌─────────┬──────────────────────┬────────────────────┬────────────────────┐
│ (index) │      Task Name       │ Average Time (ps)  │   Variance (ps)    │
├─────────┼──────────────────────┼────────────────────┼────────────────────┤
│    0    │    'nodegit_show'    │ 17454.492400586605 │ 48597.35877568342  │
│    1    │ 'isomorphicGit_show' │ 103790.86129888892 │ 2546108.500931256  │
│    2    │   'simpleGit_show'   │ 18480.07160052657  │ 11399.379668975851 │
│    3    │   'execFile_show'    │ 22125.246600806713 │ 188033.89266282678 │
│    4    │     'execa_show'     │ 14523.749800771475 │ 2120.7074128907416 │
└─────────┴──────────────────────┴────────────────────┴────────────────────┘
```
