### ISSUE TITLE
'No such file or directory, stat 'somepath/.git/config'' when cloning a repo

### ISSUE THREAD

**Issue by CluEleSsUK** [isomorphic-git/isomorphic-git#1751]
Using ts-node@10.9.1 and node 19.4.0, I ran the following snippet:
```typescript
const repo = "https://some.repo/here"
const dir = path.join(process.cwd(), "./blah")
await fs.mkdir(dir)
await git.clone({fs, http, dir, url: repo, singleBranch: true, depth: 1})
```
and get the error 
```[Error: ENOENT: no such file or directory, stat 'some/path/to/blah/.git/config'] { errno: -2, code: 'ENOENT', syscall: 'stat', path: 'blah/.git/config' }```

I wouldn't expect `./blah/.git/config` to exist yet as I'm cloning the repo for the first time.
I also tried running `git.init()` before it but it also threw the same error.
The repo in question was public and can be cloned fine using the vanilla git CLI

**Comment by jcubic** [comment]
What is `http` in your code? Maybe the library throws a wrong error. Also, can you run this with node? You don't have any types with this example.

**Comment by CluEleSsUK** [comment]
my imports are as follows:
```javascript
import path from "path"
import fs from "fs/promises"
import * as http from "isomorphic-git/http/node"
import * as git from "isomorphic-git"
```

**Comment by jcubic** [comment]
did you tried:
```javascript
import fs from "fs"
```
like in the documentation (npm readme)?

**Comment by CluEleSsUK** [comment]
Ah hmm, yes using `fs` without the promises seems to work - I would have expected the promise version to work too ;o

**Comment by CluEleSsUK** [comment]
Understood - thanks for your swift help!!

**Comment by slyduda** [comment]
I am running into the same issue on `git.init` on a WebWorker based implementation with the following code:

```js
importScripts(
    "https://unpkg.com/@isomorphic-git/lightning-fs",
    "https://unpkg.com/isomorphic-git@beta",
    "https://unpkg.com/isomorphic-git@beta/http/web/index.umd.js",
);

const fs = new LightningFS('project');
const pfs = fs.promises;

await pfs.writeFile('/path', 'Something')

const init = await git.init({ fs: pfs, dir: '/' })
const fileList = await git.listFiles({ fs: pfs, dir: '/' })

```

The error code again is as follows: Error: `ENOENT: /.git/config`

I tried following the WebWorker example in the docs and made promise modifications. Am I missing an import that is causing this issue?

**Comment by jcubic** [comment]
@slyduda Already explained you can't use promisified fs with isomorphic-git:

You need:

```javascript
const init = await git.init({ fs: fs, dir: '/path' })
```

Also in canonical git if I remember correctly the directory needs to be empty, not sure if isomorphic-git has the same requirement.

**Comment by slyduda** [comment]
Thank you! This fixed my issue. Apologies for not reading your explanation earlier - I guess I skimmed over it.
