### ISSUE TITLE
Invalid checksum in GitIndex buffer: Encoding Errors

### ISSUE THREAD

**Issue by slyduda** [isomorphic-git/isomorphic-git#1756]
To preface, I am using isomorphic-git on a WebWorker in parallel with a Vue app. All encoding and decoding is done on the WebWorker.

Unfortunately, I am adding to the long list of Invalid checksum issues in this repository, but thankfully I am, not relying on a third party package and I am close to understanding what the issue is. My use case transforms isomorphic-git/lightning-fs file data to a string that I store on my client side app, then I fs.writeFile in my WebWorker by repopulate the file system from scratch with the file data (in string data form) and continue with my git commands. The issue is that I notice the checksums aren't the same, because the ArrayBuffer lengths are different. I suspect that the way that I am decoding the data is creating this issue. 

The easiest way that I am repeating this issue is with the initial /.git/index file. The following is the way I reproduce this: 
Webworker: git init -> 
Webworker: decode all files into utf8 strings -> 
Main: store all file data (string format) -> 
Main: add a file -> 
WebWorker: repopulate fs (with all files including .git and new file) -> 
Webworker: git add the new file -> 
Webworker: decode all files into utf8 strings -> 
Main: store all file data (string format) -> 
Main: add a file -> 
WebWorker: repopulate fs (with all files including .git and new file) -> 
Webworker: git add the new file -> 
Webworker: Invalid checksum in GitIndex buffer

The following code is how I decode the data from the files:
```js
const directory = '/.git/index'
const decoder = new TextDecoder("utf8")
const data = decoder.decode(await pfs.readFile(directory))
```

The following code is how I repopulate each file with the decoded strings I store:
```js
await pfs.writeFile(file.path, file.data)
```

The following is the array data after the first git add and before the second git add:

```
const postFirstGitAddArrayBuffer = [
  68, 73, 82, 67, 0, 0, 0, 2, 0, 0, 0, 1, 100, 76, 164, 88, 17, 195, 30, 128,
  100, 76, 164, 88, 17, 195, 30, 128, 0, 0, 0, 1, 0, 0, 0, 12, 0, 0, 129, 164,
  0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 230, 157, 226, 155, 178, 209, 214, 67, 75,
  139, 41, 174, 119, 90, 216, 194, 228, 140, 83, 145, 0, 4, 97, 115, 108, 121,
  0, 0, 0, 0, 0, 0, 54, 77, 79, 70, 38, 157, 124, 39, 128, 80, 80, 142, 216, 24,
  129, 69, 4, 254, 103, 247,
];

const preSecondGitAddArrayBuffer = [
  68, 73, 82, 67, 0, 0, 0, 2, 0, 0, 0, 1, 100, 76, 239, 191, 189, 88, 17, 239,
  191, 189, 30, 239, 191, 189, 100, 76, 239, 191, 189, 88, 17, 239, 191, 189,
  30, 239, 191, 189, 0, 0, 0, 1, 0, 0, 0, 12, 0, 0, 239, 191, 189, 239, 191,
  189, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 239, 191, 189, 226, 155, 178, 239,
  191, 189, 239, 191, 189, 67, 75, 239, 191, 189, 41, 239, 191, 189, 119, 90,
  239, 191, 189, 239, 191, 189, 239, 191, 189, 83, 239, 191, 189, 0, 4, 97, 115,
  108, 121, 0, 0, 0, 0, 0, 0, 54, 77, 79, 70, 38, 239, 191, 189, 124, 39, 239,
  191, 189, 80, 80, 239, 191, 189, 239, 191, 189, 24, 239, 191, 189, 69, 4, 239,
  191, 189, 103, 239, 191, 189,
];
```

Sorry for adding to the long list of checksum issues. I wanted to be as thorough with my explanation as possible and I am still planning on attempting to figure this out myself. I'm sure that the solution is simple, but I want to put this out there just in case other developers run into encoding and decoding issues as well. I suspect that many of the other issues (including Salesforce issues) may just be due to faulty decoding.

**Comment by slyduda** [comment]
Okay so to solve this I believe I must only store file data as ArrayBuffers due to the nature of utf8 decoding. What is happening is that the `/.git/index` is encoded differently and I have to use an external library to detect encodings. The first mismatch: 164 converts to 239, 191, 189 and this is why the second buffer is bigger. 

This also means that if I want my application to work, I can't store file data as string format values, I have to store them as Buffer Arrays and do the translation when necessary. 

I'm going to close my issue!

**Comment by jcubic** [comment]
Yes, it's not a good idea to convert Binary data as strings. Unless you convert to UInt8Array and convert numbers as strings for instance using Hex values that will be later converted back to Uint8Array. Another idea is to compress such string using some fast compression. In my other project, I used `lzjb-pack` library from NPM, it was a different context in my case I needed to serialize JavaScript objects to binary that will not take a lot of space.

**Comment by jcubic** [comment]
And if you want to see how to save FS into a single file you can check my project [fake-linux-terminal](https://github.com/jcubic/fake-linux-terminal), where I create Image files on the server and load them into FS when booting. The project is not finished but the FS images working without any issues.
