### ISSUE TITLE
Fs client problem 

### ISSUE THREAD

**Issue by bajrangCoder** [isomorphic-git/isomorphic-git#1758]
Hello 
I have made a app using html, js ,etc and I want to include isomorphicgit features in it but isomorphicgit requires a fs client that I don't have but some how i have made it but it has only limited method (not a large of methods as nodejs fs have) , that's why I thought it's not compatible with isomorphicgit.
I have tried with Lighting fs, it's working but i want to perform all git operation on my local file system. So is there any approach for my case??
If anyone have i idea please suggest me.
I am glad to hear ❤️

Note: My custom fs can interact with local files of my device.
My custom fs works something like this
const a = await myFs(path of file or directory).any following methods 
My custom fs have these methods only(following methods takes some parameters):
lsDir, createDirectory(), writeFile(), createFile(), delete(), exists(), stat(), readFile(), copyTo(), move to(), renameTo()

**Comment by jcubic** [comment]
So if you only have front-end code you can use [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API). But this is not implemented you will need to implement LightningFS backend to be able to use this API with Isomorphic-Git.

You have a few options:
* Write the backend yourself
* Wait for someone to write it for you
* Pay someone to write it for you

This is when you want the code in the browser to interact with the same computer that runs the browser. If you want to run the code on the server you will need to implement lighting-fs backed that will use Ajax (HTTP requests).

> Note: My custom fs can interact with the local files of my device.

I'm not sure what you mean by that, do you have FS already that you can use, if so you need to hook it up with lightning-fs as the backend (I'm not sure if there are any benefits of doing this) the old Backend API is just a reimplementation of each native node fs method used by isomorphic-git, so I think that you can just use the fs as is. But you need to follow the API used by LightingFS and implement the same methods as the public API.

**Comment by bajrangCoder** [comment]
Ok
Thanks for your response ❤️
I will try to implement these all in my custom fs.
