### ISSUE TITLE
Invalid checksum in GitIndex buffer: expected 0e132638005b666f7263652d6170702f6d61696e but saw 7f4205634ca35523d7aa4952458357f0408b4ae6

### ISSUE THREAD

**Issue by AJBharathan** [isomorphic-git/isomorphic-git#1763]
Facing issues in VS Code that "Invalid checksum in GitIndex buffer". 

This is the full error message "Invalid checksum in GitIndex buffer: expected 0e132638005b666f7263652d6170702f6d61696e but saw 7f4205634ca35523d7aa4952458357f0408b4ae6" 

I have tried to update version and downgrade version too, its not working. Could you please help.

**Comment by jcubic** [comment]
Please report this to VS Code authors that need to create proper reproduction of the issue.
Just error message doesn't help in any way resolving the issue. The authors of the VS Code or extension you're using need to debug this and you need to provide exact steps you did.

**Comment by dead-end** [comment]
The error message says that you `.git/index` file is broken. The index file is a binary file with staging informations. The last 20 bytes of the file are a checksum and the  _expected 0e132638005b666f7263652d6170702f6d61696e_ is the checksum hex-encode. If you hex-decode the expected value you get `&8�[force-app/main`. This does not look like a checksum.

Is it possible that you add the `.git/index` file as an attachment to the issue, so that I can take a look at it?

**Comment by SamusenkoAleksey** [comment]
Experiencing the same problem:

`Invalid checksum in GitIndex buffer: expected  but saw da39a3ee5e6b4b0d3255bfef95601890afd80709`

[git index.txt](https://github.com/isomorphic-git/isomorphic-git/files/11745737/git.index.txt)

**Comment by dead-end** [comment]
@SamusenkoAleksey, thank you for submitting the index file. The file is absolutely valid and contains 13475 entries, so there is no reason why isomorphic-git should have an issue. Does the error regularly occur or was it a single error? How do you use isomorphic-git, as a library or with a program, in the browser or as a node app?

In the error message, the expected value is missing. Normally this means that the index file is empty, which is obviously not the case. The content of the file is read to a Buffer and it is checked that this is a Buffer (`if (Buffer.isBuffer(buffer)) {`). An undetected IO error would lead to an undefined buffer, which is not a valid buffer. 

I continue to analyze the problem and hope you can answer my questions.

**Comment by dead-end** [comment]
@SamusenkoAleksey: I have checked the code and your error message only occurs if the `./git/index` files exists **and** is empty. It has an other message if the file does not exist or an error occurs while reading the file.

**Comment by dead-end** [comment]
The issue at foresales: [https://github.com/forcedotcom/cli/issues/2194](https://github.com/forcedotcom/cli/issues/2194)

**Comment by jcubic** [comment]
If the linked issue doesn't solve the problem Try reporting this to project [forcedotcom/cli](https://github.com/forcedotcom/cli/issues) as a separate issue.

I know that the error says to report it here, but the bug is in the Salesforce extension, nothing we can do about the bug in that project.
