### ISSUE TITLE
SFDX: Invalid checksum in GitIndex buffer

### ISSUE THREAD

**Issue by hendrik-meiwes-adesso** [isomorphic-git/isomorphic-git#1765]
Invalid checksum in GitIndex buffer: expected  but saw da39a3ee5e6b4b0d3255bfef95601890afd80709
Please be sure to mention:
- Tool: Visual Studio Code
- Command: Deploy Source to Org

**Comment by jcubic** [comment]
Report this to the author of the thing you're using. They need to update and debug this.

See #1755
