### ISSUE TITLE
Isomorphic git issue

### ISSUE THREAD

**Issue by Gowtham2705** [isomorphic-git/isomorphic-git#1766]
Invalid checksum in GitIndex buffer: expected 2f6173736574732f69636f6e732f7374616e6461 but saw ac61690794c5da9817744156285b750bd48f01ae

**Comment by jcubic** [comment]
This is not helpful please describe what is the problem in details what code you use what tools.

**Comment by dead-end** [comment]
If you hex-decode: _2f6173736574732f69636f6e732f7374616e6461_ the expected hash value you get: _/assets/icons/standa_, which is clearly not a sha hash.

**Comment by dead-end** [comment]
Is it possible that you add the .git/index file as an attachment to the issue, so that I can take a look at it?

**Comment by jcubic** [comment]
This is probably an issue with Salesforce CLI (the OP didn't even care only saw the Action in the error message), Even though the error message says to report the issue to this library you should create an issue here:

https://github.com/forcedotcom/cli/issues/new/choose

Search if there are no issues already related to the problem. There should be a lot of them.
