### ISSUE TITLE
Hang when using `git.statusMatrix`

### ISSUE THREAD

**Issue by coderaiser** [isomorphic-git/isomorphic-git#1768]
Please be sure to mention:
- Node

```js
const status = await git.statusMatrix({
    fs,
    dir,
    filter: isSupported,
});
```

Looks like this is related to [v1.24](https://github.com/isomorphic-git/isomorphic-git/releases/tag/v1.24.0)

Here is how it used:
https://github.com/coderaiser/putout/blob/v29.9.0/packages/putout/lib/cli/staged.js#L47-L51

To reproduce you can use:

```
putout --staged
```

It works good with `v1.23.0` and freezes with `v1.24.0` of `isomorphic-git`.

**Comment by jcubic** [comment]
Do you have proper git repo? Can you execute other git commands?

**Comment by coderaiser** [comment]
This example also hangs:

```js
const git = require('isomorphic-git');
const fs = require('fs');

async function main() {
    const status = await git.statusMatrix({
        fs,
        dir: '.',
        filter: () => true,
    });
}

main().then(console.log);
```

And ruins git repository

![image](https://github.com/isomorphic-git/isomorphic-git/assets/1573141/aaf88c93-a76e-4760-aad2-f69ee2d3d9ca)

**Comment by jcubic** [comment]
The last feature was adding `parallel` option to git add.

https://github.com/isomorphic-git/isomorphic-git/pull/1767

Do you want to help debug this issue?

**Comment by coderaiser** [comment]
I don't understand how such simple example, that should only read information from `.git` directory:

```js
const git = require(https://github.com/isomorphic-git/isomorphic-git);
const fs = require(['fs'](https://nodejs.org/api/fs.html));

async function main() {
    const status = await git.statusMatrix({
        fs,
        dir: '.',
        filter: () => true,
    });
}

main().then(console.log);
```

Just ruined my git repository, isn't this example helps to debug?

**Comment by coderaiser** [comment]
Maybe the problem with this https://github.com/isomorphic-git/isomorphic-git/commit/9b183f13a381a0134b83e4d211310fb1872ffff4

I don't that the problem with this https://github.com/isomorphic-git/isomorphic-git/commit/2942c85b0a5763d841babeb359c0d36ad97dfab5

**Comment by dead-end** [comment]
I tried this example:
```
const { clone, statusMatrix } = require("isomorphic-git");
const http = require("isomorphic-git/http/node");
const rimraf = require("rimraf");
const fs = require("fs");

main().catch(console.error);

async function main() {
  const dir = "./demo";
  const pfs = fs.promises;

  rimraf.sync(dir);
  await pfs.mkdir(dir);

  await clone({
    fs,
    http,
    dir,
    url: "https://github.com/coderaiser/putout.git",
  });

  const start = new Date();

  const stat = await statusMatrix({
    fs,
    dir,

    filter: (entry) => {
      return true;
    },
  });
  console.log(stat);
  console.log(start, new Date());
}
```
It worked, but it took 4 minutes to get to the result:

```
  [ 'codemods/cut-legacy/test/fixture/id.js', 1, 1, 1 ],
  [ 'codemods/cut-legacy/test/fixture/legacy-fix.js', 1, 1, 1 ],
  [ 'codemods/cut-legacy/test/fixture/legacy.js', 1, 1, 1 ],
  [ 'codemods/cut-useless-functions/.eslintrc.json', 1, 1, 1 ],
  [ 'codemods/cut-useless-functions/.gitignore', 1, 1, 1 ],
  [ 'codemods/cut-useless-functions/.madrun.mjs', 1, 1, 1 ],
  [ 'codemods/cut-useless-functions/.npmignore', 1, 1, 1 ],
  ... 6011 more items
]
2023-05-29T12:54:50.311Z 
2023-05-29T12:58:46.013Z
```
The `statusMatrix` function should read but not modify the `.git/index` file. Can you open the file and see whats inside? Git prints the error, if the file has less than 30 bytes.

**Comment by coderaiser** [comment]
I just added:

```js
console.log('->', e.mtimeNanoseconds, s.mtimeNanoseconds);
console.log('->', e.ctimeNanoseconds, s.ctimeNanoseconds );
```

and see that often this values is the same:

```sh
-> 640257324.21875 640257324.21875
-> 640257324.21875 640257324.21875
```

**Comment by coderaiser** [comment]
Would be great to get back to old solution, since nano seconds it's not something really important, no one change files in nano seconds. When you update files in your repository you most like change more then 1 byte, and slower then couple nano seconds. I'm using `isomorphic-git` to lint staged files, it not very fast, but works good even for very big repositories (and faster then `lint-staged`).

https://github.com/isomorphic-git/isomorphic-git/pull/1769

**Comment by dead-end** [comment]
I changed the check to nanoseconds, because we had an issue with updates that are performed programmatically. A resolution of a second is not precise enough in this case.  But simply using nanoseconds is obviously not a solution to this issue.

I just found a description for this issue: https://git-scm.com/docs/racy-git/en

I think going back to seconds seams to be the best option. But you have deactivate / comment out the last test in:
```
__tests__/test-status.js
```

**Comment by coderaiser** [comment]
I think this guys who want to use `git` programmatically can add some `option` for their use case.

**Comment by jcubic** [comment]
Ok lets revert the change, but I'm not sure if commenting out the unit test is the right thing to do.

**Comment by coderaiser** [comment]
I see that `compareStats` in my repository work about `11834` times in about 3 second in `v1.23`, and in `v1.24` it is slower in about 100 times and works a couple minutes.

**Comment by dead-end** [comment]
The unit test will fail, because we have no fix for #1245 when we revert the change.

**Comment by jcubic** [comment]
@dead-end I can run `git revert` on your commit are you ok to remove you from the contributors? You can create a PR and add yourself as helping with issues.

**Comment by dead-end** [comment]
Ok, don't forget to reopen the issue.

**Comment by jcubic** [comment]
@dead-end There was a conflict when reverting, so I've left the contributors.

**Comment by coderaiser** [comment]
@jcubic could you please publish new version?

**Comment by jcubic** [comment]
@coderaiser I can't this happen automatically by CI/CD when there is a proper commit message. I've got an email from Azure that a new release was built. There should be a new version.

**Comment by jcubic** [comment]
It seems not, I'm not sure what should be the commit message to create new minor version. I've added `fix(statusMatrix)` but it didn't create a new release.

**Comment by jcubic** [comment]
I'm not able to push force with a different commit message, because the branch is protected.
You need to wait for another fix or feature PR.

**Comment by coderaiser** [comment]
You can disable protection, force push, and then enabling it back, it takes 5 minutes…

Could you please publish fixed version?

**Comment by jcubic** [comment]
I'm not able to publish anything, I don't control it. Everything happens by CI/CD when you merge a PR with a proper commit message new release is created by CI/CD.

**Comment by jcubic** [comment]
This should be fixed by now, closing.
