### ISSUE TITLE
git exception report

### ISSUE THREAD

**Issue by nilkaush** [isomorphic-git/isomorphic-git#1780]
Please be sure to mention:
- whether you are using Node or the Browser
- how you are using it (if you are using a bundler what bundler; if you are using a `<script>` tag what CDN URL)

Metadata API request failed: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 64726573735f5f632f6669656c64732f50757270 but saw 37a48f4add2fe4f963edc7814c4a15448098b8a4

**Comment by nilkaush** [comment]
Hello,
Thank you for very quick response.

Indeed it is salesforce and issue comes at time of pushing code to scratch org.

Regards
Kaushal
________________________________

**Comment by dead-end** [comment]
The error message says that your `.git/index` file is broken. Unfortunately I do not know much about salesforce. From the sources from https://github.com/forcedotcom/source-tracking/blob/main/src/shared/localShadowRepo.ts I can see that maybe there is more than one index file.

Can you call `git status` in your project directory? 

Are there `.sf/orgs/<ORGID>/localSourceTracking` directories in your project directory?

**Comment by nilkaush** [comment]
git status : yes
dont see .sf in project folder.

Regards,
Kaushal
________________________________

**Comment by dead-end** [comment]
If `git status` works, then the `.git/index` file is ok. I guess that you tried the push more than once, with the same result?

At this point I think, I cannot help you. The issue seams to be in the salesforce client. Please contact the issue that I mentioned above.

**Comment by jcubic** [comment]
Try reporting this to project [forcedotcom/cli](https://github.com/forcedotcom/cli/issues).

I know that the error says to report it here, but the bug is in the Salesforce extension, nothing we can do about the bug in that project.
