### ISSUE TITLE
Bug: renaming the current branch doesn't update HEAD

### ISSUE THREAD

**Issue by alirezamirian** [isomorphic-git/isomorphic-git#1783]
Renaming the current branch leaves HEAD untouched by default, which leads to an invalid state of HEAD pointing to a missing ref. 
There is a `checkout` option which if `true`, updates HEAD. But even when `checkout` is not `true`, it doesn't make sense not to update HEAD, if the branch being renamed is the current branch.

I've tested the issue in Browser, not Node.

**Comment by alirezamirian** [comment]
Created a PR. Not sure about naming conventions and stuff, so let me know if I should update something, or feel free to push yourself.

**Comment by mojavelinux** [comment]
I support this change. In fact, I think I've hit this problem myself in the past. Thanks for bringing attention to it and submitting a fix.
