### ISSUE TITLE
Invalid checksum in GitIndex buffer: expected 69635365637572655f6c64732f63664b696e6574 but saw f751dbd8d7b55fb3fd1a8eaa7f684bdd2f7bc5ed

### ISSUE THREAD

**Issue by abidhal216** [isomorphic-git/isomorphic-git#1786]
Invalid checksum in GitIndex buffer: expected 69635365637572655f6c64732f63664b696e6574 but saw f751dbd8d7b55fb3fd1a8eaa7f684bdd2f7bc5ed

above error while taking retrieve in vs code from salesforce org.

**Comment by jcubic** [comment]
I was reported multiple times, this is the error in salesforce extensions you're using. Please see this issue https://github.com/forcedotcom/cli/issues/2194
