### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by sfdcdevabhi** [isomorphic-git/isomorphic-git#1787]
Invalid checksum in GitIndex buffer: expected 0000000000000000000000000000000000000000 but saw 6db8554b17340add584c7847e7546178e8bb2d4f

**Comment by jcubic** [comment]
I was reported multiple times, this is the error in salesforce extensions you're using. Please see this issue https://github.com/forcedotcom/cli/issues/2194

**Comment by jcubic** [comment]
Try reporting this to project [forcedotcom/cli](https://github.com/forcedotcom/cli/issues).

I know that the error says to report it here, but the bug is in the Salesforce extension, nothing we can do about the bug in that project.
