### ISSUE TITLE
Staged changes disappear after refresh.

### ISSUE THREAD

**Issue by kristiyanplpeev** [isomorphic-git/isomorphic-git#1788]
I am using isomorphic-git in the browser.

For showing the status of each file I use the status matrix. For modified unstaged files I get the ["file.txt", 1, 2, 1] and for modified staged files i get ["file.txt", 1, 2, 2] which is completely logical.

The problem occurs after refreshing the page, the unstaged changes behave as expected, but the staged changes are reverted (all the work is lost) and are displayed in the status matrix as ["file.txt", 1, 1, 1]

**Comment by jcubic** [comment]
Can you create a reproduction of the issue? It's hard to tell what's wrong if you don't show your code.

**Comment by kristiyanplpeev** [comment]
Really sorry, the bug was caused by my implementation. You may delete this issue :)
