### ISSUE TITLE
Objects present in a pack-file as well as loose break expandOid

### ISSUE THREAD

**Issue by willstott101** [isomorphic-git/isomorphic-git#1789]
We're using isomorphic git server-side to expose a GraphQL interface to some repos. We also serve these repositories from the same filesystem using `node-git-server`.

We've ended up with a repository which has an object both loose, as well as in a pack file. This object's contents is correct in both cases, it's just present twice. I don't actually know if that's something to do with upload-pack on the server-side creating and saving packs for clients which it then doesn't actually use as primary storage, or if something else has gone wrong.

The error we see is `"Found multiple oids matching \"c6f444fb83d643dbc82bedbc02e2cf0eccf204d4\" (c6f444fb83d643dbc82bedbc02e2cf0eccf204d4, c6f444fb83d643dbc82bedbc02e2cf0eccf204d4). Use a longer abbreviation length to disambiguate them."`

I have a test and a "fix" but I'm not sure I know enough to deem it definitely a good solution.

**Comment by dead-end** [comment]
@willstott101 I am not sure that it is correct, that the repo contains an object as a loose object and in the packed file. Do you have some example code, that ends up in this situation?

**Comment by willstott101** [comment]
According to Chat GPT :laughing: and these notes on `git gc --prune` sometimes loose objects are retained for 2 weeks by default when garbage collecting: https://git-scm.com/docs/git-gc#Documentation/git-gc.txt---pruneltdategt so even without network-related packs in upload-pack I believe it's valid to have objects in both places.

**Comment by willstott101** [comment]
That being said --prune might only apply to orphaned loose objects:
```
.../test2.git # find objects/ | wc -l
1031
.../test2.git # git -C . gc --no-prune
Enumerating objects: 785, done.
Counting objects: 100% (785/785), done.
Delta compression using up to 2 threads
Compressing objects: 100% (431/431), done.
Writing objects: 100% (785/785), done.
Building bitmaps: 100% (12/12), done.
Total 785 (delta 458), reused 589 (delta 340), pack-reused 0
.../test2.git # find objects/ | wc -l
8
``

**Comment by jcubic** [comment]
I know that the PR will fix this particular issue but I don't think that this is the root cause of the issue. I don't want to add a hack that doesn't solve the real issue.

I can merge only I will be sure that this can happen in canonical git where there are what you called orphaned loose objects. I'm not expert in git internals so I'm not sure if this is something that can normally happen in git. I would expect that You would need to create a commit remove it and create again identifical commit for the OID to be the same as the one that can be garbage collected. This is only my assumption. I have no idea how git create a hash. I would expect that it can use the timestamp of the time when a commit is created to create a hash. This means that it's not possible to create two identical OID when one is loose.

I need to check if `git commit --amend --no-edit` creates the same hash. If not then you have a different problem. The issue is with either the library or your code.

**Comment by jcubic** [comment]
So the canonical git the --amend change the hash even if there are no code changes.

@willstott101 What I would try to do is to search the code for the place where you can discard the commits and create a new one. I would also check the library how the hashes are created and if they use timestamps or only the other content.

Note that this project is community-driven, the original author left the project, which means that I as a maintainer don't write code myself. So to fix the issue you will need to read the code and debug it yourself.

**Comment by willstott101** [comment]
I appreciate that this is a community project and that the onus for proof is on me.

My opinion is that this specific command should behave the way git does in this situation, so the proof that git does not fail when we have duplicate objects is proof enough. I can update my code to reduce the chance of a race condition creating a duplicate object, but tbh I don't think it's 100% avoidable. And a later `git gc` would slurp them up and tidy up anyway.

Seeing these duplicate objects doesn't seem like an error to me, so I am reluctant to try and reproduce the issue in what would basically amount to a scripted stress test. But I can try and make one if we feel there needs to be proof that it happens... I suppose I wonder if the goal is to prove that duplicate oebjcts can happen, or to try and find a potential improvement elsewhere in the library to make it less likely... either way I feel my MR should be merged.

**Comment by mojavelinux** [comment]
> I can try and make one if we feel there needs to be proof that it happens

As someone observing this discussion, I would think that the only proof that's needed is a citation from the canonical git documentation or technical specs that this can happen. If the project claims it can happen, that should be sufficient, and sufficient reason to address the condition in isomorphic-git.

**Comment by mojavelinux** [comment]
To me, this statement in the git documentation suggests that this scenario is possible:

https://git-scm.com/docs/git-maintenance#Documentation/git-maintenance.txt-loose-objects

Why would git provide such a check if it weren't possible? We could ask a git maintainer to clarify, if we feel that clarification is needed.

**Comment by jcubic** [comment]
@mojavelinux no, that's good proof. Thanks for taking the time to look into the docs.
