### ISSUE TITLE
with this error message: Index file is empty (.git/index)

### ISSUE THREAD

**Issue by KiranMaddi1215** [isomorphic-git/isomorphic-git#1791]
I am using Visual code for Apex development. While running sfdx commands to push the code. I see the following error

Error (1): An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)

Can someone help me understand whats going on and what could fix this

**Comment by jcubic** [comment]
I was reported multiple times, this is the error in salesforce extensions you're using. Please see this issue https://github.com/forcedotcom/cli/issues/2194
