### ISSUE TITLE
Metadata API request failed

### ISSUE THREAD

**Issue by biswajith-s-pso-maxval** [isomorphic-git/isomorphic-git#1792]
Metadata API request failed: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 0000000000000000000000000000000000000000 but saw d53b3073ecbd53fda80819e011f3b2c9c8506d14

**Comment by jcubic** [comment]
What it "Metadata API request"? This looks like a bug in the tool you're using.

**Comment by CodeMan82** [comment]
10:50:20.641 Starting SFDX: Retrieve Source from Org

Metadata API request failed: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 000081a40000000000000000000000cb74e8f9db but saw f85b74bd3c3bdf2e123ae6586f32d4e88152528f
