### ISSUE TITLE
SFDX - Unable to deploy Source to Org

### ISSUE THREAD

**Issue by SamarthRastogi1** [isomorphic-git/isomorphic-git#1793]
Starting SFDX: Deploy Source to Org

An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 6d61696e2f64656661756c742f67726f7570732f but saw 517dbe51cbcaa94ed45e87efb4d8ee655bd23798

**Comment by jcubic** [comment]
I was reported multiple times, this is the error in salesforce extensions you're using. Please see this issue https://github.com/forcedotcom/cli/issues/2194
