### ISSUE TITLE
Please solve this issue

### ISSUE THREAD

**Issue by abidhal216** [isomorphic-git/isomorphic-git#1794]
Starting SFDX: Deploy Source to Org

An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 9638fba1090cf0cbe3fe23e6005a666f7263652d but saw 77e4edc256a517f1d2d472ddf2da216bb3298ee6
19:02:11.64 Starting SFDX: Deploy Source to Org

An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 9638fba1090cf0cbe3fe23e6005a666f7263652d but saw 77e4edc256a517f1d2d472ddf2da216bb3298ee6
19:09:37.994 Starting SFDX: Retrieve Source from Org

Already remove everything and install it again but it's worked for 3 to 4 days and same issue.

**Comment by etaussig** [comment]
I have the same problem.  Was working for about 4 days and then I get this error again

Error (1): An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected  but saw da39a3ee5e6b4b0d3255bfef95601890afd80709
Loading source tracking information... done

**Comment by jcubic** [comment]
I was reported multiple times, this is the error in salesforce extensions you're using. Please see this issue https://github.com/forcedotcom/cli/issues/2194
