### ISSUE TITLE
Invalid checksum in GitIndex buffer

### ISSUE THREAD

**Issue by lendontumilap** [isomorphic-git/isomorphic-git#1800]
An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected  but saw da39a3ee5e6b4b0d3255bfef95601890afd80709

![Screenshot 2023-08-16 080830](https://github.com/isomorphic-git/isomorphic-git/assets/99643847/614826e1-2efc-4b8a-92b8-5c6556cd91a4)

**Comment by jcubic** [comment]
Please report this to Salesforce extension.
