### ISSUE TITLE
Metadata API request failed: An internal error caused this command to fail. Invalid checksum in GitIndex buffer: expected 73734a757374696669636174696f6e2e6669656c but saw de58e2b378a264511123e95ac7158dc107a09e26

### ISSUE THREAD

**Issue by MilesHummet** [isomorphic-git/isomorphic-git#1801]
Please be sure to mention:
Using Visual Studio Code. Attempt to Retrieve from Org/package.xml returns the following error output: 

Metadata API request failed: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 73734a757374696669636174696f6e2e6669656c but saw de58e2b378a264511123e95ac7158dc107a09e26

**Comment by jcubic** [comment]
Do you use Salceforce extension?

**Comment by MilesHummet** [comment]
> Do you use Salceforce extension?

Yes. Salesforce SLI Extension

**Comment by MilesHummet** [comment]
> Had the same issue, it was fixed when I deleted the index file after searching for it, the file is mentioned as: .git/index

Thank you. I will try to go with this path etc.

**Comment by jcubic** [comment]
@MilesHummet try to report this to the salesforce extension, they are using the isomorphic-git library and this is their problem. That they probably fixed a few months ago.

Check https://github.com/forcedotcom/cli/issues/2194

**Comment by jcubic** [comment]
Try reporting this to project [forcedotcom/cli](https://github.com/forcedotcom/cli/issues).

I know that the error says to report it here, but the bug is in the Salesforce extension, nothing we can do about the bug in that project.
