### ISSUE TITLE
 Invalid checksum in GitIndex buffer: expected 61756c742f7374617469637265736f7572636573 but saw 527712dee60f0d31e260887c55bf63b621e7f505

### ISSUE THREAD

**Issue by karenpereira98** [isomorphic-git/isomorphic-git#1803]

**Comment by jcubic** [comment]
Try reporting this to project [forcedotcom/cli](https://github.com/forcedotcom/cli/issues).

I know that the error says to report it here, but the bug is in the Salesforce extension, nothing we can do about the bug in that project.
