### ISSUE TITLE
Invalid checksum in GitIndex buffer: expected 645472616e736c6174696f6e2d6d6574612e786d but saw c73cda78db47a8cb9194aecaadb49cd42ac9abf8

### ISSUE THREAD

**Issue by MadhuSudhan-M** [isomorphic-git/isomorphic-git#1804]
Error when trying to deploy code from VS Code to Salesforce Org.

**Comment by jcubic** [comment]
See https://github.com/forcedotcom/cli/issues/2194

**Comment by jcubic** [comment]
Try reporting this to project [forcedotcom/cli](https://github.com/forcedotcom/cli/issues).

I know that the error says to report it here, but the bug is in the Salesforce extension, nothing we can do about the bug in that project.
