### ISSUE TITLE
Invalid checksum in GitIndex buffer

### ISSUE THREAD

**Issue by yuliusmj** [isomorphic-git/isomorphic-git#1805]
Please be sure to mention:
- whether you are using Node or the Browser
- how you are using it (if you are using a bundler what bundler; if you are using a `<script>` tag what CDN URL)
 Metadata API request failed: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected  but saw da39a3ee5e6b4b0d3255bfef95601890afd80709

**Comment by cristiand391** [comment]
Hi @yuliusmj, is this an issue with the Salesforce CLI? if so, please close this one and log a bug report here: https://github.com/isomorphic-git/isomorphic-git/issues/new/choose

**Comment by jcubic** [comment]
This is an issue with Salesforce CLI, Even though the error message says to report the issue to this library you should create an issue here:

https://github.com/forcedotcom/cli/issues/new/choose

Search if there are no issues already related to the problem. There should be a lot of them.
