### ISSUE TITLE
Index file is empty (.git/index)

### ISSUE THREAD

**Issue by tgraham412** [isomorphic-git/isomorphic-git#1807]
When trying to retrieve or deploy to a Salesforce Sandbox in VSCode I get the error: "An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)". I'm able to 'Diff File Against an Org' but cannot seem to deploy or retrieve.

The only way I've found to temporarily fix this is to create an entirely new Project in VSCode. But within a few days I'm receiving the error again. Any ideas on how to fix this error?

**Comment by cristiand391** [comment]
Hey @tgraham412, sorry for the confusion but if you experience any Salesforce CLI/vscode extensions issue please report an issue here: https://github.com/forcedotcom/cli/issues

this repo is just for the library we use in the CLI.
