### ISSUE TITLE
An internal error caused this command to fail.

### ISSUE THREAD

**Issue by CodeMan82** [isomorphic-git/isomorphic-git#1808]
Using Salesforce CLI Tool

09:08:15.440 Starting SFDX: Deploy Source to Org
An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 000081a40000000000000000000000df90e515f1 but saw 1d997869e11cb1a1bcdf974ddff4ed2a66950e2f

**Comment by cristiand391** [comment]
Hi @CodeMan82, could you please close this issue and open a new one in the Salesforce CLI repo?
https://github.com/forcedotcom/cli/issues/new/choose

unfortunately the CLI is just re-throwing this err from the isomorphic-git library, but we monitor issues in our own repo.
