### ISSUE TITLE
Invalid checksum in GitIndex buffer: expected 64ace3d11c38fb112242e89900006c50000081a4 but saw a2a4991f547c4ed4d6510b61e434575f58156924

### ISSUE THREAD

**Issue by Pravinprak** [isomorphic-git/isomorphic-git#1809]

**Comment by cristiand391** [comment]
Hi @Pravinprak , is this an issue with the Salesforce CLI? if so, please close this one and log a bug report here:
https://github.com/forcedotcom/cli/issues

**Comment by jcubic** [comment]
This is an issue with Salesforce CLI, Even though the error message says to report the issue to this library you should create an issue here:

https://github.com/forcedotcom/cli/issues/new/choose

Search if there are no issues already related to the problem. There should be a lot of them.
