### ISSUE TITLE
Index file is empty (.git/index)

### ISSUE THREAD

**Issue by Weplus3com** [isomorphic-git/isomorphic-git#1810]
Please be sure to mention:
- whether you are using Node or the Browser
- how you are using it (if you are using a bundler what bundler; if you are using a `<script>` tag what CDN URL)
Index file is empty (.git/index)

**Comment by jcubic** [comment]
Are you using Salesforce CLI?

**Comment by FabricioGarcia-OSF** [comment]
Same error here, using Salesforce CLI on vscode when try to deploy a new class to the sandbox

"An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)"

**Comment by jcubic** [comment]
If this is an issue with Salesforce CLI you should report the issue there, even the error message says it's isomorphic-git, they just don't handle the error properly:

https://github.com/forcedotcom/cli/issues/new/choose

Before creating an issue please search if there are no similar issues already.
