### ISSUE TITLE
Invalid dircache magic file number

### ISSUE THREAD

**Issue by maheshnagireddy** [isomorphic-git/isomorphic-git#1811]
I am using Node.

An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid dircache magic file number:

**Comment by maheshnagireddy** [comment]
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/isomorphic-git/isomorphic-git/files/12461212/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

**Comment by jcubic** [comment]
Please create an issue in https://github.com/forcedotcom/cli/issues/new/choose repo.
The error unfortunately says to report the issue here, but the error in fact came from salesforce CLI but it's not handled properly.

**Comment by Qu4tro** [comment]
I suggest this issue to be closed @jcubic
