### ISSUE TITLE
Unable to activate the Apex Language Server - undefined

### ISSUE THREAD

**Issue by VeranikaKaraliova** [isomorphic-git/isomorphic-git#1812]
I try to deploy changes to my org, but receive the error:

Invalid checksum in GitIndex buffer: expected 6574612e786d6c006310b3de305515146310b3de but saw c3f050e73ee813fadfbbd83a79c530968050ac53

**Comment by jcubic** [comment]
Can you define more context? Do you use salesforce CLI?

**Comment by VeranikaKaraliova** [comment]
yes, I use salesforce CLI.
I receive error when try to deploy changes through the graphical interface (the Visual Studio Code interface : ) or directly in the terminal.
![image](https://github.com/isomorphic-git/isomorphic-git/assets/64038365/0a3d5a62-8504-4a19-a2cb-1806810b115f)

**Comment by jcubic** [comment]
This is a bug in SalesForce CLI you should report the issue here:
https://github.com/forcedotcom/cli/issues/new/choose
