### ISSUE TITLE
Not able to deploy to salesforce

### ISSUE THREAD

**Issue by rajatjain37** [isomorphic-git/isomorphic-git#1813]
Trying to deploy an LWC component from VS code to SF sandbox org, and getting the below error:

Invalid checksum in GitIndex buffer: expected 0c028086000edc8e000081a40000000000000000 but saw e2303cad0e3708ae3b830402f14fe8a28703f1b6

**Comment by jcubic** [comment]
If this is the issue with SalesForce CLI, then please open the issue here:

https://github.com/forcedotcom/cli/issues/new/choose

Unfortunately, the CLI is just re-throwing this err from the isomorphic-git library, but they monitor issues in their own repo.

**Comment by Arvindsharma17** [comment]
i have resolved this issue. simply just create a new project file. don't retrieve components in one ago. just retrieve components one by one. it worked for me for deployement also

**Comment by jcubic** [comment]
@Arvindsharma17 you should add this comment to one the issues in [forcedotcom/cli](https://github.com/forcedotcom/cli/issues/new/choose), it may help resolve the issue.
