### ISSUE TITLE
Invalid checksum

### ISSUE THREAD

**Issue by DaniGC95** [isomorphic-git/isomorphic-git#1814]
Hi!
Since a few days, I have had the same error in Visual Studio when I try to develop or retrieve some element from Salesforce. 
Error: 
11:13:49.405 Starting SFDX: Retrieve Source from Org

Metadata API request failed: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 64f599d435d5a30f64f599d435d5a30ff2c52cee but saw 74fbcab467582f47bde395427bb4d412a9b8b76b
![gitError](https://github.com/isomorphic-git/isomorphic-git/assets/104512176/694f77ac-1e5b-498d-b31d-1b8627d4f4f1)

To solve this, I have to delete the local project and create it again, but It's a bit heavy to do it every day.

I have tried to authorize again the org, close the project and open it again, update extensions...

Can you help please?

Thanks!

**Comment by jcubic** [comment]
This is an issue with Salesforce CLI. You should return the issue here:
https://github.com/forcedotcom/cli/issues/new/choose

But first find if the issue already exists.

**Comment by DaniGC95** [comment]
Thanks @jcubic

**Comment by Arvindsharma17** [comment]
i have resolved this issue. simply just create a new project file. don't retrieve components in one ago. just retrieve components one by one. it worked for me for deployement also
