### ISSUE TITLE
Invalid checksum in GitIndex buffer

### ISSUE THREAD

**Issue by Kums201193** [isomorphic-git/isomorphic-git#1815]
I am Tried to Retrieve the Components from Org I got the below Error Message in VS Code. I am not sure what is the issue request you to help me out in fixing this.

Metadata API request failed: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 61756c742f7374617469637265736f7572636573 but saw cd39c6bdd7380e8c41017ab907a7d6e1f2523190

**Comment by Arvindsharma17** [comment]
i have resolved this issue. simply just create a new project file. don't retrieve components in one ago. just retrieve components one by one. it worked for me for deployement also

**Comment by djtoohey** [comment]
I'll just add what worked for me for anyone else who comes across this issue, 
I deleted the local copy of the repo I was pushing from, re cloned it, pushed with no issues. 
In hindsight git gc could have probably been all that was needed.

**Comment by jcubic** [comment]
This is issue with Salesforce CLI, even that the error message say to report the issue to this library you should create an issue here:

https://github.com/forcedotcom/cli/issues/new/choose

Search if there are no issues already related to the problem. There should be a lot of them.
