### ISSUE TITLE
Invalid dircache magic file number: O�|f

### ISSUE THREAD

**Issue by SaruPaduchuri** [isomorphic-git/isomorphic-git#1816]
When trying retrieve code from Org in VS code getting this error please help
<img width="662" alt="Screenshot 2023-09-07 185212" src="https://github.com/isomorphic-git/isomorphic-git/assets/144352103/efa4916f-773e-45c4-9d5d-2e1b6d3edab8">

**Comment by jcubic** [comment]
This is an issue with Salesforce CLI. You can report the issue there:

https://github.com/forcedotcom/cli/issues/new/choose

**Comment by Qu4tro** [comment]
I suggest this issue to be closed @jcubic

**Comment by jcubic** [comment]
@Qu4tro thanks for checking the open issues.
