### ISSUE TITLE
Index file is empty

### ISSUE THREAD

**Issue by msteinercrmfirm** [isomorphic-git/isomorphic-git#1817]
Please be sure to mention:
- whether you are using Node or the Browser
- how you are using it (if you are using a bundler what bundler; if you are using a `<script>` tag what CDN URL)

Trying to deploy metadata from VS Code to Salesforce.  Getting the following error...
An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)
12:24:13.362 Starting SFDX: Deploy Source to Org

Have reinstalled Salesforce CLI extensions

**Comment by jcubic** [comment]
This is issue with Salesforce CLI, even that the error message say to report the issue to this library you should create an issue here:

https://github.com/forcedotcom/cli/issues/new/choose

Search if there are no issues already related to the problem. There should be a lot of them.
