### ISSUE TITLE
Index file is empty (.git/index)

### ISSUE THREAD

**Issue by sfdevyogeshmiyani** [isomorphic-git/isomorphic-git#1818]
Please be sure to mention:
- I am using VS Code for Salesforce project and getting below while retrieving metadatas.
Metadata API request failed: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)

![image](https://github.com/isomorphic-git/isomorphic-git/assets/49476386/d74cbace-6a48-4157-b3b7-455ee7cedf97)

**Comment by jcubic** [comment]
This is issue with Salesforce CLI, even that the error message say to report the issue to this library you should create an issue here:

https://github.com/forcedotcom/cli/issues/new/choose

Search if there are no issues already related to the problem. There should be a lot of them.
