### ISSUE TITLE
Java runtime could not be located. Set one using the salesforcedx-vscode-apex.java.home VS Code setting. For more information, go to Set Your Java Version.

### ISSUE THREAD

**Issue by Leo-username1234** [isomorphic-git/isomorphic-git#1820]
Please can you help me on the VS code error below - I have all of the sudden started receiving this issue not sure how to fix.
Adding direclty the error received while deploying source to org

Java runtime could not be located. Set one using the salesforcedx-vscode-apex.java.home VS Code setting. For more information, go to [Set Your Java Version](https://developer.salesforce.com/tools/vscode/en/vscode-desktop/java-setup).

An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)

**Comment by cristiand391** [comment]
Hey @Leo-username1234 , this seems to be an issue with salesforce vscode extensions, please close this issue and open a new one in this repo:
https://github.com/forcedotcom/salesforcedx-vscode/issues/
