### ISSUE TITLE
Index file is empty (.git/index)

### ISSUE THREAD

**Issue by jsetienr** [isomorphic-git/isomorphic-git#1821]
While I try to deploy any file via _sfdx_ with VSCode to my Salesforce ORG, I find an issue since yesterday with this description:

```
12:17:19.226 Starting SFDX: Deploy Source to Org

An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)
```

I deploy my components from VSCode using SFDX with right click -> _SFDX: Deploy source to ORG_ .
I already try to close VSCode, logout from Salesforce linked ORG, updating Salesforce CLI... other commands works fine as usually f.ex.: 
- _SFDX: Diff file against ORG_ 
-  _SFDX: Execute Anonymous Apex with Editor Contents_ works fine as usually.

**Comment by sqlahmansour** [comment]
I encountered the same issue today... SF Command lines does not seem to work, SFDX does...

**Comment by sqlahmansour** [comment]
Hey again @jsetienr,
I managed to fix the issue by deleting both .sf and .sfdx folders and then on the command palette run : Developer: Reload Window.

I hope it fixes your issue.

Also, make sure to have latest SF plugins updates on visual code.

**Comment by jsetienr** [comment]
Thank you so much @sqlahmansour ! 
I followed your advice and it worked perfectly.
