### ISSUE TITLE
An internal error caused this command to fail.

### ISSUE THREAD

**Issue by SiddharthNaikap** [isomorphic-git/isomorphic-git#1823]
Facing Below Error while running SFDX Command : 

SFDX: Deploy Source to Org

ERROR:
#########
An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 650406e1232ce8d7650406e1232ce8d7e2f191ea but saw 0b39c7961cebb26ba9e8f34a9afc6d0fcb3198d0
##################

Kindly check and assist.

**Comment by jcubic** [comment]
This is issue with Salesforce CLI, even that the error message say to report the issue to this library you should create an issue here:

https://github.com/forcedotcom/cli/issues/new/choose

Search if there are no issues already related to the problem. There should be a lot of them.
