### ISSUE TITLE
Starting SFDX: Retrieve Source from Org

### ISSUE THREAD

**Issue by JanaBeCe** [isomorphic-git/isomorphic-git#1824]
Metadata API request failed: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)

**Comment by jcubic** [comment]
This is an issue with Salesforce CLI, even though the error message says to report the issue to this library you should create an issue here:

https://github.com/forcedotcom/cli/issues/new/choose

Search if there are no issues already related to the problem. There should be a lot of them.

**Comment by bjconover** [comment]
When I was at Dreamforce I spoke with one of the representatives there about this issue. Salesforce creates a local git index in your project directory that can get corrupted. They told me to locate that file and delete it and reattempt the pull/send and it will be regenerated. If you go to .sf\orgs\(Your Org Number)\localSourceTracking there is an index file in there. Either delete or rename that file to something else and reattempt the process again. That fixed my issue.
