### ISSUE TITLE
Index file is empty (.git/index)

### ISSUE THREAD

**Issue by thierrytrouin** [isomorphic-git/isomorphic-git#1825]
Hi Team,

I have an error with a VS Code Projet.

**The message is :**
Metadata API request failed: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)

This message occurred when I "Retrieve Source from Org" or "Deploy Source to Org" but "Diff File Against Org" command is working.

**My sytem configuration is the following :** 
OS : Windows 10 64bits
VS Code : 1.82.2
sfdx : 7.193.2 

The project has a local repository only

Many thanks for your help,
Thierry

**Comment by cristiand391** [comment]
Hi @thierrytrouin , for Salesforce vscode extensions please open an issue here: https://github.com/forcedotcom/salesforcedx-vscode

**Comment by thierrytrouin** [comment]
Hi @cristiand391 
Thank you for your reply.
I juste posted the message on the git "forcedotcom" but the message refers to this git repository.

**Comment by thierrytrouin** [comment]
Ok, sorry, I made a translation error. 
As shown in the link, the solution works I deleted the .sfdx folder.
Many thanks for your help
