### ISSUE TITLE
Getting error while retrieving source from org in VS code

### ISSUE THREAD

**Issue by PreetiSingh13** [isomorphic-git/isomorphic-git#1826]
getting this error --> **Index file is empty (.git/index)**
while retrieving or deploying source from org in VS code

**Comment by jcubic** [comment]
This is an issue with Salesforce CLI, even though the error message says to report the issue to this library you should create an issue here:

https://github.com/forcedotcom/cli/issues/new/choose

Search if there are no issues already related to the problem. There should be a lot of them.
