### ISSUE TITLE
Metadata API request failed

### ISSUE THREAD

**Issue by byeedeakin** [isomorphic-git/isomorphic-git#1832]
I'm using Visual Code to "Retrieve Source from Org' for Salesforce and encountered the following error:

Metadata API request failed: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: 
Invalid checksum in GitIndex buffer: expected 70706f7274756e6974792f6669656c64732f6e70 but saw eef210f987271630b352896cee3f71995e74ee79

**Comment by jcubic** [comment]
please search for issues before opening a new one, there are a bunch of duplicates.
This is an issue with salesforce cli/vscode extensions, see [forcedotcom/cli](https://github.com/forcedotcom/cli).
