### ISSUE TITLE
Metadata API request failed: An internal error caused this command to fail. 

### ISSUE THREAD

**Issue by maheshbabu9999** [isomorphic-git/isomorphic-git#1834]
Metadata API request failed: An internal error caused this command to fail. while retrieving code from sandbox how to resolve this issue..

**Comment by jcubic** [comment]
Can you give any context as to where this error happened? You will not get any help if you don't help us understand the problem.

**Comment by jcubic** [comment]
Can you look at this issue #1832?

**Comment by cristiand391** [comment]
Thanks jcubic.

As mentioned, we fixed in latest salesforce CLI and vscode extensions so it's ok if you want to close all these issues (again, sorry for all the noise) . I left a link in most of them to my comment 👍🏼
