### ISSUE TITLE
Configurable fs

### ISSUE THREAD

**Issue by bajrangCoder** [isomorphic-git/isomorphic-git#1835]
Is there any way to configure any type of `fs client` to isomorphic-git?

As in my case I have to use `cordova-plugin-file` for fs stuffs but isomorphic-git only supports nodejs like fs only(i guess)

I have to integrate isomorphic-git for git client in this [app](https://github.com/deadlyjack/Acode) and here is it's [fs](https://github.com/deadlyjack/Acode/blob/main/src/fileSystem/index.js) which uses `cordova file` , sdcard plugin etc.

Any solution will be appreciated 🤗

**Comment by jcubic** [comment]
I think the easiest way is to look at lightningFS library that implements fs module that can be used in web browser.
But to have custom fs you need to implement custom backend.

**Comment by bajrangCoder** [comment]
Ok Thanks for your response!
Can I get some hints or any sample of implementing custom backed? As on lightningFS library only mention about `backend` but there is no any docs or example about it

**Comment by jcubic** [comment]
It seems there is an option backend:

https://github.com/isomorphic-git/lightning-fs/blob/main/src/PromisifiedFS.js#L82C29-L82C36

But it's not in TypeScript definition. If you don't use TypeScript you can try it. And if you use TypeScript maybe you will need to put `as any` somewhere.

**Comment by bajrangCoder** [comment]
Yeah there are some issues in lightning fs typings declaration file as it makes db option required. For now I have modified it and tested `fs.promises.readdir()`and it's worked after doing some bypassings.

And I want to ask that how can I overide the default function that disturb the filepath as in my case when I pass these type of paths : `content://com.externalstorage....../` then lighting fs convert this path to this : `./content:/com......` 
As it will be needed in any case for my use case it's not required 

Also noticed one error that occurs when ever I start my app but it doesn't the affect any thing , here is the screenshot of error:

![Screenshot_20231026-153617~2](https://github.com/isomorphic-git/isomorphic-git/assets/71929976/d0b1d285-cd6b-45c9-be67-e4c9330fb7b6)

> **Note**
> I initialise the lighting fs in constructor like this 👇
> ```javascript
> constructor() {
>   const customBackend = new FsBackend();
>   this.fs = new FS();
>   this.fs.promises.init("myfs", { backend: customBackend });
>}
>```

**Comment by jcubic** [comment]
Don't call the init function it's an internal method.

**Comment by bajrangCoder** [comment]
Ok but what about this one 👇

> And I want to ask that how can I overide the default function that disturb the filepath as in my case when I pass these type of paths : content://com.externalstorage....../ then lighting fs convert this path to this : ./content:/com......
As it will be needed in any case for my use case it's not required

**Comment by jcubic** [comment]
I think that it will be much simpler to just implement your own fs and all the methods that are required. But if you would like to use lightning-fs you will need to fork it and modify to not normalize the path (or whatever function it used for paths).

**Comment by bajrangCoder** [comment]
Ok
