### ISSUE TITLE
Missing command: `git merge-base`

### ISSUE THREAD

**Issue by Pandapip1** [isomorphic-git/isomorphic-git#1837]
I would love a plain nodejs implementation of `git merge-base`. At the moment, I have to call the git binary to get the result, since I can't find any reliable way to do it in node myself.

**Comment by jcubic** [comment]
This project is community-driven, which means that if you do not implement this feature, probably no one will do this for you, unless you find someone and you will pay him.

**Comment by Pandapip1** [comment]
> This project is community-driven, which means that if you do not implement this feature, probably no one will do this for you, unless you find someone and you will pay him.

That's fine! Before I put together a PR, can I confirm that this project is actively maintained and that proposed changes will be reviewed?

**Comment by jcubic** [comment]
Yes, it's maintained but the original author left the project, so the only changes are done by individual contributors like you.
