### ISSUE TITLE
No shallow directory error

### ISSUE THREAD

**Issue by ppppqp** [isomorphic-git/isomorphic-git#1850]
Hi, I am using isomorphic git for my existing repo (not cloned) and getting this error. Any work around?
Using node
```
ENOENT: No such file or directory
   errno: -2
 syscall: "open"
   path: "/.git/shallow"

✗ Git > construct repo [4.89ms]
```

**Comment by jcubic** [comment]
Sorry, I have no idea. Do you have a full clone or a shallow one?

**Comment by ppppqp** [comment]
I did not clone but just `git init`.

**Comment by ppppqp** [comment]
nvm, it's `bun.js` issue. It works fine with node.

**Comment by iulo** [comment]
@ppppqp same issue, any guidance on bun-related issues? Thanks

**Comment by jcubic** [comment]
@iulo do you have a simple reproduction?
