### ISSUE TITLE
Pushing returning 401 Error: No Anonymous Write Access

### ISSUE THREAD

**Issue by Notplayingallday383** [isomorphic-git/isomorphic-git#1856]
Hi, I have currently implemented git into my webOS Project and for some reason uppon pushing a commit it pushes the commit but doesn't push the code/changes just the commit text. I checked the console and saw it was returning a 401 Unathorized and uppon clicking the request to see whats up with it says: No Anonymous Write Access. I gave the token read and write for repositories and alot of other stuff and it still didn't work. The Network request can be found in the screenshot below: ![image](https://github.com/isomorphic-git/isomorphic-git/assets/72810050/1f372ee7-8f37-468c-8416-08d193a75f40)

Debug information
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
- Defining using this script: 
   <script type="module">
      import http from '/assets/libs/http.min.js'
      import git from 'https://cdn.jsdelivr.net/npm/isomorphic-git@1.24.5/+esm';
      window.gitfetch = git
      window.http = http
    </script>

**Comment by jcubic** [comment]
Can you share your code? The screenshot of the error doesn't say anything.

**Comment by Notplayingallday383** [comment]
Sure this is how I did it for the `push` command If you want the rest of the script I can send that too.
```js
    if (!args[1]) {
                displayOutput("Usage: git push <directory>");
                createNewCommandInput();
                return;
            }
            const dirName = args[1];
            const targetDir = `/home/${dirName}`;
            try {
                const result = await window.parent.tb.dialog.Auth({
                    title: "GitHub Authentication",
                    onOk: async ({ username, password }) => {
                        try {
                            const gitfetchResult = await gitfetch.push({
                                fs: window.parent.Filer.fs,
                                http: http,
                                dir: targetDir,
                                corsProxy: 'https://cors.isomorphic-git.org',
                                remote: 'origin',
                                force: false,
                                onMessage: (e) => {
                                    displayOutput(e);
                                },
                                author: {
                                    name: user,
                                    email: `${user}@terbiumux.net`
                                },
                                onAuth: () => {
                                    return { username, password };
                                }
                            });
                            displayOutput(JSON.stringify(gitfetchResult, null, 2));
                        } catch (error) {
                            displayError(`Error: ${error.message}`);
                        } finally {
                            createNewCommandInput();
                        }
                    },
                    onCancel: () => {
                        displayError("GitHub authentication canceled");
                        createNewCommandInput();
                    }
                });
            } catch (error) {
                displayError(`Error: ${error.message}`);
                createNewCommandInput();
            }
```

**Comment by jcubic** [comment]
But you know that password property needs to be a TOKEN created on GitHub with repository access permission? It's named password but it needs to be a token. GitHub doesn't allow to use of passwords anymore.

I'm not sure if this is just something that isomorphic-git uses or is in fact GitHub thing to use TOKEN as a password.

**Comment by Notplayingallday383** [comment]
Yes I was authenticating with my token and like It basically creates commits like this without any data: https://github.com/Notplayingallday383/tb-git-test/commit/01ba646bedb3995afcce53fa65e4731c3b111d3a

**Comment by jcubic** [comment]
Can you share all the code exactly what you do. You need to run git.add and git.commit before you push the changes.

**Comment by Notplayingallday383** [comment]
> Can you share all the code exactly what you do. You need to run git.add and git.commit before you push the changes.

Oh I see I tried it with git add and it worked so thank you for your help and sorry for making this issue since it seemed like a misunderstanding problem on my end
