### ISSUE TITLE
not respecting server capabilities ( report-status )

### ISSUE THREAD

**Issue by skadefro** [isomorphic-git/isomorphic-git#1866]
If server does NOT send report-status. isomorphic-git correctly also leave it out when doing a request.
But still fails with
```
Expected "unpack ok" or "unpack [error message]" but received "".
```
at https://github.com/isomorphic-git/isomorphic-git/blob/79a38e017653a4dfe3b93e390bf3ffa73db42e82/src/wire/parseReceivePackResponse.js#L21

This check should be skipped when not using report-status

**Comment by jcubic** [comment]
I'm not sure, but if you can create failing test that pass when the code if fixed. I'm happy to merge your PR.

**Comment by skadefro** [comment]
I just added reporting support in my client, closing since no one seem to want to fix it.

**Comment by jcubic** [comment]
You didn't create a PR.

**Comment by skadefro** [comment]
Yes, I reported an issue, not a solution. I tried giving information about where I think the issue is, but have no idea how to fix it.
