### ISSUE TITLE
Race condition makes it possible for a ref to be resolved to an empty string while it's in the middle of being updated

### ISSUE THREAD

**Issue by alexvy86** [isomorphic-git/isomorphic-git#1881]
We're encountering this problem while using isomorphic-git in a Node 18 environment.

I don't have a good minimal reproduction yet but can reproduce it more or less consistently with a big suite of tests of https://github.com/microsoft/FluidFramework (I'm part of the team working on it).

Specifically, a call to [`GitRefManager.writeRef()`](https://github.com/isomorphic-git/isomorphic-git/blob/79a38e017653a4dfe3b93e390bf3ffa73db42e82/src/managers/GitRefManager.js#L137) that happens while a call to [`GitRefManager.resolve()`](https://github.com/isomorphic-git/isomorphic-git/blob/79a38e017653a4dfe3b93e390bf3ffa73db42e82/src/managers/GitRefManager.js#L179) (for the same ref) is underway sometimes causes [this read](https://github.com/isomorphic-git/isomorphic-git/blob/79a38e017653a4dfe3b93e390bf3ffa73db42e82/src/managers/GitRefManager.js#L203) in the `resolve()` call to return an empty string if it happens around the same time as [this write](https://github.com/isomorphic-git/isomorphic-git/blob/79a38e017653a4dfe3b93e390bf3ffa73db42e82/src/managers/GitRefManager.js#L142). A second `resolve()` call immediately after returns the correct value written by the update, which supports the theory that it's a concurrency issue with the read and write.

I couldn't find docs that suggest this is a known possible issue or any guidance on how to handle this scenario, so I suspect it might be a bug.

Assuming it is, I can think of two solutions off the top of my head: stop using the Promise-based APIs in the provided `fs` module in favor of sync ones (which feels pretty drastic and probably a noticeable performance hit), or add locking around write/update operations (also a performance hit, maybe not as bad). Neither seems ideal, but the correctness problem seems like it needs to be addressed somehow...

**Comment by jcubic** [comment]
Do you want to contribute with a fix? I think that locking when writing/resolving refs is a good idea.

**Comment by alexvy86** [comment]
@jcubic [first draft is out](https://github.com/isomorphic-git/isomorphic-git/pull/1882). I think the general approach is there, I'd still like a bit of time to make sure I'm thinking everything through and determine if any cases don't need locking (like right now I skipped it for `listRefs` even though it uses the filesystem, since it only cares about listing the files, not looking at its contents).

**Comment by alexvy86** [comment]
For what it's worth, I tried this same approach only around `resolve()` and `writeRef()` directly in the node_modules of our project and it does look like it did the trick, I haven't seen errors so far running our test battery several times.

**Comment by alexvy86** [comment]
@jcubic the fix is fully ready for review.

**Comment by alexvy86** [comment]
@jcubic curious if you guys have some idea of when the next release will be done? Just to get an idea of when we'll be able to update our deps to get this fix.

**Comment by jcubic** [comment]
@alex-titarenko The project use semantic release that is part of CI/CD. So the release happen just after PR merge.

**Comment by alex-titarenko** [comment]
@jcubic I think you mentioned a wrong Alex. I supposed you wanted to include @alexvy86

**Comment by alexvy86** [comment]
Hmm did something go wrong with the release, then? The latest version in npm (1.25.6) is from Feb 18:

![image](https://github.com/isomorphic-git/isomorphic-git/assets/716334/70c63f87-34d9-47cf-a192-59e7c1988ea6)

**Comment by jcubic** [comment]
@alex-titarenko sorry, the GitHub autocomplete suggestion.

**Comment by jcubic** [comment]
It looks like it run [NPM build for two commits](https://dev.azure.com/isomorphic-git/isomorphic-git/_build/results?buildId=3363&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=d9b15392-e4ce-5e4c-0c8c-b69645229181), and it stopped on the first commit. Or maybe because the message didn't start with `fix:`.

Unfortunately, I can't fix this because the main branch is protected, and I can't rebase and push force on main. You need to wait for another PR to get merged.

Sorry, I totally forget about commit messages format.

**Comment by alexvy86** [comment]
Oh, oops. Would it work to merge some of the dependabot updates, changing the commit message to one that triggers a release? I see one for express and one for follow-redirects, which I know are meant to address CVEs.

If there's anything I can do on my end to help or expedite, let me know!

**Comment by jcubic** [comment]
Yes, I wanted to do that, but they all show failing CI.

**Comment by alexvy86** [comment]
It's only a dev dependency, but [this one for express] (https://github.com/isomorphic-git/isomorphic-git/pull/1891) seems to be passing unless I'm missing something.
