### ISSUE TITLE
Pushing an tag creates a remote ref to an unexisting branch

### ISSUE THREAD

**Issue by hhourani27** [isomorphic-git/isomorphic-git#1900]
I encountered a strange behavior when pushing an annotated tag. Upon investigation, I noticed that isomorphic-git's behavior is slightly different than Git's. I'm not sure it's a bug or may cause bugs down the line. I'm posting this question, to check with you if that might be the case.

### To reproduce
1. Clone an empty repository
2. Add a file, then git add and commit:  create a first commit on `main`
3. Push `main`
4. Create an annotated tag : `git tag -a v1.0 -m "add tag"`
5. Using isomorphic-git, push the tag
```
  const pushResult = await git.push({
    fs,
    http,
    dir: "<path to repo>",
    ref: "v1.0",
  });
```

**Result**
- On the Git server, the tag seems to be correctly pushed
- On my Git GUI (both VSCode's Git Graph and GitHub Desktop), a new "branch" is displayed called `origin/refs/tags/v1.0^{}` <= This is what ticked me off
![image](https://github.com/isomorphic-git/isomorphic-git/assets/61935766/7141dd41-c79b-4039-b9fd-5d9e09d8028f)
- I looked at the `.git` folder, and isomorphic-git created a new ref at `refs/remotes/origin/refs/tags/v1.0`

**Comparing with git push**
Instead of calling `git.push()`, I ran the command `git push origin v1.0`

- On my Git GUI, I did not see a new "tag"
![image](https://github.com/isomorphic-git/isomorphic-git/assets/61935766/b39829c5-d379-402a-be3b-dfcbe0786d0b)
- Git did not modify the `.git` folder, and did not add a new ref

Do you have an explanation for this discrepancy? Does it have any impact down the line with future commands? Would you recommend that I investigate further isomorphic-git's code?

Notes
- I am using isomorphic-git 1.25.7 on Node
- My Git version is 2.41.0.windows.1

**Comment by jcubic** [comment]
I have no idea what to answer. But if you want to contribute and change this behavior to make it work like canonical git, you're welcome to do so.

**Comment by hhourani27** [comment]
My analysis : 
1. After pushing a branch ref, isomorphic-git updates the remote ref in `refs/remotes` (cf [line](https://github.com/isomorphic-git/isomorphic-git/blob/0aec2af492f5fda03742a4f2b3716848ac0e4c5d/src/commands/push.js#L288) ) <= Canonical Git does that too
2. Following the same logic, after pushing a tag, isomorphic-git inadvertently updates the tag ref in `refs/remotes`. However, Git [doesn't have remote tags](https://stackoverflow.com/a/22120725/471461) and `refs/remotes` never contains refs to remote tags.
3. It thus creates a ref in `refs/remotes/<remote>/refs/tags/<tag>`, which Git GUIs interpret as a remote branch ref.

I will try to do a PR to correct that
