### ISSUE TITLE
StatusMatrix results are different on Windows and Linux

### ISSUE THREAD

**Issue by jayree** [isomorphic-git/isomorphic-git#1904]
I recently discovered that the results of statusMatrix are different on Windows and Linux.

`unmodified` files (`[1,1,1]`) are listed on windows as `modified, unstaged` (`[ 1, 2, 1 ]`)

See: https://github.com/jayree/iso-win-test/actions/runs/8846190106/job/24291562894

**Comment by jcubic** [comment]
Hi, thanks for the report. Do you want to investigate why this is happening and maybe provide a fix? This project is community driven and don't have the main author that write all the code. There are a few maintainers, but we mostly manage the repository.
