### ISSUE TITLE
Unchanged image/audio files being queued for commit with `git.add()`

### ISSUE THREAD

**Issue by marshmn** [isomorphic-git/isomorphic-git#1908]
isomorphic-git: 1.25.8
Node: 20.12.2

This behaviour seems to have changed since upgrading from 1.25.7.

I have a repository with a few modified files (all text files). I'm then running `git.add()`:
```typescript
await git.add({
    fs,
    dir: this.repoPath,
    filepath: '.'
});
```

My expectation is that this will add all modified files (only) for commit. However, it is adding not only those files but also some (perhaps all) image and audio files for commit also - even though these are unmodified.

Reverting to 1.25.7 returns to the expected behaviour.

**Comment by marshmn** [comment]
I've now created a self-containeed repo to demonstrate the issue: https://github.com/marshmn/isomorphic-git-1908

**Comment by jcubic** [comment]
This may be the issue with `\r` character stripping, @jayree can you take a look?
