### ISSUE TITLE
Add an FAQ with examples to the website

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#191]
Technically I guess I should have made this issue on the website repo?

https://github.com/isomorphic-git/isomorphic-git.github.io

- [x] How to add all untracked files with git.add? #187
- [x] Why is there no `default` export? @CMCDragonkai in the gitter channel
https://gitter.im/isomorphic-git/Lobby?at=5b16b21b160c567d1606154c

**Comment by jcubic** [comment]
Example for whole workflow would be nice:

* clone
* edit
* add
* commit
* push

**Comment by wmhilton** [comment]
@jcubic A lot of that is available on the website: https://isomorphic-git.github.io/docs/quickstart.html

But I should probably put some examples in the README too. Right now the README just links to the API docs, not the quickstart.html

**Comment by wmhilton** [comment]
Alright! Finally done in https://github.com/isomorphic-git/isomorphic-git.github.io/commit/cf6bb837c86f486b07418423bc87c7458f5506c7
