### ISSUE TITLE
NotFoundError: Could not find main.

### ISSUE THREAD

**Issue by ProofMrNick** [isomorphic-git/isomorphic-git#1930]
Got a 'NotFoundError: Could not find main.' error while trying to pull data from a remote GitHub server.
Here's the code (Node.js):

```
const dir = path.join(process.cwd(), 'filename');
git.init({ fs, dir: dir, defaultBranch: 'main' });
git.pull({
  fs,
  http,
  dir: dir,
  ref: 'main',
  singleBranch: true,
  author: {
      email: me@email.com',
      name: 'Me Me'
  },
});
```
Error I've got:
```
throw new NotFoundError(ref)
          ^

NotFoundError: Could not find main.
    at GitRefManager.expand (/home/runner/ejsv9TEST/node_modules/isomorphic-git/index.cjs:2035:11)
    at async _merge (/home/runner/ejsv9TEST/node_modules/isomorphic-git/index.cjs:9324:10)
    at async _pull (/home/runner/ejsv9TEST/node_modules/isomorphic-git/index.cjs:9529:5)
    at async Object.pull (/home/runner/ejsv9TEST/node_modules/isomorphic-git/index.cjs:11928:12) {
  caller: 'git.pull',
  code: 'NotFoundError',
  data: { what: 'main' }
}
```
I've cloned my GitHub repo beforehand, its clone is stored in ```dir```; on GitHub I've renamed default repo branch to ```main```.

**Comment by jcubic** [comment]
you're trying to initialize an empty repository and then pull. You need to have a remote to be able to pull.

**Comment by ProofMrNick** [comment]
I removed the ```git.init``` part of code but I still get the same error:
```
git.pull({
  fs,
  http,
  dir: dir,
  ref: 'main',
  singleBranch: true,
  author: {
      email: 'me@email.com',
      name: 'Me me'
  },
});
```

**Comment by jcubic** [comment]
can you show witch repo you cloned and how?

**Comment by ProofMrNick** [comment]
I cloned [this repo](https://github.com/ProofMrNick/database) with: 
```
const dir = path.join(process.cwd(), 'dbase');
git.clone({ fs, http, dir, url: 'https://github.com/ProofMrNick/database.git' }).then(console.log);
```
And I also want to make a little bit clearer what exactly I'm trying to do. I have a GitHub repo (link above) with one branch (that I renamed from ```master``` to ```main```) with one file, ```database.json```. The same I have on the Node server: ```dbase``` directory with one file, ```database.json```. I want to dynamically ```pull``` the most recent changes from GitHub to Node, edit the file, ```commit``` the changes and ```push``` it back to GitHub. What is the best way to do that (dynamically)?

**Comment by jcubic** [comment]
so the problem is that you run two async operation at the same time. You need to wait for clone to finish before you can call git.pull:

this is the code that works:

```javascript
const path = require('path');
const git = require("isomorphic-git");
const http = require("isomorphic-git/http/node");
const fs = require('fs');

const dir = path.join(process.cwd(), 'dbase');
(async () => {
    try {
        await git.clone({ fs, http, dir, url: 'https://github.com/ProofMrNick/database.git' });

        await git.pull({
            fs,
            http,
            url: 'https://github.com/ProofMrNick/database.git',
            dir: dir,
            ref: 'main',
            singleBranch: true,
            author: {
                email: 'me@email.com',
                name: 'Me me'
            },
        });
    } catch (e) {
        console.error(e.stack);
    }
})();
```

if you want to use promises you need to put pull into then handler.

**Comment by ProofMrNick** [comment]
It worked for me! Thank you very much for help!
