### ISSUE TITLE
Got error below while running a pipeline

### ISSUE THREAD

**Issue by GMlynda** [isomorphic-git/isomorphic-git#1931]
Error (1): An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: SHA check failed! Expected 26ac8de745ea874e3dcccd569aab8bdb7508a2d4, computed f75b07721a53832b21ed837c7589cb71b3a784c8

**Comment by jcubic** [comment]
what pipeline, what code are you running? You need to explain what you're doing. We don't have a crystal ball to read your mind.

**Comment by GMlynda** [comment]
This is what is in the pipeline for run-tests in GitLab:
#
# Run tests
#
run-tests:
    stage: run-tests
    script:
      #install dependency plugin
      - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/g-minds/SalesForce/sfdx-gm-plugin.git
      - cd sfdx-gm-plugin
      - npm install
      - cd ..
      - sfdx plugins:link sfdx-gm-plugin
      # Authenticate to the Dev Hub using the server key
      - sfdx auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile salesforce-ci/assets/server.key --username $SF_USERNAME --setdefaultdevhubusername --setalias HubOrg
      # Create scratch org and install depenencies
      - sfdx gm:org:create -a $SCRATCH_ORG_ALIAS -d 1 -r https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/g-minds/SalesForce/salesforce-mdapi-converted.git -w
      - sfdx force:org:display --targetusername $SCRATCH_ORG_ALIAS
      
      # Push source to scratch org (This is with source code, all files, etc)
      - sfdx force:source:push --targetusername $SCRATCH_ORG_ALIAS

      # Unit Testing
      - sfdx force:apex:test:run -y --targetusername $SCRATCH_ORG_ALIAS --wait 30 --resultformat human --codecoverage --testlevel $TESTLEVEL
      - sfdx force:org:delete -p -u $SCRATCH_ORG_ALIAS
    only:
    - merge_requests
    - develop
    - master
    - taxonomy
