### ISSUE TITLE
Creating a repository for an authenticated user

### ISSUE THREAD

**Issue by ahmadkani** [isomorphic-git/isomorphic-git#1941]
I'm using this incredible library for a while and creating an app with it. then I wanted to create a repository for a user using isomorphic git methods but I couldn't find this kind of function.
First of all, is there any feature like this has been implemented?
Secondly, can it be implemented in the client side using isomorphic git?
I also have found this API docs for doing so : https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-for-the-authenticated-user
Any help would be appreciated. 
Although I think this feature is so interesting that couldn't been out of sight of the developers but should've been impossible or hard to implement!

**Comment by RuanXinyu** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jcubic** [comment]
Isomorphic-git is only for interacting with git repository and git hosting. It has nothing to do with GitHub. If you want to create git repo on GitHub you need to ask somewhere else, like [GitHub discussion](https://github.com/orgs/community/discussions).

But if you already have remote git repo, all you have to do is to init, commit, and push. Same as with canonical git. But you will probably need authenticated user token to do this.

**Comment by ahmadkani** [comment]
thanks for your answer and brightening up the scope of this project.
