### ISSUE TITLE
Erroring example in clone docs

### ISSUE THREAD

**Issue by dbkaplun** [isomorphic-git/isomorphic-git#196]
https://isomorphic-git.github.io/docs/clone.html:
```js
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at HTMLDocument.listener (try-it-out-giturl.js:28)
```

Google Chrome
Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by wmhilton** [comment]
I fixed the error, but it still seems... slower than I remember. Very slow. I wonder if that's because the repo it's cloning has gotten bigger or if it has gotten slower.
