### ISSUE TITLE
missing files after resetting indexeddb

### ISSUE THREAD

**Issue by ahmadkani** [isomorphic-git/isomorphic-git#1960]
Hi

I'm using isomorphic git and lightning fs for a while and these are two of the best libraries I've worked with.
but I've always had this strange problem that I think you have somehow said something about it in LRU caching.
but I don't know what causes the problem and how you cache it?
this is the problem: when I clone the project and then the indexeddb gets deleted for recloning the files in the repository are gone and are not in the indexedb and there is only the git files.
do you have any ideas about this problem?
or do you want me to explain more about thi?

**Comment by jcubic** [comment]
Can you create a reproduction?

Do I understand that you:

1. Clone repo
2. Delete IndexedDB
3. Clone repo again with same directory

and the git repo is not saved in indexedDB?

**Comment by jcubic** [comment]
Can you create a working demo?

**Comment by ahmadkani** [comment]
yes i made a simple html code so you can test it, it's not a fully functional code and it has some bugs but gives you the idea

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Isomorphic Git Clone Example</title>
  <script src="https://unpkg.com/@isomorphic-git/lightning-fs"></script>
  <script src="https://unpkg.com/isomorphic-git@beta"></script>
  <script src="https://cdn.jsdelivr.net/npm/idb-keyval@3.2.0/dist/idb-keyval-iife.min.js"></script>
</head>
<body>
  <h1>Clone a Git Repository with Authentication</h1>

  <button id="cloneRepo">Clone Repository</button>
  <button id="deleteStore">Delete File Store</button>
  <button id="checkFiles">Check Files</button>

  <pre id="output"></pre>

  <script type='module'>

	import http from 'https://unpkg.com/isomorphic-git@beta/http/web/index.js'

    const fs = new LightningFS('gitfs', { wipe: false });
    const { promises } = fs;

    const REPO_URL = 'your repo url';
    const USERNAME ='your personal access token' ;
    const PASSWORD = 'x-oauth-basic';
    const corsProxy = 'your cors proxy url';


    async function cloneRepo() {
      try {
        await git.clone({
          fs,
          http,
          corsProxy: corsProxy,
          dir: '/',
          url: REPO_URL,
          singleBranch: true,
          depth: 1,
          onAuth: () => ({
            username: USERNAME,
            password: PASSWORD,
          }),
        });
        document.getElementById('output').textContent = 'Repository cloned successfully!';
      } catch (err) {
        document.getElementById('output').textContent = `Error cloning repository: ${err.message}`;
      }
    }


    async function deleteFileStore() {
        async function deleteRecursively(path) {
          const items = await promises.readdir(path);
          for (const item of items) {
            const itemPath = `${path}/${item}`;
            const stats = await promises.stat(itemPath);
            if (stats.isDirectory()) {
              await deleteRecursively(itemPath);
            } else {
              await promises.unlink(itemPath);
            }
          }
          await promises.rmdir(path);
        }

        try {
          await deleteRecursively('/');
          document.getElementById('output').textContent = 'File store deleted!';
        } catch (err) {
          document.getElementById('output').textContent = `Error deleting file store: ${err.message}`;
        }
      }

    async function checkFiles() {
      try {
        const files = await promises.readdir('/');
        document.getElementById('output').textContent = 'Files in /: ' + JSON.stringify(files);
      } catch (err) {
        document.getElementById('output').textContent = `Error reading /: ${err.message}`;
      }
    }

    document.getElementById('cloneRepo').addEventListener('click', cloneRepo);
    document.getElementById('deleteStore').addEventListener('click', deleteFileStore);
    document.getElementById('checkFiles').addEventListener('click', checkFiles);
  </script>
</body>
</html>
```

**Comment by jcubic** [comment]
Got error: `Error deleting file store: ENOTEMPTY` so the directory is not really deleted.

**Comment by ahmadkani** [comment]
I can't understand your point. yeah the code is not working well because it was just for illumination.
would you run this code : 
https://codepen.io/ahmadkani/pen/bGXvoPX 
and give me your thoughts on it ?
when you delete the repo entirely from the fs it can't give you the files except of the .git

**Comment by jcubic** [comment]
If you create a production of the error, you need to make something that really demonstrate the issue and not give an error before you even see the issue.

**Comment by jcubic** [comment]
Ok, the problem is that you use Beta version of isomorphic git, that was published a few years ago before version 1.0 come out.

It looks like with the latest version of Isomorphic-git everything works fine.

**Comment by ahmadkani** [comment]
Oh, that's very nice of you. thanks for the easy yet difficult to imitate solution.
the problem is that i have started with the documents like : https://isomorphic-git.org/docs/en/quickstart.html which has used the beta version of isomorphic git. I guess modifying it will help other people not to falling into this problem.

**Comment by jcubic** [comment]
Thanks for bringing up an issue about the docs.

I've updated the quick-start page, I hope the website will get updated. The whole CI/CD was setup by the original author that no longer work on the project, and it works like magic, or doesn't work at all.

**Comment by ahmadkani** [comment]
Apparently it hasn't changed, but thank you for your help.

**Comment by jcubic** [comment]
Yea, we have problem with the build there is a limit of 30 min on Azure, the same as on GitHub actions and the build take longer. Also, I didn't add prefix to commit, not sure if this affect building documentation.
