### ISSUE TITLE
Clone progress event

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#197]
Clone take really long time (event with depth = 1), it would be nice if there is some kind of progress event, ideally with % of done or message what is library currently doing.

**Comment by kyleparisi** [comment]
There is an EventEmitter config option that you can pass in

**Comment by jcubic** [comment]
Thanks, I'm now using the event emitter but now when I clone, it hangs after message: "Compressing objects: 100% (652/652), done" and last progress event.

**Comment by kyleparisi** [comment]
Hm, not sure about that one

**Comment by jcubic** [comment]
It's about 1min delay between messages especially between compress 100% and Total. Progress events are usually really fast.
