### ISSUE TITLE
CodeCommit clone issue

### ISSUE THREAD

**Issue by kyleparisi** [isomorphic-git/isomorphic-git#199]
I have 2 issues when trying to clone from AWS codecommit repos.  First issue is the `GitRemoteHTTP.discover` and `GitRemoteHTTP.connect` are appending `.git` to the urls.  I've seen other issues reported where this is required so not sure how to handle that.

The second issues is the following error:
```bash
TypeError: Cannot read property 'replace' of undefined
    at Object.clone (/Users/kyleparisi/lambdas3/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:2939:13)
    at <anonymous>
```

I tried investigating this second issue and was not successful in understanding the issue.  What I gather is that the response from codecommit is not working in retrieving the packfile.  This is the response I get from curling the `discover` route:
```bash
001e# service=git-upload-pack
00000099de3e3cae168df55f271122dbed0420d5a0595b5b HEAD�multi_ack_detailed shallow side-band-64k thin-pack allow-tip-sha1-in-want allow-reachable-sha1-in-want
003fde3e3cae168df55f271122dbed0420d5a0595b5b refs/heads/master
0000
```
Any ideas what might be broken?

Reference material:
curling a public github repo
```bash
001e# service=git-upload-pack
0000010874a142ff37b557f9c7c89d93b6cac0f12f756ebd HEADmulti_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed no-done symref=HEAD:refs/heads/master agent=git/github-g5c70ccf6530b
003c38ed6dacd102add6c2b2adcb9ea5d273aae57929 refs/heads/7.1
003c5ec2a63336da891a78c87f0ef260bd1b8dd8d3d3 refs/heads/7.2
003f74a142ff37b557f9c7c89d93b6cac0f12f756ebd refs/heads/master
0000
```

**Comment by wmhilton** [comment]
I have a hunch! Does it work if you explicitly specify the branch to clone with `ref: 'master'`?

**Comment by kyleparisi** [comment]
Even though that solves the TypeError, I still don't end up with a cloned repo.  I end up with `.git/objects/pack/pack-.pack`.

**Comment by wmhilton** [comment]
Oh that's interesting. I ran into a problem with a `.git/objects/pack/pack-.pack` last night and thought it was a one off. OOOH I bet that gets generated if the packfile is empty, which (I think) can happen if you do a git fetch and there are no new commits. So that would be a bug. But why would the packfile be empty if you are doing a fresh clone... that seems very odd. Does it work with `singleBranch: true` maybe?

**Comment by kyleparisi** [comment]
Heres my clone command I've been running (including the ref you suggested).

```javascript
    git.clone({
      fs,
      dir: path.join(__dirname, "tmp"),
      url,
      ref: 'master',
      singleBranch: true,
      depth: 1
    });
```

I was not successful with modifications to singleBranch or depth.   Most of the time I try to remove the tmp folder before cloning as I think it tries to read from the pack files.

**Comment by wmhilton** [comment]
You might want to try again once #264 gets released. That should get rid of the empty `.git/objects/pack/pack-.pack` problem.

**Comment by kyleparisi** [comment]
Awesome.  One more error happens after getting that update:

```
{ Error: Failed to checkout ref 'master' because commit de3e3cae168df55f271122dbed0420d5a0595b5b is not available locally. Do a git fetch to make the branch available locally.
    at checkout (/Users/kyleparisi/lambdas3/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:2604:13)
    at <anonymous> caller: 'git.clone' }
```
I run a manual git fetch on that folder then rerun the clone script, then it gets the cloned repo.

**Comment by wmhilton** [comment]
Oh, I like that error, because it tells you how to fix it. :) That's one of my (few) good error messages I've written so far. I should make more like that.

**Comment by kyleparisi** [comment]
Do you think the clone command is missing a fetch step?

**Comment by kyleparisi** [comment]
Yeah.  I did a manual fetch to fix.  I'd like to make it repeatable because I intend to run this clone on a lambda so that I can do some CI type things.

**Comment by wmhilton** [comment]
Wait, by a "manual fetch" do you mean a fetch with isomorphic-git or with the canonical git? It's it open source so I could just see what your doing... it sounds like CodeCommit has some subtle differences in how it's configured that's throwing off my fetch code.

**Comment by kyleparisi** [comment]
Canonical git.  I pushed my work in progress to [this repo](https://github.com/kyleparisi/lambdas3).  To run you'll want to do something like `AWS_PROFILE=personal AWS_REGION=us-east-1 REPO_NAME=isomorphic-git node index.js`.  Thanks for looking!

**Comment by wmhilton** [comment]
AWS 404's if you add `.git` suffix and Gitlab 404's if you don't. Lol. After much experimentation, I've settled on observing HTTP redirects from the `discover` phase to determine which URL to use during the `fetch` phase.

Also, for some reason CodeCommit barfs and doesn't return a packfile if you include the `agent=git/isomorphic-git` string in the capabilities list. I think the proper thing to do (i.e. what canonical git is doing) is only include the `agent` capability during the `fetch` phase if the server presents the `agent` capability during the `discover` phase, but for now I've just removed it from the `fetch` phase, since that didn't seem to upset Github Gitlab or Bitbucket.

**Comment by wmhilton** [comment]
Arh, the redirect strategy is running afoul because of the CORS-proxy resolving redirects on its end... Hrmph

**Comment by kyleparisi** [comment]
Wow I forgot you support browsers.

**Comment by wmhilton** [comment]
Yeah... it sucks when you spend a bunch of time making a solution, testing it in Node, only to discover it won't work for the Browser. I shot my own foot there, making it auto-append ".git" to urls early on... if I'd made the user do it I wouldn't have this whole problem. :D As it is, it looks like I'll end up with a clunky solution: adding a `noGitSuffix: true` argument to the clone/fetch/push functions.

**Comment by kyleparisi** [comment]
Maybe future major version can drop support.  I think user provided in clone url is best bet.

**Comment by kyleparisi** [comment]
Confirmed working via 

````javascript
    await git.clone({
      fs,
      dir: path.join(__dirname, "tmp"),
      url,
      ref: 'master',
      singleBranch: true,
      depth: 1,
      // new option:
      noGitSuffix: true
    });
```
