### ISSUE TITLE
[IOS - React native] ParseError: Expected "# service=git-upload-pack\n" but received "" when getRemoteInfo

### ISSUE THREAD

**Issue by tuanlevi95** [isomorphic-git/isomorphic-git#1994]
i used getRemoteInfo method like this and got error:
`ParseError: Expected "# service=git-upload-pack\n" but received ""`

here is the coding:
```
import git, { type PromiseFsClient } from 'isomorphic-git/index.umd.min.js';
import http from 'isomorphic-git/http/web/index.js';
...
   const info = await git.getRemoteInfo({
        http,
        url: 'https://github.com/isomorphic-git/isomorphic-git.git
      });
```

it worked perfect on android emulator, but ios not working.
I tested on simulator using ios 18

**Comment by jcubic** [comment]
I have no clue, something needs to be off with iOS. You can try to debug this to find what is happening.

**Comment by tuanlevi95** [comment]
i thought getRemote just fetch api from git and get result, are there any missing of cert?

**Comment by jcubic** [comment]
This project is Open Source, you don't need to assume anything, you can check the source and see what `getRemote` is doing.

**Comment by tuanlevi95** [comment]
i resolve with this pr: https://github.com/isomorphic-git/isomorphic-git/pull/1997
