### ISSUE TITLE
Delete file not listed

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#206]
## What do I get:

```javascript
await git.listFiles({fs, dir});
// ['foo', 'bar', 'baz'];
await git.remove({fs, dir, 'foo'});
await git.listFiles({fs, dir});
// ['bar', 'baz'];
// should be [['foo', 'bar', 'baz'];
await pfs.readDir(dir);
// ['foo', 'bar', 'baz']
await git.status({fs, dir: '/test', filepath: 'foo'})
// undocumented "*undeleted"
await git.add({fs, dir: '/test', filepath: 'foo'})
await git.status({fs, dir: '/test', filepath: 'foo'})
// "unmodified"

await git.remove({fs, dir, 'foo'});
await pfs.unlink('/test/foo');
await git.status({fs, dir: '/test', filepath: 'foo'})
// deleted which is fine but
await git.listFiles({fs, dir});
// ['bar', 'baz'];
// should be [['foo', 'bar', 'baz'];
```

## What I expect:
the file should always be on the list because it's not yet committed.
When I call `fs.unlink('/test/foo');` the file have correct status deleted but it's not one the list.

**Comment by jcubic** [comment]
I've found this code by try and error:

```javascript
git.remove({fs, dir: '/test', filepath: 'bar'}).then(() => git.add({fs, dir: '/test', filepath: 'bar'})).then(() => fs.unlink('/test/bar'));
```

it make the file appear as deleted but I can't call git.add on that file because I got error file not found.

**Comment by wmhilton** [comment]
`listFiles` lists the files currently in the git index (sometimes called the git stage). I *think* you'll find its behavior is consistent with `git ls-files`... I just tried it and `git ls-files` will not list a file if it has been removed with `git rm`, even though that change is not committed.

**Comment by wmhilton** [comment]
What you *might* want is to list the files from the current HEAD commit. Which, due to the way git stores things internally, is a more complicated recursive task. For more details see [this thread](https://github.com/isomorphic-git/isomorphic-git/issues/43#issuecomment-361017144)

**Comment by wmhilton** [comment]
And if that's what you want, I'll follow through on what I told @mojavelinux and write up the code that does that and add it to the FAQ #191

**Comment by mojavelinux** [comment]
I agree files which are removed should not be shown in listFiles as they are no longer part of the index. This is different from reading from the working tree, where the file still lives, as the API docs for remove states:

> Note that this does NOT delete the file in the working directory.

If you want to read files from the working tree, I just recommend using the regular fs module.

**Comment by jcubic** [comment]
What I want it to implement normal `git rm` that remove the file from git then from disk and then add it to staging area. And second I want to have `git rm --cached` but this is probably just `git.remove`

**Comment by mojavelinux** [comment]
In that case, I think what we're really talking about is an enhancement to remove...perhaps an additional argument to have it remove from the working tree.

**Comment by wmhilton** [comment]
A normal `git rm` should just be `await git.remove(); await pfs.unlink()`

**Comment by jcubic** [comment]
@wmhilton It was my second try when I've notice that file stay on disk. That listFiles I've used to display status was confusing because it looked like the file disappear.  Will take a look for that recursive list of files from Head then. Thanks for the hint and also for this great project.

**Comment by jcubic** [comment]
I think that there is no problem in doing extra step to delete the file but there should be example how to list all the files in FAQ or maybe update the api with extra parameter that will indicate that it should show files from commit/HEAD.

**Comment by jcubic** [comment]
I've came up with function that list all files from branch:

```javascript
async function listBranchFiles(fs, dir, branchName) {
    const repo = { fs, dir };
    const originBaseRef = 'refs/remotes/origin/';
    const sha = await git.resolveRef({ ...repo, ref: originBaseRef + branchName });
    const { object: { tree } } = await git.readObject({ ...repo, oid: sha });
    var list = [];
    return (async function readFiles(oid, path) {
        const { object: { entries } } = await git.readObject({ ...repo, oid});
        var i = 0;
        return (async function loop() {
            var entry = entries[i++];
            if (entry) {
                if (entry.type == "blob") {
                    list.push(Object.assign({}, entry, {
                        path: path.concat(entry.path).join('/')
                    }));
                } else if (entry.type == "tree" && entry.path !== ".git") {
                    await readFiles(entry.oid, path.concat(entry.path));
                }
                return loop();
            }
        })();
    })(tree, []).then(() => list.map((entry) => entry.path));
}
```

this can be put in FAQ, it list the same number of files as git.listFiles.

**Comment by wmhilton** [comment]
> or maybe update the api with extra parameter that will indicate that it should show files from commit/HEAD.

Ooooh! I really like that idea. We could just add a `ref` parameter to `listFiles`, and that could work for listing files in a branch, or a tag, or a commit, and even for a tree. I think the only thing it wouldn't work on is Blobs, which could throw an error message.

**Comment by wmhilton** [comment]
Yeah... so `readObject` is still better for say a file explorer UI or searching for a particular file, but for the simple case of "just list all the files in the commit" it would make sense to have it built in, because listing all the files is going to be maximally inefficient regardless, but still needed for a lot of common tasks - like git merge most likely.

**Comment by jcubic** [comment]
This one can be closed.
