### ISSUE TITLE
Logo for isomorphic-git

### ISSUE THREAD

**Issue by familqasimov** [isomorphic-git/isomorphic-git#210]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![isomorphic-git](https://user-images.githubusercontent.com/36432269/40245346-6f6ef16a-5ad6-11e8-8733-32769f297ca6.png)

Best Regards
Famil Qasimov

**Comment by wmhilton** [comment]
Thank you for the offer, but I'm happy with the current logo... and I don't think using the Java logo would make sense.
