### ISSUE TITLE
Show API function name in error message

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#212]
So now I have complicated app with lot of calls for git functions and I use one catch at the end but I don't know what caused the issue it would be usefull if each error message show exact api method that caused the error so it's easy to find the problem.

This may be problematic because they are other functions, that not exposed, that can cause errors.

**Comment by wmhilton** [comment]
I've been meaning to go through and systematize all the errors. Ideally, there would just be a big list, they'd all be imported from some `errors.js`, they'd all have a corresponding error code and a link to the appropriate documentation page on the website. And the documentation for each function on the website would document not just the return value (as it currently does) but also all the possible thrown Errors. (And if TypeScript supports documenting Error types include that in the TypeScript definitions for the functions.)

Hopefully there's some kind of library for Errors now that would make managing this easier. The last time I looked the only thing I found was a thing called VError but it didn't have all the features I wanted. I mean, ideally you could even bake in the filename and line number - not from a stack trace which could be unreliable but as a preprocessing step - so it would be trivial to know "OK, this error came from this part of the source code".

If nothing like that exists yet, maybe that would be a good weekend project. 🤔

**Comment by wmhilton** [comment]
It looks like neither TypeScript nor FlowType provide a mechanism for typing the `throws` of a function, only the return value.

**Comment by wmhilton** [comment]
So I figured out how to solve this Error Management problem using an eslint plugin. It's pretty cool actually. I'm still adding features, but I'll probably have it published this evening or tomorrow afternoon.

**Comment by wmhilton** [comment]
@jcubic See my proposal in #217. I am very interested in your feedback! (And feedback from anyone and everyone; the ideas in the proposal are not specific to `isomorphic-git` and could be adopted by pretty much every npm module I think.)

**Comment by wmhilton** [comment]
Fixed by #262 I think
