### ISSUE TITLE
No messages events in push

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#214]
I just successfully [pushed first commit](https://github.com/jcubic/git/commit/2338b84026b10baa9495d62775a36b891168fd8d) (one side issue it put `&lt;` inside of `<`, don't know yet the reason). but when I push I didn't get events from event emitter.

I have code like this:

```javascript
var emitter = new EventEmitter();
emitter.on('message', (message) => {
    term.echo(message);
});
git.findRoot({fs, filepath: cwd}).then(dir => {
    return git.push({
        fs,
        dir,
        ref: branch,
        authUsername: credentials.username,
        authPassword: credentials.password,
        emitter
    });
}).then(term.resume).catch(error);
```

**Comment by jcubic** [comment]
Ok, but emitter then is redundant because it doesn't do anything. It's just misleading because you expect messages. I think that emitter should be removed or emit one message that last one:
```
To https://github.com/isomorphic-git/isomorphic-git
 * [new branch]      update-cors-proxy -> update-cors-proxy
```

And side question, because I'll implement those messages myself for now, do you know what are those hashes? they are not from commits.

```
To github.com:jcubic/git.git
   0879d82..465fc50  gh-pages -> gh-pages
```

and one more thing I need to know if branch is new or not, is it possible to get that info with `isomorphic-git` or from .git directory directly?

**Comment by wmhilton** [comment]
> Ok, but emitter then is redundant because it doesn't do anything.

See https://github.com/isomorphic-git/isomorphic-git/issues/106 Don't assume because your server is quiet that they all are! 😁 If the server sends messages, you need a way to receive them.

>  do you know what are those hashes? they are not from commits.

Oh but they are!
![image](https://user-images.githubusercontent.com/587740/40383818-cb7a9dc8-5dcf-11e8-8f5e-d2fd84d4a0bf.png)

**Comment by jcubic** [comment]
Sorry my bad, was checking wrong repo or branch then. So this is no issue. closing

**Comment by jcubic** [comment]
One question remain is there a way to know if branch is new?

**Comment by wmhilton** [comment]
> One question remain is there a way to know if branch is new?

Not off the top of my head. I think right now the only way to do that would be to do `listBranches` on the remote before a push and see if it exists.
