### ISSUE TITLE
git push force

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#219]
So now from #129 I have function that restore git repo from `HEAD~1` but when I have pushed the commit I to update remote I need to use `git push -f`.

if this is how push works every time then I need to a way to check if push will overwrite commits so I would be able to reject it when user don't use force.

**Comment by wmhilton** [comment]
Oh no... are you saying that `isomorphic-git`'s push is basically doing `git push --force` by default?

**Comment by jcubic** [comment]
no, I don't know what typo of push `isomorphic-git` do, but it do one type and I need both and a way to invoke both.

**Comment by isysd** [comment]
I have received errors when attempting to force push or do similar non-trivial pushes. :+1:

**Comment by wmhilton** [comment]
I'll have to do some experiments with GIT_TRACE_PACKET=1 and see what is different about force pushes. I didn't see them mentioned in the git protocol docs.

**Comment by wmhilton** [comment]
A deep search of the git source code reveals that [`git push -f` is a client side implementation detail](https://github.com/git/git/blob/b7bd9486b055c3f967a870311e704e3bb0654e4f/remote.c#L1425). So yes, we must check that what we are pushing follows the 4 rules laid out in the comment ourselves before doing a push:

```

		/*
		 * If the update isn't already rejected then check
		 * the usual "must fast-forward" rules.
		 *
		 * Decide whether an individual refspec A:B can be
		 * pushed.  The push will succeed if any of the
		 * following are true:
		 *
		 * (1) the remote reference B does not exist
		 *
		 * (2) the remote reference B is being removed (i.e.,
		 *     pushing :B where no source is specified)
		 *
		 * (3) the destination is not under refs/tags/, and
		 *     if the old and new value is a commit, the new
		 *     is a descendant of the old.
		 *
		 * (4) it is forced using the +A:B notation, or by
		 *     passing the --force argument
		 */
```

which, written another way, I think ends up being:

Require `--force` for a push if:
- the ref is a tag that already exists on the server
- the ref is a branch that already exists on the server and the new oid is NOT a descendent of the old
