### ISSUE TITLE
Wrong timezone offset in commit

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#221]
I've notice that my terminal is adding commit with -0000 offset, I didn't put date so it should get new Date but with browser timezone.

Old commits when I did git clone have +0200 (120 offset).

**Comment by wmhilton** [comment]
Wait... -0000 offset? Shouldn't it at least be +0000?

_half an hour of debugging later_
Well. Today I have learned some fun facts about negative zero.

```js
Math.sign(-0)
// -0
-0 === 0
// true
Object.is(-0, 0)
// false
```

**Comment by jcubic** [comment]
in fact it's string not actual number it's probably just 0.

**Comment by wmhilton** [comment]
Actually -120, because (new Date()).getTimezoneOffset() is weird.

**Comment by wmhilton** [comment]
I've created some insane eyebrow raising logic to fix this "0 becomes -0000" logic but still let you create a commit with "-0000" if you need to.

**Comment by jcubic** [comment]
Oh, didn't know about timezoneOffset property when doing commit. Will use it then.

**Comment by wmhilton** [comment]
> Oh, didn't know about timezoneOffset property when doing commit. Will use it then.

Apparently I forgot to document it. Or use it in any of my own tests.  ¯\\_(ツ)_/¯
