### ISSUE TITLE
fetch remote refs

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#223]
It would be nice if `isomorphic-git` expose api for fetching remote refs sames as the one that located in `.git/refs/remotes/origin/` but on the remote so you can compare commits.

I'll be able to show message:

```
 Switched to branch 'master'
 Your branch is ahead of 'origin/master' by 2 commits.
   (use "git push" to publish your local commits)
```

I'll just run git log with all commits and search for commit from remote for selected branch. If not found it mean that branch is behind.

**Comment by wmhilton** [comment]
I think you can do that using [getRemoteInfo](https://isomorphic-git.github.io/docs/getRemoteInfo.html). That'll work for if you're ahead... I'm not sure how you'd figure out how many gets behind you are.

**Comment by jcubic** [comment]
I'm just wondering if behind is just pull being done on other branch, like fetch so it's remote branch locally updated but not yet merged to your local branch. Is this how fetch work?

**Comment by wmhilton** [comment]
yyyes, actually. Now that I think about it, that 'Your branch is behind by X commits' only updates when you do a `git fetch` doesn't it? So it's probably just doing a git log on `refs/remotes/origin/remote-tracking-branch`.

**Comment by wmhilton** [comment]
I think this can be closed? Using `fetch` works for this right?
