### ISSUE TITLE
git log's 'since' parameter is comapred with author timestamp instead of commit timestamp

### ISSUE THREAD

**Issue by howardgod** [isomorphic-git/isomorphic-git#227]
Hi,

As title, the since parameter is using on author date, would it be intentional?
If so, is it possible to provide another parameter to compare with commit date as well?

thank you,

Howard

**Comment by wmhilton** [comment]
Wow I really had to dig through `git`'s source code to confirm that, but you're right it should be using the committer not the author. Feel free to open a PR or if you'd rather not yourself I can.

**Comment by wmhilton** [comment]
Right [here](https://github.com/isomorphic-git/isomorphic-git/blob/fa0101cddace7ab320c752fd720f9671e1085865/src/commands/log.js#L68) we just need to replace `author` with `committer`.
