### ISSUE TITLE
dist/bundle.umd.js

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#246]
it would be easier to debug the library if there is bundle for browsers but not minified.

**Comment by wmhilton** [comment]
Are source maps not working? I had hoped that would provide an awesome debugging experience even for the minified version.

**Comment by jcubic** [comment]
I've just notice that there is bundle.umd.js, never used source maps only pretty print in source panel.

**Comment by wmhilton** [comment]
All browsers should be using sourcemaps automatically... maybe only if you have DevTools open though? Which browser are you testing with that's showing the minified version?

**Comment by jcubic** [comment]
I've just notice that there is bundle.umd.js.

**Comment by jcubic** [comment]
I'm using Chromium and I have enabled source maps in dev tools settings, don't know how they suppose to work.

**Comment by wmhilton** [comment]
Hmm. Well... hmm. Does this picture help? It shows where in the Sources panel to look, and setting a random breakpoint in `git.add`.
![image](https://user-images.githubusercontent.com/587740/40589543-0d06765e-61bd-11e8-8f25-e3fa2497e5ce.png)

**Comment by wmhilton** [comment]
And no, I can't claim to understand _why_ it is in a folder called "." inside "git". I mean, I guess "git" is because the UMD bundle uses `git` as the name of the library. And "." just seems to be a webpack-ism.

**Comment by jcubic** [comment]
Wow It works, thanks.
