### ISSUE TITLE
can't clone gists

### ISSUE THREAD

**Issue by burningTyger** [isomorphic-git/isomorphic-git#247]
I followed the API and apparently I can't clone gists.

This is my code:

    await git.clone({
      fs,
      dir: '/tmp/test',
      ref: 'master',
      url: 'https://gist.github.com/f55e5fc30238c672621f56aba653904c.git'
    })

It does clone the gist repo but only populates it with the `.git` directory. I could then `git.pull` to get the file too but that's not how cloning works.

If I use the isomorphic-git repo address as `url` it works as expected.

**Comment by wmhilton** [comment]
Confirmed. For some reason, Github is returning 404 Not Found errors for service discovery attempts requests to gists if the `User-Agent` string does not start with `git/`. Regular Github repos only require the User-Agent string for the second HTTP request which does the actual cloning. I guess we'll need to send the User-Agent for both of them. :/

**Comment by burningTyger** [comment]
thanks a lot!

**Comment by wmhilton** [comment]
Haha well (assuming this is the correct fix) it was really easy. :)
The robot should leave a message to let us know when this gets published on npm, so then you can try with that version.

**Comment by burningTyger** [comment]
great, works as expected now. Thank you.

**Comment by jcubic** [comment]
Does this work, got error `Expected '# service=git-upload-pack\n' but got ''` when cloning gist. I'm using version 0.17.2

**Comment by jcubic** [comment]
Is this fixed? I'm not able to clone unless I spoof my User-Agent.

**Comment by jcubic** [comment]
Maybe the fix is only for backed because when I inspect the http request it send my normal useragent. So this is not fixed for browser.

**Comment by wmhilton** [comment]
@jcubic Whether the frontend can send the necessary User-Agent depends on the CORS headers. If you're using cors-buster-tbgktfqyku.now.sh as your proxy, it should work.

I see you're using your own proxy. Make sure you are including 'User-Agent' in the 'Access-Control-Allow-Headers'.

**Comment by wmhilton** [comment]
Attempting to fix problem at the source. Tracking https://github.com/jhiesey/stream-http/pull/89

**Comment by wmhilton** [comment]
FYI here's the chain of dependencies:
`isomorphic-git` > `simple-get` > `webpack/node-libs-browser` > `https` > `http`

Note that even once/if this is fixed upstream and it trickles down into whatever build of Webpack we're using, there is a bug in Chrome that will block us. Firefox, Edge, and Safari all handle this correctly:

```
fetch('https://cors-buster-tbgktfqyku.now.sh/gist.github.com/f55e5fc30238c672621f56aba653904c/info/refs?service=git-upload-pack', {headers: {'user-agent': 'git/firefox'}}).then(res => res.text()).then(console.log)

001e# service=git-upload-pack
000001087a640443626dc1376dc6a83d102d570854c30f46 HEAD�multi_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed no-done symref=HEAD:refs/heads/master agent=git/github-g329139f472a1
003f7a640443626dc1376dc6a83d102d570854c30f46 refs/heads/master
0000
```

But Chrome does not:

```
fetch('https://cors-buster-tbgktfqyku.now.sh/gist.github.com/f55e5fc30238c672621f56aba653904c/info/refs?service=git-upload-pack', {headers: {'user-agent': 'git/firefox'}}).then(res => res.text()).then(console.log)

Not Found
```

Meanwhile, I've emailed Github support to start a conversation about their HTTP headers. Maybe, just maybe, we can talk them into dropping their User-Agent filtering shenanigans.

**Comment by jcubic** [comment]
Is this fixed because the diff don't show package.json change only pakcage-lock.json.

**Comment by wmhilton** [comment]
Yes! I can confirm that cloning gists now works in Firefox:
![image](https://user-images.githubusercontent.com/587740/40871513-eec148ca-660a-11e8-8bf7-d6056ed3d256.png)

and is broken in Chrome:
![image](https://user-images.githubusercontent.com/587740/40871518-002b4c00-660b-11e8-8d7e-c2670ab1b73a.png)

But there is honest-to-god nothing we can do about the Chrome bug. Either a) Github needs to stop returning 404s based on User-Agent or b) Chrome needs to follow the actual specs like Firefox, Safari, and Edge and allow setting the User-Agent header in CORS requests. Or c) you could modify your own proxy (https://jcubit.pl/proxy.php) to use a User-Agent string starting with "git/" when you proxy the requests.

**Comment by jcubic** [comment]
In chrome you can't even use XHR to set `user-agent`. I've delete fetch before including isomorphic-git so it get xhr instead of fetch and I've got error `request.js:194 Refused to set unsafe header "user-agent"`.

Will set up my proxy to include that user-agent. thanks for the tip.

**Comment by wmhilton** [comment]
Meanwhile I'll create a new issue to track the Chrome-specific bug.
