### ISSUE TITLE
Return last git commit in getRemoteInfo

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#250]
Would it be possible to fetch last commit in this API function (maybe get heads for all branches if that will not slow things down) so I can call it before git.pull and if commit is already locally I would just show message `Already up-to-date.`, because right now I get messages from emitter.

**Comment by wmhilton** [comment]
I think that's what this function does... it ought to return all the refs

**Comment by jcubic** [comment]
Don't know why but when I tested it was returning list of branches and now it return refs with commits.

**Comment by wmhilton** [comment]
I think it's always returned an object mapping refs to commits. You must have had something else going on lol.
