### ISSUE TITLE
git.log needs to trace all merge parents

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#253]
Right now, git.log is only following the first parent. This causes a bug in building packfiles for sendUploadPackResult because it is not including the commits from the merged branches.

**Comment by Cobertos** [comment]
> git.log is only following the first parent

Is this also why `git.log` only returns a single parent for a merge commit in the `commit.parent` array? I just ran into this bug in my code today.

**Comment by wmhilton** [comment]
> Is this also why git.log only returns a single parent for a merge commit in the commit.parent array? 

It might be. Although I would think that it would still list both parents, even if it only followed the one.

**Comment by Cobertos** [comment]
Yay! Thank you so much! Now I can take out my
commit.message.match(/^Merge/) hack :P
