### ISSUE TITLE
trouble with git.checkout

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#254]
So I have repo and I want to checkout branch and I've called git.fetch branch (because when I try to checkout without it it give error that I need to use fetch first) depth: 1  then git.checkout of same branch and it freezes, the problem is method GitPackIndex::fromPack that read from buffer:
```javascript
    await new Promise((resolve, reject) => {
      buffer2stream(pack)
        .pipe(listpack())
        .on('data', async ({ data, type, reference, offset, num }) => {
```
And my case the data event is not fired so the promise is never resolved and it keeps waiting. If something is wrong it should reject the promise, don't know why it fail to read the buffer.

**Comment by wmhilton** [comment]
I think you'll need to provide a code sample that can reproduce the problem. I'm guessing it is a problem with buffer2stream or listpack, but we'll need the packfile to debug it.

**Comment by wmhilton** [comment]
> (because when I try to checkout without it it give error that I need to use fetch first)

I remember writing that Error message, because it is actually helpful! That happens when you clone using `singleBranch` and try to checkout a different branch, right?

**Comment by jcubic** [comment]
> I remember writing that Error message, because it is actually helpful! That happens when you clone using singleBranch and try to checkout a different branch, right?
yes, that's right, will create code sample that show the error.

**Comment by jcubic** [comment]
I had broken repo because `git log` also freezes. I was doing only git commands do you want any file that I have in browser in other to see what's was happening?

There may be a bug in `isomorphic-git` and it should give exception/reject on each git command if repo is corrupted.

**Comment by wmhilton** [comment]
> it should give exception/reject on each git command if repo is corrupted.

Easier said than done my friend. :)

But more realistically... it wouldn't be out of the question for all of the commands to include a Cancel mechanism. At least all the commands that have a primary loop or stream. A simple timeout would be a quick hack to get more durability, although it would be even nicer to provide something like an [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort).

Well... no, AbortController isn't serializable. I'll need to think of a mechanism that works over postMessage.

**Comment by TomasHubelbauer** [comment]
You may want to check out the concept of cancellation tokens. It's used in VS Code codebase and is an often seen pattern in .NET code. 

E.g.: https://docs.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads

**Comment by jcubic** [comment]
What about checking [buffer.length](https://duckduckgo.com/?q=node+buffer+length&ia=web)
```
await new Promise((resolve, reject) => {
      if (!pack.length) {
          return reject('meaningul error message');
      }
      buffer2stream(pack)
        .pipe(listpack())
        .on('data', async ({ data, type, reference, offset, num }) => {
```

**Comment by jcubic** [comment]
Weird I just applied this to the source code included and now my repo git return commits on git log even that it's rejected.

**Comment by jcubic** [comment]
.git/refs/heads/gh-pages content was 257465cbe3855cafc276f339d3a4e2df424feec1 but this
```
await git.log({fs, dir: '/git', ref: '257465cbe3855cafc276f339d3a4e2df424feec1'})
```
throw my error.

**Comment by wmhilton** [comment]
> What about checking buffer.length

Oh bloody hell, I bet I know what it is.

@jcubic Delete `.git/refs/objects/pack-.pack`

And then somebody open a PR adding a check around [lines 78-82](https://github.com/isomorphic-git/isomorphic-git/blob/16a8f737ea412875ed328b866a4a306c5e34bb5c/src/commands/fetch.js#L78) to prevent saving the packfile to disk if it's completely empty. Longer term, we should actually a) NOT concatenate the entire packfile into memory (line 78), b) compute the SHA of the stream except for the last 20 bytes, using the same library used in `push.js`, and c) compare the computed SHA with the last 20 bytes of the stream before saving to disk, and throwing a "packfile got corrupted during download" error if the SHA doesn't match.

**Comment by jcubic** [comment]
> @jcubic Delete .git/refs/objects/pack-.pack

I don't have `refs/objects` directory

**Comment by wmhilton** [comment]
Ah, my bad. Typo. I meant `.git/objects/pack/pack-.pack`

**Comment by jcubic** [comment]
Sorry forget to remove that file and now I've removed the repo and created fresh clone.

**Comment by wmhilton** [comment]
@jcubic Were you ever able to make a code sample to reliably produce the error?

**Comment by jcubic** [comment]
It was not working when I last tested it but in 0.27.0 it works.

**Comment by wmhilton** [comment]
hell yeah! that's what I like to hear. Things be getting better all the time!
