### ISSUE TITLE
Config parsing

### ISSUE THREAD

**Issue by CMCDragonkai** [isomorphic-git/isomorphic-git#26]
Hey @wmhilton I've decided to abandon my effort in pursuing libgit2 + emscripten simply because mmap doesn't work properly with an adaptation of virtualfs as the emscripten inmemory fs. To do it properly will require a soft-mmu implemented in javascript and I'm not up to that.

So I've decided to go back to my old plan which is to reimpl git in JS. For now I'm looking through your codebase to adapt. The first output is actually config parsing. I see that you're using the ini parsing system, without a real parser. So I've implemented a real git-config parser: https://github.com/MatrixAI/js-virtualgit/tree/master/lib/config All tests are passing for this. There are a couple things missing: tilde expansion for inclusion paths and conditional includes, but they are kind of not important at this stage.

Oh and while I'm adapting your code, I have slightly different requirements than yours that's why I cannot just directly use your codebase, but I hope we can collaborate together and share code/algos/ideas. So feel free to use my lexer/parser/interpreter for your isomorphic git if you want.

**Comment by wmhilton** [comment]
Oh boy! Yes my config parser is... well, 80% for 20% as they say. I will definitely take a look at your parser.

**Comment by CMCDragonkai** [comment]
Currrently I'm reworking it to have a more granular translation between config changes in-memory and the necessary config changes applied to the file.

**Comment by wmhilton** [comment]
Let me know if you added the ability to parse git's weird "fetch" syntax, e.g.
```
[remote "origin"]
fetch = +refs/heads/*:refs/remotes/origin/*
```

I don't currently parse it and probably should so I can do proper git pulls.

**Comment by CMCDragonkai** [comment]
It does currently parse it. But still need to work out a better concrete syntax tree index data structure.

**Comment by wmhilton** [comment]
I'm going to close this issue and recommend moving the discussion to the new community Gitter chat room! https://gitter.im/isomorphic-git/Lobby
