### ISSUE TITLE
Use 'pako' instead of 'inflate' in 'git-list-pack'

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#294]
So... git-list-pack by chrisdickinson is using his *own* inflate module rather than pako, and my experimenting suggests we'd get a 50x speedup by using pako instead.
![image](https://user-images.githubusercontent.com/587740/41814048-a037869e-7710-11e8-9965-1f34b5b67a85.png)

**Comment by erdahuja** [comment]
@wmhilton How can i do it?

**Comment by wmhilton** [comment]
I... don't know. There's a clue here (https://github.com/nodeca/pako/issues/126#issuecomment-356231736) but I think the best bet is to simply tag @chrisdickinson @creationix and @mariusGundersen and see if they have any words of wisdom?

**Comment by wmhilton** [comment]
@mariusGundersen Is async stream available as an npm module? I've been using Node streams throughout isomorphic-git because they are familiar, but they are a bit of a pain.

**Comment by mariusGundersen** [comment]
[Async iterables](https://github.com/tc39/proposal-async-iteration) is a part of es2018 and is supported in the latest node version, but I'm writing in TypeScript which compiles it down to generators and promises.

**Comment by wmhilton** [comment]
Right... but what are you using to convert say, the [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) returned by `window.fetch` into an async iterable, that has this awesome "rewind" feature?

**Comment by wmhilton** [comment]
Oh wow! It's built right into the latest version of node. It is still labeled [Experimental](https://nodejs.org/api/stream.html#stream_readable_symbol_asynciterator) however.

**Comment by mariusGundersen** [comment]
Yes, it's coming to both node and `window.fetch` but until it does I have a simple way to convert from streams to async iterables [here](https://github.com/es-git/es-git/tree/master/packages/http-transport/ts/utils).

**Comment by wmhilton** [comment]
this was done in https://github.com/isomorphic-git/isomorphic-git/pull/305

**Comment by creationix** [comment]
If I remember correctly, Chris wrote his own because there was nothing else that worked in the way we needed at the time.  If there are better options now, I see no reason to not use them.
