### ISSUE TITLE
Concurrent working using big pack/idx files

### ISSUE THREAD

**Issue by akaJes** [isomorphic-git/isomorphic-git#297]
when calling script like 
```
Promise.all(list.map(filepath => git.status({fs, dir, filepath})))
```
we get numerous(depend to CPU speed) concurrent streams which trying do the same operations
1. opening idx
2. reading pack
in my case it is more than 100 promises and i get crash V8 with a core dump for 3GB

sample of my case:
```
git.listFiles({fs, dir})
  .then(list => Promise.all(list.map(filepath => git.status({fs, dir, filepath}).catch(e => '').then(status => ({filepath, status})))))
```

**Comment by wmhilton** [comment]
Hmm. GitIndex uses a lock and a cache, and GitPackIndex caches the packfile... so it should only need to access the filesystem for the very first call to git.status. Does it work any better if you do a serial call to git.status first to make sure it's cached before doing the concurrent calls?

```js
git.listFiles({fs, dir}).then(list =>
  git.status({fs, dir, filepath: list[0]}).then(() =>
    Promise.all(list.map(filepath =>
      git.status({fs, dir, filepath}).catch(e => '').then(status => ({filepath, status}))
    ))
  )
)
```

**Comment by akaJes** [comment]
cache doesn't work - because insertion into the cache invokes after the promise is resolved.
Your code will not works too, only if after first `status` you will wait some time :)

**Comment by wmhilton** [comment]
I don't yet understand what you mean, but I'm sure if I stare at the code long enough your change will make sense. 😁

**Comment by akaJes** [comment]
At morning I get new more nice version of PR
