### ISSUE TITLE
Error when pulling after a commit has been made outside isomorphic-git

### ISSUE THREAD

**Issue by fasiha** [isomorphic-git/isomorphic-git#303]
In the browser (Firefox latest stable), using `<script src="bundle.umd.min.js"></script>` where `bundle.umd.min.js` comes from `node_modules/isomorphic-git/dist/` (i.e., latest on npm), I can successfully clone a repo from GitHub using isomorphic-git (woweee 🙌!):
```js
        await git.clone({
          fs,
          dir: 'repo',
          url: 'https://cors-buster-tbgktfqyku.now.sh/github.com/fasiha/test-data',
          singleBranch: true,
          depth: 1
        });
```

Then *outside* isomorphic-git/browser I push another commit (e.g., I go to GitHub and edit a file and commit).

Then back in my isomorphic-git browser tab to `git.pull` but I can't: running this in the JS Console:
```js
git.pull({fs, dir: 'repo'}).then(x => console.log(x))
```
produces `TypeError: e.committer is undefined` in merge.js:65:2.

If I try to go a different route: I can run `git.fetch` successfully but `git.merge` in isomorphic-git tab fails with a different error.

I understand that only fast-forwards are allowed, but the remote repo on GitHub is only a commit ahead of that in isomorphic-git and should fast-forward.

**Comment by wmhilton** [comment]
Well... that's odd. Oh, hang on I have a theory... I bet findMergeBase chokes on shallow clones because `log` returns an Error for the last commit instead of a GitCommit object.

**Comment by wmhilton** [comment]
Probably would be fixed by https://github.com/isomorphic-git/isomorphic-git/issues/245

**Comment by fasiha** [comment]
Actually no: after I delete everything in Browserfs and do a full clone, `git.log({fs, dir:'repo'}).then(x => console.log(x)).catch(e => console.log('err', e))` prints out a nice-looking length-17 array.

**Comment by wmhilton** [comment]
Hmm, but I bet git.pull works it that case. I'm like 90% sure it must be related to the initial `depth: 1` bit. Either that or you've got magic commits that have no committer. But that was the first thing I checked, and all the commits in `fasiha/test-data` have a committer. So the only reason I can think of why `e.committer is undefined` would be if `e` was not actually a commit.

**Comment by fasiha** [comment]
I wish it were the case! But in the JS Console if I run, right after the above sequence of steps,
```js
git.pull({fs,dir:'repo'}).then(x => console.log('success',x))
Promise { <state>: "pending" }
Using ref=master pull.js:38:4
TypeError: e.committer is undefined[Learn More] merge.js:65:2
```
So Promise is the return value, then "Using ref=master" is printed by pull.js, and then the "e.committer is undefined" in merge.js. Ok, I'll set some breakpoints in the debugger and see if I can narrow it down more and report back. Thanks for your help so far!

**Comment by wmhilton** [comment]
Huh! Well that's weird. Yes, please see if you can figure out what this "e" whose committer is undefined looks like. If it's not a Commit, and it's not an Error... could it be null? Or an unresolved Promise?

Meanwhile, I'll go ahead and fix #245 because that'll make @jcubic happy no doubt.

**Comment by fasiha** [comment]
Ok, here are the values of the two arguments being compared:
```
Object { oid: "3beae9422c24cbfc03d5dcd09034feff662c74d3", message: "Update data.txt\n", parent: (1) […], tree: "dec685cf642a1027780b34422c111af1cc15f2e4", author: {…}, committer: {…}, gpgsig: "-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJbOFZRCRBK7hj4Ov3rIwAAdHIIAIybpEPkWZLa0ZM1pib49plk\nFLXTuUqLrK6hU4FHso//V/+ACtSxzgay+t6WWQRml+LmV/WZPckFyOo5Lbf3inQ5\ng2PYopY1teUMqBxaT2CyHrLaMTZcDImWVgv+WsuLDfKy4hv5GHQYCEWFWB6M+zCQ\nByuB1VdllAX+6AgTfoTOypbhc4ydqriBPEyRIHlNa2+EWCWsmUiv1G9pt0rWh/Y9\nNq0wR7JwN4YETkGPvhU6MPgXQvB8nkOPmhQNKv9V18XIOcZBRseT1eX7ZSN0nO9I\nMXEQxd4HIls69/wt1M4jFaTmt5MutUv+rf/g5z1oo+tl6y4HctJWnrPbx4oIRE4=\n=YuZG\n-----END PGP SIGNATURE-----\n" }
 
Object { oid: "42b3c556d4ecec45cb2124577ee853aab6b30c21", error: ReadObjectFail }
```
The first object is the most recent commit that isomorphic-git had (after the initial clone). The second object however is the 'error', and corresponds to the new commit in origin that isomorphic-git is trying to pull down ([link](https://github.com/fasiha/test-data/commits/master/data.txt)).

So isomorphic-git gets the commit SHA but none of the metadata, only an 'error'?

**Comment by wmhilton** [comment]
Hmm. So it's not a `ReadShallowObjectFail` but a regular `ReadObjectFail`. That's... hmm. This is from `git.pull` right? Git.pull does `fetch` first, so it _should_ have that commit. I wonder why it can't read it.

What do you get if you try 
`await git.readObject({fs,dir:'repo', oid: "42b3c556d4ecec45cb2124577ee853aab6b30c21" })`? Should be the same ReadObjectFail error.

**Comment by fasiha** [comment]
Yes, this is from `git.pull`. And yes, `git.readObject` throws `ReadObjectFail`.

I wonder if it's related to the fact that I can `git.fetch` just fine, but then when I try to `git.merge({fs,dir:'repo'}).then(x=>console.log('success',x))`, I get an error: `TypeError: r is undefined`, with sourcemap pointing to `GitRefManager.js:112:8`, which is nonsense because that line just has `let sha`, all by itself.

**Comment by wmhilton** [comment]
I'll have to test this more thoroughly this week. I'll figure it out, I promise. This is too basic and important a task to have not working!

**Comment by wmhilton** [comment]
I did discover a bug in `git.merge` though as a result of this. If the full paths (e.g. `refs/heads/master`) weren't specified, it could end up writing the result of the merge to the wrong place (e.g. `.git/master` instead of `.git/refs/heads/master`).

**Comment by wmhilton** [comment]
Possibly linked to #243

**Comment by fasiha** [comment]
So I tested this today with latest npm-published version, both with isogit CLI utility and browser, and everything worked as expected!

**Comment by wmhilton** [comment]
That's fantastic! Thanks for re-testing this! (I bet it was that bug in git.merge I fixed.)
