### ISSUE TITLE
resolve annotated tag

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#306]
See #15. Don't worry about [ creating / reading / deleting ] tags just yet. Just be able to parse them enough so that `resolveRef` can do its job, so that @mojavelinux can do his tree walking.

**Comment by mojavelinux** [comment]
Exactly! I just need to find the tree when a user specifies a tag to start from.

**Comment by wmhilton** [comment]
Current state of affairs: `resolveRef` still gives you the OID for the tag object itself (which is what `git-show-ref` does without the `--dereference` option):

```sh
> isogit resolveRef --ref=v0.0.9
>> git.resolveRef({fs, dir: '.', "ref":"v0.0.9"})
"6e90dfd7573404a225888071ecaa572882b4e45c"
```
but now you can either read that parsed tag object:

```sh
> isogit readObject --oid=6e90dfd7573404a225888071ecaa572882b4e45c
>> git.readObject({fs, dir: '.', "oid":"6e90dfd7573404a225888071ecaa572882b4e45c"})
{
  "type": "tag",
  "format": "parsed",
  "object": {
    "object": "af4d84a6a9fa7a74acdad07fddf9f17ff3a974ae",
    "type": "commit",
    "tag": "v0.0.9",
    "tagger": {
      "name": "Will Hilton",
      "email": "wmhilton@gmail.com",
      "timestamp": 1507071414,
      "timezoneOffset": 240
    },
    "message": "0.0.9",
    "signature": "-----BEGIN PGP SIGNATURE-----...-----END PGP SIGNATURE-----\n"
  },
  "source": "./objects/pack/pack-1a1e70d2f116e8cb0cb42d26019e5c7d0eb01888.pack",
  "oid": "6e90dfd7573404a225888071ecaa572882b4e45c"
}
```

and then do something with the `"object": "af4d84a6a9fa7a74acdad07fddf9f17ff3a974ae"` property, or since annotated tags are "tree-ish", you can use the `filepath` option of `readObject` to go straight to a particular file:

```sh
> isogit readObject --oid=6e90dfd7573404a225888071ecaa572882b4e45c --filepath=README.md --encoding=utf8
>> git.readObject({fs, dir: '.', "oid":"6e90dfd7573404a225888071ecaa572882b4e45c","filepath":"README.md","encoding":"utf8"})
{
  "type": "blob",
  "format": "parsed",
  "object": "# isomorphic-git .... tually the lowest level building blocks.\n",                                       
  "source": "./objects/pack/pack-b4dd2a8714ef8fc8b0cecb58252132df06bf2ce8.pack",   
  "oid": "19c89db9ab4dfa5e3fbf4dd059e0102bf056a53a"                                
}
```

I haven't updated other functions besides readObject though, so things like `isogit checkout --ref=v0.0.9` probably don't work.

**Comment by mojavelinux** [comment]
As long as there is a path to the information, I'm sure I can get it to work. Is there any way to know it's an annotated tag and not a lightweight tag? I'm thinking about the conditional logic I'll need to dereference it.

**Comment by wmhilton** [comment]
> Is there any way to know it's an annotated tag and not a lightweight tag?

Nope, not until you try to read it. A lightweight tag will resolve to an OID that is for a `commit`. An annotated tag will resolve to an OID that is for a `tag`. From just the OID you can't tell what type of object it is. But that's OK because you don't need to know ahead of time; you can call `readObject` on the OID and then examine `type` - if it's `"commit"` it must have been a lightweight tag; if it's `"tag"` then it must have been an annotated tag.

**Comment by mojavelinux** [comment]
That's exactly the information I was looking for. Thanks! I'm going to give this a try shortly.

**Comment by wmhilton** [comment]
Basically, check the return type. If it's "tag" instead of "commit", try again. In theory, more than once.

(In practice, I might be the only person crazy enough to create tags pointing to tags.)

**Comment by mojavelinux** [comment]
I just tested it and it works great!

The only think I'm not sure about is this property:

```
  "object": {
    "object": "af4d84a6a9fa7a74acdad07fddf9f17ff3a974ae",
```

It seems more logical that it would be object.oid instead of object.object. Would you agree? Or is it because we don't know what type the sha actually is?

**Comment by mojavelinux** [comment]
Another option might be commitish, which is defined to be a commit or a tag.

**Comment by wmhilton** [comment]
Dan my man, you make too much sense. Alas, I didn't choose the names - those are the header fields "as written" in the annotated tag plain-text format.

```sh
> git cat-file -p v0.0.9
object af4d84a6a9fa7a74acdad07fddf9f17ff3a974ae
type commit
tag v0.0.9
tagger Will Hilton <wmhilton@gmail.com> 1507071414 -0400

0.0.9
```

I do think `oid` makes a little more sense here. Particularly since `readObject` uses "object" to hold the contents of the object, but yes, I think it's because we don't know what type the sha is.

I think for now I want to leave it as is. Renaming header fields might ultimately cause problems, for instance if some git client inserts an actual header value called "oid".

**Comment by mojavelinux** [comment]
You're always a wealth of information. I'm learning more about git from you each day. Since you're matching what the plain-text format returns, then it makes sense to maintain that compatibility. It might be something to mention in the type information.
