### ISSUE TITLE
Allow tags to be skipped when cloning

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#307]
The fetch function has an option to control whether tags are fetched. However, the clone function currently does not. This issue proposes adding support for the `tags` option to the clone function. When set to false, it emulates the `--no-tags` option flag of `git clone`. When set to true, it matches the current behavior.

To match git conventions, the `tags` option on the clone function should default to `true` (the opposite of the fetch function).

**Comment by wmhilton** [comment]
Sadly, you run into issues if you start making optional arguments default to `true`. For instance, it breaks the CLI which uses `minimist` which treats "present" as truthy and "absent" as false. I'm all for self-consistency... but at this point my goal is to be consistent with git. Git is not self-consistent so it's painful sometimes.

I already have two negative options: `noCheckout` and `noGitSuffix` (boy that one was painful... see https://github.com/isomorphic-git/isomorphic-git/issues/199 for the story of how I ended up adding that one) so it will be `noTags` lol. Trust me it's more painful for me than it is for you. 😛

**Comment by mojavelinux** [comment]
Sounds reasonable to me.

**Comment by mojavelinux** [comment]
Thanks @wmhilton!
