### ISSUE TITLE
CodeCommit push issue

### ISSUE THREAD

**Issue by sigmaidetest** [isomorphic-git/isomorphic-git#310]
First of all, really appreciate this work here... A detailed set of docs as well. 
I encountered the issue #199 too and with a bit of struggle, I was able to find the fix through the comments. Better to update the docs :P

Now, I'm having an issue with trying to push into an AWS CodeCommit repository. Appended '.git' to the URL can be avoided with the same 'noGitSuffix' attribute. However, still getting an error when pushing the diff into the repo.

```
Push Err: GitError: Unparsable response from server! Expected "unpack ok" or "unpack [error message]" but received "".
    at Object.push (http://localhost:9000/static/js/bundle.js:51956:13)
```

The network call

```
POST
https://cors-buster-tbgktfqyku.now.sh/git-codecommit.us-east-1.amazonaws.com/v1/repos/repo/git-receive-pack
Content-Type: application/x-git-receive-pack-request
```

receives a response with a payload as follows.

```
00a5fd1d95348a7aad98f2308fd4f54f81305337a5b9 558e43bc835aa738c8b46875ea359a4cfc36c745 refs/heads/master report-status side-band-64k agent=git/isomorphic-git@0.19.9
0000PACK
xËA
B!á½§p<ÔÑ§BDh×Æ73d=lWhõÃf»¡@DÐ	lRZnÔJ«<PWÀÕì8ø©VÈSMfDªejW¢¤(ÅKS«?z{
{Ëßj}èì¿Ø÷/Û«¬Oà2
Ñ¦tfÞ~WåA"Kæ"Í>¢x340031QrutñuÕËMa8Z÷?ôõ£Å¬¾~×^ST¦óå!DPrîìdë²ìÊlÔüPe²ûm/ikÉ<xóHÍÉÉWÏ/ÊIQI>1xKee` ÄÊüöÔk{Æå²< ã
```

Any suggestion?

**Comment by wmhilton** [comment]
Probably CodeCommit isn't reporting the status... I don't think my response parser currently takes into account whether the server asserts the `report-status` capability.

What's the output of [`getRemoteInfo`](https://isomorphic-git.github.io/docs/getRemoteInfo.html) for that repository? The refs and symrefs don't matter, just the `capabilities` array.

**Comment by wmhilton** [comment]
> Better to update the docs :P
Done

**Comment by sigmaidetest** [comment]
Can't execute a `getRemoteInfo` for the repository. I suppose the `noGitSuffix` attribute should be added for that as well because the repository URL is appended by a '.git' in there.

**Comment by jchamath** [comment]
Can't execute a `getRemoteInfo` for the repository. I suppose the `noGitSuffix` attribute should be added for that as well because the repository URL is appended by a '.git' in there.

**Comment by wmhilton** [comment]
FML I completely forgot about that.

**Comment by wmhilton** [comment]
Hmm. It appears that the CodeCommit repo I'm testing against _does_ list the `report-status` capability. So... hmm.

**Comment by sschadwick** [comment]
Also encountering this error when attempting to push to CodeCommit

**Comment by wmhilton** [comment]
I'll have to keep investigating then!

**Comment by sschadwick** [comment]
```javascript
let info = await git.getRemoteInfo({
  noGitSuffix: true,
  username:    'username',
  password:    'password',
  url:         'https://git-codecommit.us-west-2.amazonaws.com/v1/repos/myrepo'
})
console.log(info) // { capabilities: [] }
```

**Comment by wmhilton** [comment]
Are you pushing to an empty repo or one that already has a master branch?

**Comment by sschadwick** [comment]
Pushing to an empty repo, context is backing up repos across git providers
