### ISSUE TITLE
The README still mentions the CORS buster

### ISSUE THREAD

**Issue by TomasHubelbauer** [isomorphic-git/isomorphic-git#312]
If your CORS buster source is up, we should link to it instead so that people know to run it locally.

**Comment by wmhilton** [comment]
Funny I was just working on [fixing the website](https://isomorphic-git.github.io/blog/2019/07/05/cors-proxy-disabled.html). I'm mentally exhausted. Can you make a PR for the README?

**Comment by TomasHubelbauer** [comment]
Yeah I will and I will also take a look at why there's not line breaks on that page (at least in my Firefox).
