### ISSUE TITLE
CodeCommit Pull/Fetch/Merge Error

### ISSUE THREAD

**Issue by braindx** [isomorphic-git/isomorphic-git#315]
Hi, using Node.js 8.11.3 and isomorphic-git 0.21.0 with a CodeCommit repository and I'm encountering a couple of issues:

1. When issuing a pull, the noGitSuffix doesn't appear to be respected so I get a 404 when working with a CodeCommit repo.

2. If I clone using isomorphic-git, then commit a new revision from a different machine using canonical Git, and then fetch using isomorphic-git it puts my .git folder in a state that the canonical Git client doesn't like.  For example, if I try to subsequently fetch using the canonical client I get:
error: refs/remotes/origin/HEAD does not point to a valid object!
error: refs/remotes/origin/development does not point to a valid object!
Attempting to merge refs/remotes/origin/development into refs/heads/development after that using isomorphic-git results in the following error:
TypeError: Cannot read property 'timestamp' of undefined

**Comment by wmhilton** [comment]
I can definitely work on # 1 by adding a `noGitSuffix` to pull.  For point # 2 I am probably going to need more information to figure out. I haven't encountered something like that before!

**Comment by braindx** [comment]
Happy to provide whatever information I can that you think might help narrow it down. I'm testing on a CodeCommit repository that has only a single file in it and any fetch with isomorphic-git (provided there's something new to fetch) seems to break the repo.

**Comment by braindx** [comment]
I've created a test app to reproduce the issue as simply as possible. Contained within app.js you can find credentials for a test CodeCommit repository I've set up. Run the app, use those credentials to modify the repo, and then run the app again and you will see the issue. Let me know if there's anything else I can do to help. This app was built using Node.js v8.11.3.
 
[testapp.zip](https://github.com/isomorphic-git/isomorphic-git/files/2168786/testapp.zip)

**Comment by wmhilton** [comment]
THANK YOU that was AWESOME @braindx . Man I wish all bug reports came so nicely packaged.

I and my [mitmproxy](https://mitmproxy.org/) have found the issue! It's an odd one. CodeCommit will hang up with a 200 OK but empty body if the fetch request does not have a `Content-Length` header. I will have a fix released tomorrow! :)

Meanwhile, does anybody know if _pushing_ to CodeCommit works? If it requires a Content-Length header I'll need to rework how I do pushes so it saves the packfile to disk before sending it.

**Comment by wmhilton** [comment]
fun fact: my `merge` command does not do a checkout afterwards. I wonder if that's a bug.

**Comment by braindx** [comment]
Haha, no problem, I agree. Easy repro is the key to success! Awesome that you were able to track it down so quickly. Really appreciate you taking the time.

I haven't tried pushing with CodeCommit but I don't think my particular use case requires it (famous last words).

Also, good to know about the merge not doing a checkout afterwards. I'll look out for that. Thanks again!
