### ISSUE TITLE
Set core.bare config value to true when repository is cloned with noCheckout: true

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#332]
When a repository is cloned with the `noCheckout: true` option, the config value `core.bare` should be set to `true`. This is consistent with the behavior of the native git client.

```
$ git clone --bare https://github.com/isomorphic-git/isomorphic-git.git
  cd isomorphic-git.git
  git config --get core.bare
# true
```

**Comment by wmhilton** [comment]
Alrighty... just looked into this and (as usual with git) it's not _quite_ that simple.

The `noCheckout: true` option is supposed to be correspond to the [`--no-checkout` aka `-n`](https://git-scm.com/docs/git-clone#git-clone---no-checkout) flag, e.g. 

```
$ git clone --no-checkout https://github.com/isomorphic-git/isomorphic-git
  cd isomorphic-git
  git config --get core.bare
# false
```

The [`--bare`](https://git-scm.com/docs/git-clone#git-clone---bare) flag has slightly more complicated behavior. Quoting from the docs, this first part is indeed similar to the result achieved using `git.clone({gitdir, noCheckout: true})`:

> Make a bare Git repository. That is, instead of creating `<directory>` and placing the administrative files in `<directory>/.git`, make the `<directory>` itself the `$GIT_DIR`. This obviously implies the `-n` because there is nowhere to check out the working tree. 

However the paragraph continues,

> Also the branch heads at the remote are copied directly to corresponding local branch heads, without mapping them to `refs/remotes/origin/`. When this option is used, neither remote-tracking branches nor the related configuration variables are created.

which can be seen in the config files...

```ini
# bare clone config
[core]
        repositoryformatversion = 0
        filemode = false
        bare = true
        symlinks = false
        ignorecase = true
[remote "origin"]
        url = https://github.com/isomorphic-git/cors-proxy
```

```ini
# no-checkout clone config
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
[remote "origin"]
        url = https://github.com/isomorphic-git/cors-proxy
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

So my conclusion, for what it's worth, is that `noCheckout: true` is doing the right thing. So I'll probably close this issue as `invalid`. BUT... it logically segues into a feature request for a `git.clone({bare: true})` that would truly be equivalent to `--bare` if somebody feels strongly about that.

**Comment by mojavelinux** [comment]
I always learn so much from you @wmhilton. Thanks for taking the time to explain this. I never knew before there was a difference between no-checkout and bare. Now I do. And it also explains why I was noticing a difference between the references in a bare repository cloned by git and the references in a repository cloned by isomorphic-git using noCheckout: true.

I would be interested in a bare option, though I'm going to see how far I can get with noCheckout: true. It might just be the thing I'm looking for anyway. Main main goal is just to save the time creating a worktree I'm not going to use.
