### ISSUE TITLE
Cors Error

### ISSUE THREAD

**Issue by hjiayz** [isomorphic-git/isomorphic-git#334]
browser:firefox
gitserver:gogs
webserver:webpack dev server

gogs/custom/conf/app.ini 

`[http]
ACCESS_CONTROL_ALLOW_ORIGIN = http://localhost:3000`

error message:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5000/myrepo/newtest.git/info/refs?service=git-upload-pack. (Reason: missing token ‘user-agent’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5000/myrepo/newtest.git/info/refs?service=git-upload-pack. (Reason: CORS request did not succeed).
Error: "XHR error"`

Response headers Status code:200

`
Access-Control-Allow-Headers | Content-Type, Authorization
`

Request headers

`Access-Control-Request-Headers | authorization,user-agent`

**Comment by wmhilton** [comment]
Looks like your Gogs is whitelisting localhost:3000 but your server is running on port 5000

**Comment by hjiayz** [comment]
finished.
proxy by nginx.
nginx server config:
    server {
        server_name localhost;
        listen 4000;
        #ssl on;

        location / {
            proxy_pass http://localhost:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 90;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS';
            add_header Access-Control-Allow-Credentials 'true';
            add_header Access-Control-Allow-Headers 'Accept, Authorization,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
            if ($request_method = 'OPTIONS') {
               add_header 'Access-Control-Allow-Origin' *;
               add_header 'Access-Control-Max-Age' 1728000;
               add_header 'Access-Control-Allow-Credentials' 'true';
               add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE, PUT, OPTIONS';
               add_header 'Access-Control-Allow-Headers' 'Accept, Authorization,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
               add_header 'Content-Type' 'text/plain charset=UTF-8';
               add_header 'Content-Length' 0;
               return 204;
           }
        }
    }
