### ISSUE TITLE
_listpack - doesn't call "push" if numObjects === 0

### ISSUE THREAD

**Issue by niegowski** [isomorphic-git/isomorphic-git#336]
if `numObjects` is 0 then push is never called and `GitPackIndex.fromPack` never resolves Promise

https://github.com/isomorphic-git/isomorphic-git/blob/9fa17e64c0b7845ac37193cba611551078728d90/src/utils/git-list-pack.js#L34

**Comment by niegowski** [comment]
this happens to me when i pull from remote repo (github wiki) and there is no changes

**Comment by wmhilton** [comment]
I'm having trouble replicating this. I know earlier versions of `isomorphic-git` would incorrectly save a blank (0 bytes long) packfile when a fetch returned no changes, and it would get stuck on those 0 length files. However I don't think that happens anymore.

However, you are right that this code isn't robust enough - we can't have the failure case go into an infinite loop! That's just bad. I'll make sure this code exists properly even for corrupt packfiles.

**Comment by wmhilton** [comment]
It now makes sure that `numObjects` > 0 before entering the loop. (as well as a bunch of other sanity checks that should help diagnose corrupt packfiles)
