### ISSUE TITLE
New feature: list git remotes

### ISSUE THREAD

**Issue by hsablonniere** [isomorphic-git/isomorphic-git#345]
Hey,

I would like a new command to list git remotes.
It seems like the whole list is already in the config file.

WDYT?

**Comment by hsablonniere** [comment]
@wmhilton I tried to tackle this one.

It seems that the current GitConfig won't allow us to list all named sections remote.

Should we add a new getter like `getSections('remote')` that could return this:

```js
{
  origin: {
    url: 'https://...'
  },
  clever: {
    url: 'https://...'
  }
}
```

**Comment by hsablonniere** [comment]
I was also wondering about the form of the return of `listRemotes`...

I think it should be an array with name and urls like this:

```
[
  { name: 'origin', url: 'https://...' },
  { name: 'clever', url: 'https://...' },
]
```

**Comment by wmhilton** [comment]
> I think it should be an array with name and urls like this:

What about instead of `name` use `remote`? Just because that way it's the same as the `remote` parameter used in `fetch` and `push`. E.g.

```js
[
  { remote: 'origin', url: 'https://...' },
  { remote: 'clever', url: 'https://...' },
]
```
