### ISSUE TITLE
AssertServerResponseFail if target repo is dumb HTTP

### ISSUE THREAD

**Issue by Curtis-Fletcher** [isomorphic-git/isomorphic-git#360]
This is testing in the browser using the bundles suggested in the quickstart.

If issuing a clone to a remote git repo set behind a dumb HTTP server (AKA not one running the git CGI, as long as "git update-server-info" has been run on the repo) the official git binary has no problem cloning even when "GET /.git/info/refs?service=git-upload-pack" returns the refs file rather than CGI-generated content.

However isomorphic-git dies with an assertion error ("AssertServerResponseFail") in "GitRemoteConnection" because the response body doesn't start with "# service="...

If this is unsupported use, that's fine, I just wanted to mention it in case it was new information.

**Comment by wmhilton** [comment]
Unfortunately the "dumb" HTTP protocol isn't supported at this time. But we should replace that error with a nicer one explaining that only the "smart" HTTP protocol is implemented.
