### ISSUE TITLE
Git status shows .png files modified directly after clones.

### ISSUE THREAD

**Issue by NasonLee** [isomorphic-git/isomorphic-git#362]
Please be sure to mention:
- whether you are using Node or the Browser
- how you are using it (if you are using a bundler what bundler; if you are using a `<script>` tag what CDN URL)

A1: I use Node.
A2: 
```
const git = require("isomorphic-git");
let repo = {fs, dir: PATH}
function gitClone(){
     git.clone({
         ...repo,
        url: REPOSITORY_URL,
        username: username,
        password: password,
        singleBranch: false,
   });
}
```

When I do this command.
$ git status

results as follow:
        modified:   zzz/images/icon-128.png
	modified:   xxx/yyy/zzz-16.png
	modified:   rrr/xxx/nee/images/su.png
	modified:   tt/cccc/ssss/image/icon-16.png

All my images  were modified, but I didn't change any file.
I feel unsure about it. Can anyone tell me that? 
Tnanks.

**Comment by wmhilton** [comment]
That is... interesting!

a) ARE the files actually modified / corrupted (e.g. some bug in my code that saves files to disk) or does git merely THINK they are modified (which could be a bug in my .git/index code)? 
b) Is it only PNG files that do this or all file types?

Also... are you on Windows, Mac, or Linux? Maybe it's a file mode thing.... 🤔

**Comment by NasonLee** [comment]
a) well...actually, i don't know whether the PNG files is really modified. But when i open these files, they look as usual. Using `$diff`  still got no difference. 
b) Yes, it is only PNG files do this. And I find not all the images show this status. That's weird.
I am on macOS.

**Comment by wmhilton** [comment]
Is this a public git repository? I've got a MacBook, so I could try cloning it and see if it happens on my machine too.

**Comment by NasonLee** [comment]
Nope... it's our group private repository. How can i do ? :(

**Comment by wmhilton** [comment]
Does the following fix it?
```sh
$ rm .git/index
$ git reset
$ git status // should be back to normal
```

If so, then I'll know for sure it is a bug in the index file.

**Comment by wmhilton** [comment]
Ah! Alright then. I fixed some bugs in the .git/index code while working on #355 so once that is merged let's try again and see if that makes the problem go away. I suspect it's storing the file mode incorrectly (that was my problem implementing `git status` anyway).

**Comment by NasonLee** [comment]
OK~ Great! Thank you a lot .
https://drive.google.com/file/d/1PcnZvmHia4RYlMkJewAHN5nzPRYLI6vR/view?usp=sharing
The upside pic is my original files. And the bottom one is using <isomorphic-git> to clone my repository. 

Does I just wait for merge?

**Comment by wmhilton** [comment]
Yup! I just need a couple more days to polish the code and update the docs before I merge it.

**Comment by NasonLee** [comment]
Hi, how can i test this version? Thanks!

**Comment by wmhilton** [comment]
It's on npm. The latest version should still be compatible with your existing code.

**Comment by NasonLee** [comment]
@wmhilton The problem is solved! You are a kind person. Thank a lot :)
