### ISSUE TITLE
Allow Experimental Features?

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#366]
I'm thinking about merging #355 as-is but label the `walk` function as "beta" or "experimental", because as I build out `merge` and other features that might rely on `walk` I might realize I need to change it.

So far I've avoided including any experimental features in order to adhere strictly to semver. But lots of successful projects (Node, React) don't strictly adhere to semver, and they sometimes expose unstable "experimental" features. Plus if I don't expose experimental features to let people use them until I've decided the API is perfect, I can't get any feedback about experimental features.

Thoughts?

**Comment by noppa** [comment]
Why not just increment the major version number when the experimental api changes? That might happen frequently and the version might soon end up being 142 or something, but who cares? There are plenty of integers to go around.

**Comment by wmhilton** [comment]
> Why not just increment the major version number when the experimental api changes?

That'll create a headache for maintainers using isomorphic-git in production who only care about stable API features. Every time an experimental API changes, they'll have to check the changelog to see if any of the _stable_ features they use changed.

**Comment by wmhilton** [comment]
I ended up making a clever(?) compromise: I included an experimental `walk` command but named it `walkBeta1`. The API for `walkBeta1` will adhere to semver but if I need to totally revamp how it works, I'll just make a new function `walkBeta2`.

In this style of development / code evolution, "major" releases will simply consist of dropping deprecated functions to clean up the codebase.
