### ISSUE TITLE
Support --unshallow on fetch

### ISSUE THREAD

**Issue by mizchi** [isomorphic-git/isomorphic-git#370]
I use IndexedDB backend. Browser storage's quota is restricted up to 6% of user storage(HDD/SSD).  https://developer.chrome.com/apps/offline_storage

I want to reduce cloned data volume so I use `{ singleBranch: true, depth: 1 }` at first to show rapidly. But users need history later by `git fetch <ref> --unshallow`

```
# man git-fetch
       --unshallow
           If the source repository is complete, convert a shallow repository to a complete one, removing
           all the limitations imposed by shallow repositories.

           If the source repository is shallow, fetch as much as possible so that the current repository
           has the same history as the source repository.
```

---

P.S. `git.clone` looks unstable yet. It's one of reason I use `singleBranch, depth: 1`. Some tree objects are broken after clone (or not implemented format?). Do you plan to improve them after https://github.com/isomorphic-git/isomorphic-git/pull/138 ?

**Comment by wmhilton** [comment]
The fast and dirty solution is just use really big depth, like `{depth: 1000000000}`.

What I would actually recommend would be the following:
- Start with `{ singleBranch: true, depth: 1 }`
- Then fetch with `{ depth: 100, relative: true }` which will grab the previous 99 commits
- Then repeat fetching with `{ depth: 100, relative: true }` as needed until you have the full history. You can tell you have the full history indirectly by a couple of means... probably the easiest would just be `git.log` and when the array returned stops growing in length.

This gives you a well-behaved, paginated method for lengthening the git history as needed!

A slightly more efficient way of telling if you have the full history, would be to grab the oid from the last commit returned by `git.log` and use that as the starting point for the next call to `git.log` with `{ ref: oid }` and keep repeating until git.log only returns one commit. Or you could use the `'progress' event emitter` in `fetch` and if the fetch completed successfully with 0 progress events, I think that would indicate there's no more to fetch. 

As for broken tree objects after clone... this is unusual! If they were created by isomorphic-git then maybe they are faulty git objects themselves. Or maybe there is some yet undetected problem with cloning. But there are not any bugs _that I am aware of_ but @jcubic and @TomasHubelbauer have run into similar sounding bugs before.

**Comment by mizchi** [comment]
Thank you! I use that work around at first.

My clone way is here.  I can not trust clone promise now...

https://github.com/mizchi/next-editor/blob/301cc30c82fef61717b26eef4e70a88bef2526e5/src/domain/git/commands/cloneRepository.ts

And I will report known error cases later as other issue. I encountered many errors on my developing next-editor.app

**Comment by wmhilton** [comment]
next-editor.app is AWESOME! I may start using this too. And I am happy to hear about bugs you find - I spend so much time _writing_ isomorphic-git I barely get to _use_ it. It is projects like [next-editor](https://next-editor.app/) and [Git Web Terminal](https://jcubic.github.io/git/) that really battle-test the library and find the bugs.

**Comment by wmhilton** [comment]
Added to the FAQ! https://isomorphic-git.org/docs/en/faq

**Comment by jcubic** [comment]
Should you add next-editor to list of projects then? @mizchi maybe you should add PR with this file update https://github.com/isomorphic-git/isomorphic-git.github.io/edit/source/website/users.js
