### ISSUE TITLE
listFiles 

### ISSUE THREAD

**Issue by akaJes** [isomorphic-git/isomorphic-git#377]
node -v v8.11.1
isomorphic-git@v0.28.2
any git repository
```
echo "require('isomorphic-git').listFiles({ fs: require('fs'), dir: '.' }).then(console.log)" | node
rm .git/index
git reset
echo "require('isomorphic-git').listFiles({ fs: require('fs'), dir: '.' }).then(console.log)" | node
```
after this commands the result unpredictable - file names become ruined
just compare first and last listFiles results

**Comment by wmhilton** [comment]
Nope, not related to recent changes. Problem is present in old versions of isomorphic-git. Has to do with `git` - `git reset` results in a very different-looking index than `git checkout`.

It seems to be happening when the files in the working directory have been modified and don't match the ones in the index. `git reset` is inserting a lot more nulls where I normally see data.

**Comment by wmhilton** [comment]
OK try with version 0.28.3
