### ISSUE TITLE
Esdoc doesn't parse "push" command correctly

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#38]
See https://isomorphic-git.github.io/isomorphic-git/function/index.html#static-function-push

Edit: fixed the URL because the repo moved to an org

**Comment by wDhTIG** [comment]
That link gives me a 404.

**Comment by wmhilton** [comment]
I'm gonna close this because I'm heavily leaning towards migrating from [ESDoc](https://esdoc.org) to [docusaurus](docusaurus.io). I liked the idea of having the documentation right there in the source code, but the reality is it has made things more complicated to maintain.
