### ISSUE TITLE
moveBranch

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#39]

**Comment by erdahuja** [comment]
can you help me implement any one of the features? like reset, move etc It's my first commit.

**Comment by wmhilton** [comment]
I'm visiting my parents this weekend (it's Father's Day in the USA) so I can't directly help today, but if you give it a shot and get stuck you can ask questions!

**Comment by mojavelinux** [comment]
I case could be made either way, but I think renameBranch would be a more fitting name. (Both terms are used in the git documentation, but what's really happening is that the branch is getting a new name. Plus, the name of the operation in Node's fs module to rename/move a file is "rename". So the terminology might be expected.)

**Comment by crutchcorn** [comment]
I think `renameBranch` would be ideal as well. I'd like to take on development for this issue, but don't know where to start in terms of reference for how to actually implement this logic. I'll take a look through the `createBranch` logic, but will ping here if/when stuck

**Comment by crutchcorn** [comment]
I decided I would do an experiment and simply clone two of the exact same repo, then locally rename the `master` branch to `main` in one of them, then use SmartSyncronize to compare and contrast the difference between the two.

It seems like the following actions need to be done:

1) Change the `config` branch name
2) Change the `head` ref
3) Move the `ref/heads` old branch name file to a file with the new branch name

I'll read through the codebase to see what code is already present and what code needs to be written
