### ISSUE TITLE
noCheckout crashes `git log`

### ISSUE THREAD

**Issue by vmarkovtsev** [isomorphic-git/isomorphic-git#394]
The following code crashes in the browser:

```js
await git.clone({
    dir,
    corsProxy: 'https://cors.isomorphic-git.org',
    url: 'https://github.com/src-d/hercules',
    noCheckout: true
});

await git.log({dir});
```

```
Uncaught (in promise) u: Could not resolve reference "refs/heads/master"
```

**Comment by wmhilton** [comment]
Oops! Sorry @vmarkovtsev. Good bug find! Meanwhile, you can use this workaround:

```js
await git.log({ dir, ref: 'origin/master' })
```

* * *

Note to self: This works in canonical git:
```sh
git clone --no-checkout https://github.com/isomorphic-git/isomorphic-git
cd isomorphic-git
ls # empty
git log # works
```
It appears that it still writes `.git/HEAD` and `.git/refs/heads/master` _as if_ you had checked out the branch, it just doesn't write the files to the working directory. (Which puts all the files in a "deleted" status which is weird, but hey whatever.)
