### ISSUE TITLE
How to use corsProxy parameter

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#400]
I've got 401 error when using credentials plugin and It asked for host jcubic.pl instead of github.com so I added this:
```javascript
await git_wrapper.push({
  dir,
  corsProxy: 'https://jcubic.pl/proxy.php?', // without question mark it also don't work
  ref: branch,
  //authUsername: credentials.username,
  //authPassword: credentials.password,
  emitter
});
```
and I edited .git/config to have just github url but got error when push:

> AssertServerResponseFail: Expected "# service=git-receive-pack\n" but got "".

the proxy script is working becasue I can open https://jcubic.pl/proxy.php?https://github.com

**Comment by wmhilton** [comment]
yay! we're duplicating work and discovering the same bugs lol see https://github.com/jcubic/git/pull/6

**Comment by wmhilton** [comment]
Long story short: our proxies work slightly differently:
- `https://cors.isomorphic-git.org/github.com/isomorphic-git/isomorphic-git`
- `https://jcubic.pl/proxy.php?https://github.com/isomorphic-git/isomorphic-git`

But I have updated the `corsProxy` option now to handle both styles.

**Comment by wmhilton** [comment]
> I've got 401 error when using credentials plugin and It asked for host jcubic.pl instead of github.com 

Another option is instead of passing in `{ protocol, host, path?}` I could just pass unparsed `url`. Then you could parse the URL yourself and strip off the `https://jcubic.pl/proxy.php?` bit if it is there.

I think the canonical git parses the URL for you really as a convenience. But URL parsing in JavaScript is as simple as `let parsed = new URL(url)` so there's not a lot of point to it.

**Comment by wmhilton** [comment]
Screw it. I kept having to mangle `{protocol, host, path?}` into a single value anyway so it was simple enough to use a key/value store for passwords. Unless you can think of a reason to keep it, I'll change it to just `fill({url})`, `approved({url, auth})`, and `rejected({url, auth})`. It seems simpler.
