### ISSUE TITLE
listRemoteBranches

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#46]
From #43
> Currently, the listBranches function only looks for heads. Could you add a function that lists remote branches (or all branches?).

I think... add a `listRemoteBranches` function that takes a `remote` argument that defaults to undefined, and returns all remote branches, or if `remote` is specified returns just the branches in that remote.

**Comment by mojavelinux** [comment]
I think you could avoid the extra function by allowing the `remote` property to be specified for `listBranches`.

```js
const branches = await git.listBranches({
  fs,
  dir,
  remote: 'origin'
})
```

If you don't specify a remote, then it returns local branches (as it does now).

**Comment by wmhilton** [comment]
added in v0.2.0

**Comment by mojavelinux** [comment]
Thanks!

**Comment by mojavelinux** [comment]
I just tested these changes and they work great!

My only feedback is that I'm wondering whether HEAD should be returned when listing branches. git does show it when you run `git branch --list -a origin/*`. However, nodegit does not include it in the list of references. It's easy enough to exclude, so it's up to you what you think is right.

**Comment by wmhilton** [comment]
Hmm. I agree it's a little weird, but a remote HEAD actually indicates the "default branch" if you clone without specifying a branch. And it is technically there in `refs/remotes/origin` on the local machine as well. (Although probably in `.git/packed-refs` rather than actual `.git/refs`.) I think I'd rather users complain that I'm giving them too much vs too little... although I can't think of a single reason you would want "HEAD" to be listed in that output. Unless there's a case when it might *not* return "HEAD"? Hmm.

When in doubt, I'll go with git's behavior. It's quirky but we all have it so it's a good reference. `git branch --list -a` shows it, so I guess I will too.

**Comment by mojavelinux** [comment]
I agree with this logic.

I can't seem to figure out when git puts the HEAD file in refs/remotes/origin. When I clone using `git clone`, it's always there. However, repositories I have cloned on my machine previously don't have this file. Perhaps there was a change in git at some point that it started creating this file. I'm feeling pretty confident this conclusion is correct.

Interesting to note that nodegit does not create the HEAD file when cloning. That would appear to be the old behavior.
