### ISSUE TITLE
Can I retrieve a blob from a tree?

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#48]
Is it possible to retrieve a blob from a tree? My use case is that I want to be able to grab files out of the git repository without checking out the branch. This allows me to extract files from branches in the repository without affecting the worktree.

I'm looking for something to replace this nodegit operation: http://www.nodegit.org/api/tree_entry/#getBlob

Here's an example:

```js
const fs = require('fs')
const git = require('nodegit')

async function entryToFile (entry) {
  const blob = await entry.getBlob()
  const contents = blob.content()
  const stat = new fs.Stats()
  stat.mode = entry.filemode()
  stat.size = contents.length
  return { path: entry.path(), contents, stat }
}

const dir = 'isogit'
const branchName = 'develop'

;(async () => {
  const repo = await git.Repository.open(dir)
  const walker = (await(await repo.getBranchCommit(branchName)).getTree()).walk()
  const files = await new Promise((resolve, reject) => {
    const collector = []
    walker.on('entry', (entry) => collector.push(entryToFile(entry)))
    walker.on('error', (err) => reject(err))
    walker.on('end', () => resolve(Promise.all(collector)))
    walker.start()
  })
  files.forEach((file) => console.log([file.path, file.stat.size]))
})()
```

I would also need a way to get a list of files from a branch without checking it out. I don't really need a walker. Just a flat list of files in the branch would suffice.

**Comment by wmhilton** [comment]
Hmm. You're definitely doing more low-level individual git object stuff than the fluffy API was intended for. You might have more luck using the `GitObjectManager` directly. I didn't expose any of the managers in the current API, but I *am* pretty confident that it's API (read, write, and hash) is set in stone.

Ah but yes, you'd need the GitTree model to find the SHA for the blob... and then the GitCommit model to get the tree SHA... well I guess `git.log` returns a parsed GitCommit but that's a wee bit awkward. Yeah... I see where an API for exploring the git repo without checking out files would have a serious speed advantage - this project has taught me that file system operations are SLOW. (And error prone.)

And... yes, I see it could be useful for designing "super-features", e.g. doing meta-operations on a git repo that require lots of information about the guts (branches, commits, tags) before transforming the working directory somehow. Currently most commands are just that: actual commands that influence the working directory directly.

It looks like you're trying to migrate some code from using nodegit to isomorphic-git? I would love to learn more. If you have a Gitter account you could chat with me here https://gitter.im/isomorphic-git/Lobby

**Comment by wmhilton** [comment]
I think the new [readObject API function](https://isomorphic-git.github.io/docs/readObject.html) should resolve this! If not we can reopen the issue.

**Comment by mojavelinux** [comment]
> Currently most commands are just that: actual commands that influence the working directory directly.

I think it's a huge milestone for this project to be able to advance beyond the worktree. Nice work!
