### ISSUE TITLE
How does this deal with conflicts

### ISSUE THREAD

**Issue by DominicTobias** [isomorphic-git/isomorphic-git#485]
Hi,

Thanks for this lib. I couldn't see something in the docs about handling conflicts, did I miss it?

e.g. You do a push but it is rejected, then you do a pull and have to resolve merge conflicts.

Is there any info about this? Thanks

(PS will close this as it's not an issue)

**Comment by jcubic** [comment]
AFAIK you can't do complex merges only fast forward merges so you can't even make it to the point where there are conflicts.

**Comment by DominicTobias** [comment]
Thanks for the replies, no worries @wmhilton still a great project that can bring about a lot of new ideas, look forward to seeing how it progresses!
