### ISSUE TITLE
listCommits returns almost all commits when doing a simple force push

### ISSUE THREAD

**Issue by hsablonniere** [isomorphic-git/isomorphic-git#498]
Imagine this situation:

* Remote master branch:

```
A<--B<--C<--D<--E<--F<--G<--H<--I<--J
```

* Local master branch:

```
A<--B<--C<--D<--E<--F<--G<--H<--I<--J'
```

Both remote and local share the same history of commits from `A` to `I` but commit `J'` is a rewrite of commit `J`. If I try to force push `J'` to my remote, the `listCommits()` function seems to list all the commits.

1. Is it normal?
2. In `git push` situations, don't we need a shorter list of commits? (maybe the list until a common parent)
3. In `git push` situations, the `listObjects` will get the list all commits as function arg and walk them all. On my project (~1800 commits), it can last more than one minute.

**Comment by hsablonniere** [comment]
Should we reuse `findMergeBase`?

**Comment by wmhilton** [comment]
Oooooooh. I still need to finish writing a proper `findMergeBase`. Currently it only handles fast-forward cases.

**Comment by hsablonniere** [comment]
> Oooooooh. I still need to finish writing a proper findMergeBase. Currently it only handles fast-forward cases.

:disappointed: Yep. I think this is why the example I described pushed all the commits and makes `listObjects` last 1 minute.

**Comment by wmhilton** [comment]
It's a bit rough... it only computes the mergebase of the branch being pushed and its remote tracking branch. Which irks me because I know I could instead compute the actual minimum graph utilizing ALL the branches we know about, but that creates its own set of potential slowdowns. Let me know if it solves your immediate problem though, which is the goal!

**Comment by wmhilton** [comment]
(It got auto-closed by the PR, but I want to confirm the performance improvement on your end before closing this issue for real.)

**Comment by hsablonniere** [comment]
@wmhilton Sorry for the delay. I just tested and it seems faster that before.
