### ISSUE TITLE
Configure Azure Pipelines to report Test Failures

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#511]
Some internet searching in similar Azure Pipelines related Github issues turned up your name @chrisrpatterson. Would you be willing to help me solve this mystery?

As seen here: https://github.com/isomorphic-git/isomorphic-git/runs/21388990

the overall Azure Pipelines check is labeled a "Success", even while it reports "Build #20181004.1 has test failures"

I'd much rather the Azure Pipelines check be labeled with a big red X when the tests fail. Is there some setting I need to turn on so that Test Failures cause an overall Build Failure?

**Comment by kaylangan** [comment]
I think if you mark the Publish Test Results task as Always Run, it'll report that build as failed.

**Comment by wmhilton** [comment]
OK... some progress has been made...

### Before: https://github.com/isomorphic-git/isomorphic-git/runs/21388990
![image](https://user-images.githubusercontent.com/587740/46487062-189d8680-c7cd-11e8-9de2-b00091a8abd2.png)

### After: https://github.com/isomorphic-git/isomorphic-git/runs/21526871
![image](https://user-images.githubusercontent.com/587740/46487097-2bb05680-c7cd-11e8-8a79-4c578d6b8ac2.png)

But it is still far too happy looking:
![image](https://user-images.githubusercontent.com/587740/46487303-aed1ac80-c7cd-11e8-8931-c0fac5909d5a.png)

**Comment by wmhilton** [comment]
Oooh! I think I've got it:
![image](https://user-images.githubusercontent.com/587740/46488670-52708c00-c7d1-11e8-98f5-84ab312472b7.png)

Now let's make sure it is Success when tests pass....

**Comment by wmhilton** [comment]
All right! I think we figured this out:
![image](https://user-images.githubusercontent.com/587740/46489400-45ed3300-c7d3-11e8-80cb-83f885d2250a.png)

Thanks @kaylangan for your advice and encouragement!

**Comment by chrisrpatterson** [comment]
@wmhilton I think you figured it out but the basics of the system are we will fail if a step fails and the easiest way to fail a script step is to return a non-zero exit code.  I think there is a fix in the works but currently simply publishing test results with failed test results alone will not fail the pipeline.

**Comment by wmhilton** [comment]
Thanks @chrisrpatterson!
