### ISSUE TITLE
 fs compatibility with nodejs fs back to what version?

### ISSUE THREAD

**Issue by rimmartin** [isomorphic-git/isomorphic-git#583]
Hi,

I'm developing a BYOFS for storing a working copy in a solid pod.
https://github.com/DataDriven-CAM/solid-fs

What version of nodejs fs is considered compatible with https://isomorphic-git.org/docs/en/plugin_fs?  v10 and v11 don't allow the callback to be ignored.  Particularly fs.stat. In https://github.com/isomorphic-git/isomorphic-git/blob/master/src/models/FileSystem.js there is a try catch with specific look at the err.code to know if the file exists.  From my implementation of fs.stat I'm having difficulty throwing an exception (in promise land).  

To test a little I changed my local copy models/FileSystem.exists to

```
  async exists (filepath, options = {}) {
    var ret = false
    var p = new Promise((resolve, reject) => {
      this._stat(filepath, (err, stat) => {
        if (err != null) {
          if (err.code === 'ENOENT' || err.code === 'ENOTDIR') reject(err)
          else {
            console.log('Unhandled error in "FileSystem.exists()" function', err)
            throw err
          }
        } else resolve(true)
      })
    }).then((res) => { ret = true }).catch(() => { ret = false })
    await p
    return ret
  }

```
and was able to run with the correct true or false coming from it. Didn't test with BrowserFS or the throw. BrowserFS points the nodejs v11 docs as what it is emulating yet I don't know if it v11 compatible yet.

What do you think?

**Comment by wmhilton** [comment]
Hmm. You shouldn't be able to pass a callback to `this._stat` because it's wrapped to return a promise:

[Line 25](https://github.com/isomorphic-git/isomorphic-git/blob/0793e271f0231df74410949214537936646a9b3e/src/models/FileSystem.js#L25) `this._stat = pify(fs.stat.bind(fs))`

As long as your implementation of `fs.stat` calls its callback with `(null, stat)` or `(err)` then it should work.

Unless there's something funny with the way `pify` works and the absence of an `options` argument is messing it up. /goes digging through `pify` source code/ No, that doesn't appear to be it. Very strange!

**Comment by wmhilton** [comment]
To address your initial question, I know it's at least compatible back to Node v8.12.0 because that's what the CI tests run with.

**Comment by rimmartin** [comment]
Oh, I'm not familiar with pify; let me pull a fresh copy and do some more testing.  Not sure how a function that doesn't return anything gets wrapped. Testing...

**Comment by rimmartin** [comment]
@wmhilton , you're right, pify does more than what I thought it could.  And I'm running further I thought and hitting an issue I know I'm making from the solid pod end

**Comment by wmhilton** [comment]
Solid is that new thing from Tim Berners-Lee right? That sounds really interesting! Do share your cool project on the [Gitter channel](https://gitter.im/isomorphic-git/Lobby). I'm really excited about isomorphic-git interoperating with experimental networks (like Solid, DAT, IPFS, Scuttlebutt, etc).
