### ISSUE TITLE
Feature: init bare repository

### ISSUE THREAD

**Issue by yuhr** [isomorphic-git/isomorphic-git#598]
Hi, is there any ongoing development for the equivalent feature of native `git init --bare`?

**Comment by mojavelinux** [comment]
I believe you just have to set dir and gitdir to the same value.

```js
const dir = 'path/to/repo.git'
await git.init({ dir, gitdir: dir })
```

then just add a commit to it to warm it up

```js
await git.commit({ dir, gitdir: dir, author: { name: 'Coder', email: 'coder@example.org' }, message: 'init' })
```

Is there something else you're looking for?

**Comment by yuhr** [comment]
How simple, thanks @mojavelinux 😭 But I think this is not intuitive and should be documented as kind of "How to create a _bare_ repository" for reacheability, or it might be good if we have a boolean `bare` option which automatically sets `gitdir` to the same as `dir`.

**Comment by yuhr** [comment]
Hmmm I just now found this sentence [here](http://isomorphic-git.org/docs/en/dir-vs-gitdir#docsNav),

> This is really only important when working with bare repositories.

Well, but the search engine does not hit this part 🤣 Pretty weird.

<img width="639" alt="screenshot 2018-11-30 at 9 56 24 pm" src="https://user-images.githubusercontent.com/18474125/49290621-cb971180-f4ea-11e8-91df-a8d5a57cbc19.png">

Just hits "non-bare" so I didn't look into the page... My bad, but still putting some example code like `await git.init({ dir, gitdir: dir })` would be informative.

**Comment by mojavelinux** [comment]
I definitely think an explicit statement about how to make a bare repository in the docs would be helpful. I can see room for it on the dir vs gitdir page as well as in the API docs for clone.

I'd be happy to draft something. @wmhilton, is there a place you'd like to see these docs land, or would you like me to just put forth a proposal?

**Comment by mojavelinux** [comment]
Since I'm a major user of this feature, I have a personal interest in these docs and might be able to offer some insight.

**Comment by mojavelinux** [comment]
@yuhr You also need to specify noCheckout so that isomorphic-git doesn't create the files for the current branch in the worktree.

```js
await git.init({ dir, gitdir: dir, noCheckout: true })
```

**Comment by yuhr** [comment]
Thank you again.

Probably you know that option is also undocumented and [missing a typedef](https://github.com/isomorphic-git/isomorphic-git/blob/master/src/index.d.ts#L351). It world help if you coud fix this together. 🏗😭🚜

**Comment by wmhilton** [comment]
> it might be good if we have a boolean bare option which automatically sets gitdir to the same as dir.

Your wish is my command! 😉

**Comment by mojavelinux** [comment]
> I'm pretty sure @mojavelinux meant git.clone. I don't think git.init has a noCheckout option.

Oops, yep, that's what I meant. I was having split mind disorder there.
