### ISSUE TITLE
Add option to branch function to checkout branch upon creating

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#610]
As a convenience, it would be nice if the `branch` function offered an option to checkout a branch after it's created. Often, when you create a branch, you also want to switch to it. This would eliminate a step in the calling code. This is similar to the `checkout -b` command in git. I'm thinking the option could be `checkout = true`.

```js
git.branch({ ...repo, ref: 'develop', checkout: true })
```

The alternative would be to add this functionality to `checkout` (something like `create = true`). Right now, the `checkout` command will implicitly create a new remote tracking branch, but that's not the same use case as creating a local branch (unless I'm mistaken).

**Comment by jcubic** [comment]
I think it should be in checkout since in git client there is `git checkout -b` so is reasonable to have the same in isomorphic-git

**Comment by wmhilton** [comment]
I vote for the second options, mostly because adding `checkout` to `branch` would cause the size of
```js
import { branch } from 'isomorphic-git'
```
to balloon significantly, whereas `checkout` already has most of `branch` inside it so adding a --create param to checkout won't really affect the weight of
```js
import { checkout } from 'isomorphic-git'
```
at all.

**Comment by wmhilton** [comment]
I've always felt weird about `git checkout -b`. It felt like putting the 🛒 in front of the 🐴.

Realistically? ~~I think it's trivial to add **both**, with no real cost in bundle size or over-extending the API. ~~ Turns out it's easier to add it to the `branch` command.

**Comment by wmhilton** [comment]
@mojavelinux @jcubic what do you think of #611?

**Comment by jcubic** [comment]
After consideration it actually don't matter which function have this feature it's just branch+checkout so it can be added to both or either of the commands, so I'm ok with this implementation.

**Comment by mojavelinux** [comment]
:tada:

**Comment by mojavelinux** [comment]
:tada:
