### ISSUE TITLE
checkout function should support checking out a commit

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#614]
The checkout function seems to assume that it's checking out a branch. When using it instead to check out a commit, it gets everything about the checkout right, except it puts the wrong information in the HEAD file. It should fill in the bare commit sha (oid). Instead, it adds a `ref: ` prefix to the value.

Here's a workaround:

```js
await git.checkout({ ...repo, ref: oid })
await fs.writeFile(path.join(repo.dir, '.git', 'HEAD'), oid + '\n')
```

I'm using isomorphic-git in Node, though that shouldn't make a difference in this case.

**Comment by wmhilton** [comment]
Yup... it needs to be modified to handle all the non-branch cases. I half suspect it would screw up and try to set up a remote tracking branch if you checked out a tag.

**Comment by wmhilton** [comment]
> I half suspect it would screw up and try to set up a remote tracking branch if you checked out a tag.

Actually that shouldn't happen because tags, unlike branches, aren't scoped by remotes. There's no distinction between local and remote tags, and thus `v1.0.0` will resolve right away after a clone (and `origin/v1.0.0` will _not_).
