### ISSUE TITLE
Fetch creates new packfile and index pair after cloning

### ISSUE THREAD

**Issue by DMXL** [isomorphic-git/isomorphic-git#615]
### Environment
Node: v8.1.2
System: macOS 10.14.1

### Problem
After cloning the repo, fetch will create a new pair of index and packfile under `.git/objects/pack`. I'm not sure if this is normal with git, cuz if I run `git gc` one of the index-packfile pair will be deleted. The following fetch calls will each time add one packfile only, which causes the APIs to break, since the corresponding index files are missing.

**Comment by wmhilton** [comment]
Actually, when you run `git gc` it creates a _new_ packfile that consolidates the current packfiles. It's OK to have multiple packfiles in `.git/objects/pack`. And it should work just fine... isomorphic-git automatically indexes any packfiles if it needs to read them. (Maybe it should index them right after it fetches... not sure.) What API is breaking?

**Comment by wmhilton** [comment]
I think what you're describing is a symptom of this bug: #654 
The good news is I've got a fix in the works!
