### ISSUE TITLE
Exclude HEAD from list of remote branches

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#620]
When calling listBranches with a remote, the HEAD branch should be filtered out. This isn't really the name of a branch, so it's quite surprising when it gets returned. It's a symbolic ref used internally by isomorphic-git to track which branch is the default on the remote, and therefore shouldn't get exposed.

**Comment by mojavelinux** [comment]
This one could probably go either way. nodegit doesn't return the HEAD branch for a remote. However, `git branch -r` does (though `git ls-remote --refs` doesn't). Perhaps an option, then, like noSymbolic?

**Comment by wmhilton** [comment]
Yay no consistency. :) It's quite useful to know what the default branch on a remote is though! I hate adding esoteric options... `noSymbolic` is a bit of a doozy. (You'd have to know what symbolic refs are, and know that HEAD is a symbolic ref.) This seems like one where I may have screwed up the default settings. :/

Looking at the code, there's an even deeper problem. The problem with `noSymbolic` is that you can't tell whether a ref is a symref or not until you read the file. And currently `GitRefManager.listRefs` doesn't read the contents of all the files. So filtering out symbolic refs accurately would noticeably slow down the function.

Right now it would be a breaking change to remove `HEAD` from the list. Let's pin this and revisit it if/when we start planning a 1.0 release.

**Comment by mojavelinux** [comment]
I'd be totally find with handling this as a documentation issue. I think if the docs set an expectation that HEAD may be one of the branches returned if the remote is set, then I'd know to expect it and ignore it if necessary. Would you like me to propose a docs update?

**Comment by wmhilton** [comment]
Go for it!
