### ISSUE TITLE
clone fails to complete when cloning certain repositories with depth=1

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#624]
When clone is called with a depth of 1 on certain repositories, it fails to create the clone and causes the process to terminate early.

Here are two repositories that cause isomorphic-git trouble:

* https://github.com/asciidoctor/asciidoctor.git
* https://github.com/vuejs/vue.git

Execution stops inside the following call in fetchPackfile:

```js
let response = await parseUploadPackResponse(raw);
```

Here's a sample program to reproduce the issue:

```js
const fs = require('fs')
const git = require('isomorphic-git')

;(async () => {
  const url = 'https://github.com/vuejs/vue.git'
  const dir = 'clone.git'
  const repo = { fs, dir, gitdir: dir, url }
  const depth = 1
  await git.clone({ ...repo, depth, noTags: true, noCheckout: true })
  console.log('done')
})()
```

**Comment by wmhilton** [comment]
Any chance it's related to #86? I never did solve that one.

**Comment by mojavelinux** [comment]
It does look to be the same issue.

I think I can provide some insight into what leads the early termination. Based on what I've observed, when using a readable stream (in particular with through2), if not all the sinks are satisfied, then the JavaScript process stops awaiting and immediately returns.

I can provide a simple script that demonstrates this problem:

```js
const vfs = require('vinyl-fs')

;(async () => {
  const result = await new Promise((resolve, reject) => {
    const files = []
    vfs
      .src('*.js')
      .on('data', (data) => files.push(data))
      .on('error', (err) => reject(err))
      .on('end', () => resolve(files))
  })

  console.log(result.length)
  console.log('done')
})()
```

If you comment out the line starting with `.on('end',`, then the script will terminate prematurely.

So it must be that the pipe in parseUploadPackResponse is not cleanly terminating. As to why, I'm not sure.

**Comment by wmhilton** [comment]
Out of curiosity, how did you figure out "Execution stops inside the following call in fetchPackfile"? That's more than I ever figured out. I tried adding an 
```
process.on('uncaughtException', function (err) {
  console.error((new Date).toUTCString() + ' uncaughtException:', err.message)
  console.error(err.stack)
  process.exit(1)
})
```
but it doesn't catch it

**Comment by wmhilton** [comment]
Hmm. So one difference is canonical git the `depth` param _implies_ `--single-branch`. [source](https://git-scm.com/docs/git-clone#git-clone---depthltdepthgt)

Interestingly, if you add `singleBranch: true` this problem goes away.

I wonder what happens if I specify `--no-single-branch` in git...

**Comment by wmhilton** [comment]
OK. So.

```sh
git clone --depth 1 --no-tags --no-checkout --no-single-branch https://github.com/vuejs/vue.git
```
results in a server response with 24 "shallow" commands. If we look on Github, at the top it says "25 branches".
![image](https://user-images.githubusercontent.com/587740/49678971-161e0e00-fa56-11e8-9397-529406920c44.png)

However if we go to the branches page and look around, we'll see that the `csp` and `1.0-csp` branches point to the same commit, `c45cfee24d222b68b8e6a320863cb7e13c15f2bc`. So that explains how we get from 25 to 24.

Now. We run the same command in `isomorphic-git`...
```js
await git.clone({
  url: 'https://github.com/vuejs/vue.git', dir, depth: 1, noTags: true, noCheckout: true
})
```
and the server response returns 342 "shallow" commands before the process terminates. So my guess is that the server hangs up because something is terribly wrong about the request.

**Comment by wmhilton** [comment]
OK. There's a big difference in normal cloning too. git only clones branches and tags by default, but isomorphic-git is pulling down PRs from Github as well... because I thought "branches and tags... well that's everything, right?". Lemme see if putting the breaks on that helps.

**Comment by mojavelinux** [comment]
> but isomorphic-git is pulling down PRs from Github as well

I had actually noticed that when trying to clone https://github.com/octocat/Spoon-Knife.git, which has an absurd number of PRs but practically no commits on "real" branches.

**Comment by mojavelinux** [comment]
> Out of curiosity, how did you figure out "Execution stops inside the following call in fetchPackfile"?

This is the strange thing about unresolved promises in streams. They seem to miss the exception handler altogether. I figured it out only through trial and error in the debugger / print statements.

**Comment by wmhilton** [comment]
> I figured it out only through trial and error in the debugger / print statements.

Damn. That's what I've been doing as well.

**Comment by wmhilton** [comment]
OK. So it's not the server terminating the connection. I just tried dumping the stream from the old code
```js
  raw.pipe(require('fs').createWriteStream('dump.txt'))
  console.log('dumped to dump.txt')
  return
  let response = await parseUploadPackResponse(raw)
```
and have a LOVELY 23mb server response complete with 2143 "shallow" commands.

**Comment by mojavelinux** [comment]
I think I may have figured it out. For some (very strange) reason, this line does not actually fire the 'end' event.

```
packetlines.end()
```

However, if you add this line after it, then it does.

```
packetlines.emit('end');
```

**Comment by wmhilton** [comment]
Interestingly, if I increase `depth` from 1 to 4, now there's only 616 shallow commands in the response.

| depth | shallows |
|---|---|
| 1 | 2143 |
| 2 | 1295 |
| 3 |  857 |
| 4 | 616 |
| 5 | 451 |

I'm _guessing_ that this has something to do with the average distance between PRs? Like if most PRs are only a couple commits deep, and are being merged (rather than squashed) then the older PRs are reachable by the newer PRs.

**Comment by mojavelinux** [comment]
With the change I proposed, it correct shallow clones all repositories I cited.

(I'm actually curious whether that end handler was ever being hit, because it just seems that the event wasn't being raised correctly).

**Comment by mojavelinux** [comment]
hmm, well, sort of. it seems like the log is still not right in the asciidoctor repository...but at least the process doesn't terminate prematurely.

**Comment by mojavelinux** [comment]
Nevermind about the issue with asciidoctor. That's exactly right. The tip is a merge and of course it's parent isn't there. So it's exactly what we want.

**Comment by mojavelinux** [comment]
Unless I'm mistaken, I think we've got a solution. Whether it's the right solution, IDK. But it satisfies my request, at least.

**Comment by mojavelinux** [comment]
> I'm guessing that this has something to do with the average distance between PRs?

It does seem like the shallow commit inventory changes based on what other commits are present. Seems like it gets deep into graph theory ;)

**Comment by wmhilton** [comment]
> With the change I proposed, it correct shallow clones all repositories I cited.

So, interestingly it _does_ finish, but only 342 of the "shallow" commands make it through `through2`.

Hang on I think I've got it........

**Comment by wmhilton** [comment]
got it! The packetlines stream only pipes into through2 up to the highwatermark, then was pausing. It's in paused mode because it has no `.on("data"` handler.

```js
    packetlines.pipe(
      through2(async (data, enc, next) => {

      })
    ).resume()
```

**Comment by wmhilton** [comment]
so it only becomes apparent as a problem if the server sends > 16kb of "shallow" commands LOL.

**Comment by mojavelinux** [comment]
Ahhhh. That makes **total** sense and, once again, I learned something in the process. \o/

**Comment by wmhilton** [comment]
I mean... it doesn't explain why the process _silently crashes without a stacktrace!_ grumble hrrumph.

**Comment by mojavelinux** [comment]
I think that's just built-in behavior in Node when a promise is not resolved (but not rejected either). Seems to be some sort of safety mechanism (good or bad). But I agree, it seems pretty dumb to me.

**Comment by mojavelinux** [comment]
:tada:
