### ISSUE TITLE
Some fixes to 'annotatedTag' and 'commit'

### ISSUE THREAD

**Issue by yuhr** [isomorphic-git/isomorphic-git#642]
https://github.com/isomorphic-git/isomorphic-git/pull/621#issuecomment-446284927

> I just noticed this in the code:
> 
> ```
> tagger.timestamp !== undefined && tagger.timestamp !== null
> ```
> That's functionally equivalent to:
> 
> ```
> tagger.timestamp != null
> ```
> There's no reason to check for exactly null and undefined.

https://github.com/isomorphic-git/isomorphic-git/pull/621#issuecomment-446286045

> I also noticed that if the tagger object passed in is missing name or email, the object is modified directly. I don't think a function should have side effects.
> 
> And one more thing. I think the message should default to the tag name (i.e., ref) instead of being blank. That's a pretty typical git practice.

Thanks @mojavelinux! And sorry I didn't notice these viewpoints.

**Comment by yuhr** [comment]
It seems the same also applies to commit command.

**Comment by wmhilton** [comment]
@mojavelinux 
> There's no reason to check for exactly null and undefined.

Hahaha yes there IS a reason! I'll see if you can think of the edge case. 😉 @yuhr you'll have to put these checks back.

> the object is modified directly

Hmm. Yeah we can change that.

**Comment by mojavelinux** [comment]
@wmhilton Hmm. My understanding is that using loose equals on null can only match null or undefined. (http://adripofjavascript.com/blog/drips/equals-equals-null-in-javascript.html). I can't find anything to the contrary. But you seem to know of case. Please enlighten this poor soul. :pray:

**Comment by wmhilton** [comment]
> using loose equals on null can only match null or undefined. 

Well I'll be damned, you're right.

Originally, I was just using a "truthiness" test:
```js
tagger.timestamp = tagger.timestamp ||  Math.floor(taggerDateTime.valueOf() / 1000)
```

and _that_ bit me. Because if either the timestamp (or the time ZONE - much more common) is `0` it does the wrong thing.

But you're right... apparently an `== null` check works here. I honestly thought that `0 == null` type coerced both to falsy values.

**Comment by mojavelinux** [comment]
The reason I know this is because I went on exactly the same journey not that long ago.
