### ISSUE TITLE
Throw dedicated error for empty remote repository

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#647]
When the remote repository is empty, throw a dedicated error so an application can catch it. Currently, isomorphic-git throws an error for the first missing capability, which ends up being rather arbitrary and not very informative.

I've worked out that an empty repository will report no refs and no capabilities. We could check if either (or both) of those properties is empty to determine that the repository is empty.

**Comment by mojavelinux** [comment]
Technically, we can't know with absolute certainty that the remote repository is empty. But I think this error is better than reporting that shallow clones are not supported. Consider an empty repository on GitHub. Shallow clones are supported, but nothing is supported if the repository is empty, and that's really what we want to focus on.

**Comment by wmhilton** [comment]
Here's what canonical git does:
```sh
> git clone https://github.com/wmhilton/can-you-clone-an-empty-repo
Cloning into 'can-you-clone-an-empty-repo'...
warning: You appear to have cloned an empty repository.
```

I feel like cloning an empty repo should work. It shouldn't throw an error, but should init an empty repo and configure the remote, just like git does.

I'm not even convinced we need a warning. The fact that the repo is in a detached head state is a pretty good indicator.

**Comment by mojavelinux** [comment]
> I feel like cloning an empty repo should work. It shouldn't throw an error, but should init an empty repo and configure the remote, just like git does.

I'm totally fine that. We're coming from a situation where an error is thrown. So the choice is either to throw a proper exception or not throw. Let's match what git does. I also agree that the warning git issues is unnecessary.

I'll proceed with reworking the code so it just succeeds silently.

**Comment by wmhilton** [comment]
Yup! As @pyramation [illustrates](https://gist.github.com/pyramation/a4325cbf645a90a4fdce515ea29bd41a#file-init-js), the end result of cloning an empty repo should basically be:

```js
await git.init({ gitdir });

// remote
const remote = 'origin';
await git.config({
  gitdir,
  path: `remote.${remote}.url`,
  value: repoUrl
});

await git.config({
  gitdir,
  path: `remote.${remote}.fetch`,
  value: `+refs/heads/*:refs/remotes/${remote}/*`
});
```

**Comment by mojavelinux** [comment]
Thanks @wmhilton!

I updated the title of the issue to accurately reflect the change that was made.
