### ISSUE TITLE
Add an option to the fetch command to prune references

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#663]
Add an option to the fetch command to prune references that have been removed from the remote. This is equivalent to `git fetch -p name-of-remote`. Tags should only be pruned if both the prune and tags options are enabled. This is roughly equivalent to `git fetch -p -P name-of-remote`.

**Comment by wmhilton** [comment]
> Tags should only be pruned if both the prune and tags options are enabled.

Actually, because of the weird interaction of tags with multiple remotes, it's probably safer to add a separate `pruneTags` option. Which I'll do.

**Comment by mojavelinux** [comment]
> it's probably safer to add a separate pruneTags option.

After thinking it over again, I agree. Thanks!
