### ISSUE TITLE
`status` throws an error on a repository with no HEAD commit

### ISSUE THREAD

**Issue by krasimir** [isomorphic-git/isomorphic-git#669]
> - whether you are using Node or the Browser

I'm using it in a browser.

> - how you are using it (if you are using a bundler what bundler; if you are using a `<script>` tag what CDN URL)

The dependencies of my test are:
```
https://unpkg.com/browserfs@1.4.3/dist/browserfs.min.js
https://unpkg.com/isomorphic-git@0.47.0/dist/bundle.umd.min.js
```
And here is the code:

```js
let fsOptions = {
  fs: 'InMemory',
  options: {}
}

BrowserFS.configure(fsOptions, async function (err) {
  if (err) return console.log(err);
  const fs = BrowserFS.BFSRequire('fs');
  
  git.plugins.set('fs', fs);
  await git.init({ dir: '.' });
  
  fs.mkdir('/demo', async () => {
    fs.writeFile('/demo/test.txt', 'Testing git', 'utf8', async () => {
      console.log(await git.status({ dir: '/demo', filepath: 'test.txt' }));
    });
  });
});
```

I'm getting

```
Uncaught (in promise) s: Could not resolve reference "HEAD"
```
(at the line of the `console.log`)

Here is a demo where I'm trying to make it work https://demoit.app/e/xWj9gK7EJCV

**Comment by wmhilton** [comment]
The empty repository state is... weird. Git intentionally creates a dangling HEAD reference to a non-existing "master" branch. Once you add some files and make a commit it should be fine, but I suppose I should go through and add unit tests for everything in a "git init" state and find the commands (like `status`) that assume the HEAD commit exists and add extra logic to handle that case when there are no previous commits.

**Comment by pyramation** [comment]
@wmhilton regarding blank repos. I suppose I could hack the git-server to potentially fork (by copying) a repo with a single commit, but it feels a bit hacky. Do you think this feature is on the horizon?
