### ISSUE TITLE
file history

### ISSUE THREAD

**Issue by stefan-guggisberg** [isomorphic-git/isomorphic-git#677]
i am currently porting [git-server](https://github.com/adobe/git-server) from `nodegit` to `isomorphic-git` (adobe/git-server#47). The port has been straight forward so far, kudos to the isomorphic team!

However, there's one feature i can't find in isomorphic-git:  listing all commits which affected a particular file, i.e. the eqiuvalent of 
```
git log -- path/to/file
```

Any pointers/suggestions would be greatly appreciated.

**Comment by stefan-guggisberg** [comment]
@wmhilton that works for me, thanks!

**Comment by wmhilton** [comment]
Awesome! I've added it to the Snippets page. https://isomorphic-git.org/docs/en/snippets#git-log-path-to-file

**Comment by jtran** [comment]
I'm trying to do `git log -- path/to/file`.  I used the snippet given, and it works.  But it's very slow.  Is there any way this feature could be added in a way that's performant?   If not, do you have any tips for how I can speed up the `readObject()` loop for a large repo if, for example, I know that the path is a regular file, not a directory or other thing?
