### ISSUE TITLE
statusMatrix() shows non-files

### ISSUE THREAD

**Issue by tripodsan** [isomorphic-git/isomorphic-git#705]
using isomorphic-git with node, having a non-file / non-symlink in the working directory, for example a unix socket, is reported in `statusMartix()` where as `git status` doesn't list it.

### example:

```
$ python -c "import socket as s; sock = s.socket(s.AF_UNIX); sock.bind('test.sock')"
$ ls -al
total 0
drwxr-xr-x   6 user staff   192B Feb 28 11:20 ./
drwxr-xr-x  19 user staff   608B Feb 28 11:14 ../
drwxr-xr-x  12 user staff   384B Feb 28 11:17 .git/
lrwxr-xr-x   1 user staff     9B Feb 28 11:29 linktoreadme.md@ -> readme.md
-rw-r--r--   1 user staff     0B Feb 28 11:17 newfile.txt
-rw-r--r--   1 user staff     0B Feb 28 11:15 readme.md
srwxr-xr-x   1 user staff     0B Feb 28 11:20 test.sock=

$ git status --porcelain
?? linktoreadme.md
?? newfile.txt

$ node -e "const git = require('isomorphic-git'); git.plugins.set('fs', require('fs')); git.statusMatrix({dir:'.'}).then(console.log)"
[ [ 'linktoreadme.md', 0, 2, 0 ],
  [ 'newfile.txt', 0, 2, 0 ],
  [ 'readme.md', 1, 1, 1 ],
  [ 'test.sock', 0, 2, 0 ] ]
```

**Expected:** `test.sock` not to be reported in the martix.

**Comment by wmhilton** [comment]
That possibility... never crossed my mind.

Um... if anyone wants to tackle this, I'd start at [this line in GitWalkerFs](https://github.com/isomorphic-git/isomorphic-git/blob/3b8453421de546970226ffb7ab0ecf2c8228c2b9/src/models/GitWalkerFs.js#L53) which makes a naive-in-hindsight "if it's not a directory it's a file" labeling and update it to set `type` to something besides "blob". Then update the [map](https://github.com/isomorphic-git/isomorphic-git/blob/3b8453421de546970226ffb7ab0ecf2c8228c2b9/src/commands/statusMatrix.js#L64) used in statusMatrix and where it skips directories make it also skip if `workdir.type` is exotic.
