### ISSUE TITLE
statusMatrix() throws if the git repo has submodules

### ISSUE THREAD

**Issue by stefan-guggisberg** [isomorphic-git/isomorphic-git#707]
using Node 

If a git repo has submodules `git.statusMatrix({ dir: repoPath })` throws the following error:

`Failed to read git object with oid 3b8453421de546970226ffb7ab0ecf2c8228c2b9`

Note that the hash is the hash of the (first) submodule:

```bash
git submodule
 3b8453421de546970226ffb7ab0ecf2c8228c2b9 isomorphic-git (v0.0.26-467-g3b84534)
```

Seems like `isomorphic-git` tries to read an object from `this` repo's object store but using the submodule's hash as key.
 
I traced the problem down to `statusMatrix() -> walkBeta1() -> GitWalkerRepo.readdir() -> readObject()` but then got lost :/

**Comment by wmhilton** [comment]
yeah. submodule support is a WIP. cloning projects with submodules doesn't crash anymore... but I still haven't taught it where to look for submodule objects in order to read/checkout submodules properly. :/

**Comment by wmhilton** [comment]
> I traced the problem down to statusMatrix() -> walkBeta1() -> GitWalkerRepo.readdir() -> readObject() but then got lost :/

Well, I'm glad you were able to trace it that far! And yes... readObject is a little crazy, because objects can be "loose" or "packed" (and a few other modes that aren't supported yet like "alternates") but in essense, it fails to read oid `3b8453421de546970226ffb7ab0ecf2c8228c2b9` because it's not in any place it knows about. Submodule objects are stored in `.git/modules/{name}/objects` instead of `.git/objects`.

**Comment by stefan-guggisberg** [comment]
@wmhilton Is there a chance this gets fixed any time soon? `git.statusMatrix` throws an `Error` if there are submodules. We can't really prevent people from using submodules. The only option we have right now is to replace the `git.statusMatrix` calls with `git status` command line executions via `shelljs` (which would be a pity IMO).

**Comment by wmhilton** [comment]
Ah. Hmm. Well, actually properly computing the status of a submodule would probably take a while for me to get working... would a quick fix like skipping submodules in statusMatrix work for your use case?

**Comment by stefan-guggisberg** [comment]
> would a quick fix like skipping submodules in statusMatrix work for your use case?

yes, absolutely.

**Comment by wmhilton** [comment]
Ah! In that case I'll try to slap something together this evening. `statusMatrix({ skipSubmodules: true })` or something.

**Comment by wmhilton** [comment]
@stefan-guggisberg Hopefully it'll work for your use case now! 🙂 Let me know if you run into any more issues.

**Comment by stefan-guggisberg** [comment]
@wmhilton awesome, thank you so much!

**Comment by BastienAr** [comment]
Is there an option to skip submodule check in statusMatrix ? Because currently the statusMatrix function returns all the submodules files as [ 'file', 0, 2, 0 ], (HEAD is detached).

**Comment by wmhilton** [comment]
Aaaaahhhh... @BastienAr your submodules are full of files? You must have cloned them with another git implementation :). And those files all show up as new... urgh that's got to be annoying. I'll... see what I can do.
