### ISSUE TITLE
resolveRef fails to resolve a branch named 'config'

### ISSUE THREAD

**Issue by stefan-guggisberg** [isomorphic-git/isomorphic-git#709]
* using Node
* using as a `package.json` dependency

`resolveRef` fails to resolve existing branches with certain names, e.g.
* `config`
* `description`
* `index`
* `shallow`
* `commondir`

To reproduce:

```
mkdir test
cd test
git init
touch README.md
git add .
git commit -m 'initial commit'
git checkout -b config
```

then call `git.resolveRef({ dir: '.', ref: 'config' })`:

```
ResolveRefError: Could not resolve reference "[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true".
```

Note that the double quoted text is the content of the `.git/config` file.

**Comment by stefan-guggisberg** [comment]
@wmhilton Any chance you can have a look at this issue and the related PR #710?

**Comment by Ni55aN** [comment]
The issue still present for `checkout` or `currentBranch`
https://github.com/isomorphic-git/isomorphic-git/issues/767
