### ISSUE TITLE
manually delete an entire directory from the repo and add that change

### ISSUE THREAD

**Issue by jfrankdev** [isomorphic-git/isomorphic-git#715]
When using command line git, when you clone a repo, delete a folder in that repo on your desktop manually (drag to recycle bin kind of thing) and then run:

```
git add -A
git status
```

it will show that you deleted that directory in staging. Then all you need to do is add a commit message, push it and that folder will be deleted when you check your remote repo.

How do you emulate this behavior with isomorphic-git? Is there a way to track manual deletions of entire directories within your repo?

**Comment by wmhilton** [comment]
Goooood question. Yes you can track the deletions via `status` or `statusMatrix`. But I don't have a git `add -A` command yet. :/ In fact, right now there's an asymmetry where the `git.add` command will recursively add files in a directory, but the `git.remove` command doesn't recurse.

It would probably be wise to rewrite `add` and `remove` to use `walkBeta1`. Then it'd be easy to handle both these cases, as well as pattern matching cases like `git.add({fs, dir, pattern: "**/*.txt" })`

For now though, the quickest way to implement a "git add -A" would probably be to run `statusMatrix` and then loop through the results and run `git.add` on all the files with changes.

**Comment by jfrankdev** [comment]
great thank you @wmhilton, I can confirm this works. This is the statusMatrix git add -A function from https://isomorphic-git.org/docs/en/snippets#git-log-path-to-file, but here it is slightly modified with what worked for me:

```
const dir = 'C:\Github';
 git.plugins.set('fs', require('fs'))

await git.statusMatrix({ dir: dir, pattern: '**' }).then((status) =>
 Promise.all(
     status.map(([filepath, , worktreeStatus]) =>
         worktreeStatus ? git.add({ fs, dir, filepath: filepath }) : git.remove({ fs, dir, filepath: filepath })
            )
      )
);
```
