### ISSUE TITLE
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them

### ISSUE THREAD

**Issue by abhishiv** [isomorphic-git/isomorphic-git#728]
Hey guys

I am facing the following error while using isomorphic-git@0.51.12 in jest on clone

```
    TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them

      at fetch (node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:5105:16)
```

Source is here
https://github.com/isomorphic-git/isomorphic-git/blob/667ae6c6758a3f385a5734f1fa4c9a64cb9a14bf/src/commands/fetch.js#L197-L200

The error block is hit because I'm using a custom fs, and there's probably some issue with that which I need to fix. However modifying the err.caller property this way hides the original error from me and makes debugging hard since jest then shows this error rather than original error.

**Comment by jcubic** [comment]
I think that browser started to report error when `caller` is used, even if used in not function. I think this was the same with some linter that reported eval usage even that it was custom function with the same name and original eval was not called.

It seems that you get this error while getting real error. Not sure how to do this when you use source maps but you need to somehow modify the code maybe set breakpoint or edit the file (in Chrome there is overwrite option in source panel) and remove that `err.caller` that way you will see real error you got. Or you can set breakpoint on exceptions and check what is `err.message`.

**Comment by wmhilton** [comment]
that's weird. I specifically rethrow the same error object thinking that way you wouldn't lose information 😟. Does the engine overwrite the `err.stack`? If so that's a pain, I'll have to figure out how to preserve that.

As for why your getting the error:

```
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
```

That's not because I'm adding a property called `caller` to an object. I'm guessing that's because somewhere in your custom fs you're using `arguments`, `callee`, or `caller`. I think the error message is the original error message, but the stack trace is originating from the point where the error was rethrown.

**Comment by wmhilton** [comment]
Unless... maybe `err` is not an `Error` object! You can throw anything really.... what if `err` is a Function? _Then_ modifying the `.caller` property could be an issue. Actually any object that has a weird behavior (a Proxy, a frozen object, a readonly `caller` property) could potentially cause 

```err.caller = 'git.fetch'```

 to error! I should handle that.

**Comment by abhishiv** [comment]
Hey @wmhilton 

> Unless... maybe err is not an Error object! You can throw anything really.... what if err is a Function? Then modifying the .caller property could be an issue. Actually any object that has a weird behavior (a Proxy, a frozen object, a readonly caller property) could potentially cause

That was it! I was using errors.js from your lighting-fs, and forgot to do `new EExist()` and was doing  `EExist()`. That fix made it go away. Personally I think fs layers have to throw an error object the way node does, so you can keep the behaviour as it is now.

Please feel free to close this issue.

**Comment by wmhilton** [comment]
Yay! I thought that might be it. (`throw MyError` vs `throw new MyError()`)

I'll close this, but if any future Googlers stumble across this because they also ran into this issue, leave a +1 comment below and I'll reopen it if more people run into this problem.
