### ISSUE TITLE
CSP error when used without 'unsafe-eval'

### ISSUE THREAD

**Issue by FabianHenneke** [isomorphic-git/isomorphic-git#734]
Due to the use of the npm package `nick` in `GitError.js`, isomorphic-git requires 'unsafe-eval' when used in a context with a Content Security Policy (CSP). I noticed this when I wanted to use isomorphic-git in a Chrome App (not Extension), which have a fixed CSP in place.

Since `nick` is used in a single place where string templates are evaluated immediately, coming up with a full replacement that is CSP-friendly is not difficult. I have submitted PR #733 with a proposal for such a replacement.

**Comment by wmhilton** [comment]
Wow yeah, we do _not_ need `eval` 😆 that's horrible. Sorry about that. Originally I intended for Error messages to be translated, and have internationalization, and the original design of GitError was hugely overkill. The Error messages themselves are now taking up a not-insignificant portion of the bundle size; I'd love to figure out how to lazy-load them. But for now your template function should work great!
