### ISSUE TITLE
Set up a sponsors file

### ISSUE THREAD

**Issue by TomasHubelbauer** [isomorphic-git/isomorphic-git#743]
I just found that GitHub allows you to display a Sponsor button (next to the Used By, Watch, Start and Fork ones at the top of the repository page) which displays a popup with links to whatever funding methods are configured to display:

https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository

I think we should promote OpenCollective there, what do you think?

This is not to be confused with the upcoming GitHub Sponsors feature. It's confusingly named right now, in the future, I am sure this button will prominently display the GitHub Sponsors way of supporting, but it looks taking advantage of this feature could help promote alternative funding methods alongside GitHub Sponsors when that lands and overall increase the funding option visibility.

**Comment by wmhilton** [comment]
Great idea!!!
