### ISSUE TITLE
Unexpected output: ExperimentalWarning: The fs.promises API is experimental

### ISSUE THREAD

**Issue by tripodsan** [isomorphic-git/isomorphic-git#771]
when using isomorphic-git with nodejs v10.15.x, I see the output:

```
(node:67212) ExperimentalWarning: The fs.promises API is experimental
```

from here:

```
(node:67348) ExperimentalWarning: The fs.promises API is experimental
    at Object.get (fs.js:1841:17)
    at verifySchema (.../node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:1091:33)
    at Map.set (.../node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:1119:5)
```

IMO, this warning could be avoided by using a library like `fs-extra` or similar.

**Comment by stefan-guggisberg** [comment]
related to #730

**Comment by wmhilton** [comment]
I was going to post a lengthy explanation of why I don't think I can fix this. But then I found something that might work!!! uno momento

**Comment by wmhilton** [comment]
v10
> Object.getOwnPropertyDescriptor(fs, 'promises')
{ get: [Function: get],
  set: undefined,
  enumerable: false,
  configurable: true }
>

v12
> Object.getOwnPropertyDescriptor(fs, 'promises')
{
  get: [Function: get],
  set: undefined,
  enumerable: true,
  configurable: true
}

**Comment by wmhilton** [comment]
linking to https://github.com/nodejs/node/issues/27944

**Comment by stefan-guggisberg** [comment]
That was quick :-) Thanks William!

**Comment by jcubic** [comment]
Awesome finding, great job @wmhilton
