### ISSUE TITLE
Proxy option in pull and push api

### ISSUE THREAD

**Issue by Herffin** [isomorphic-git/isomorphic-git#772]
My web server is deployed in my company‘s inner environment. 
Because of the security strategy, if my server want to build connection with outter, i have to use proxy. However, isomorphic-git's api doesn't support proxy option. 
Now I use global agent in my code and i works but i wanner just use proxy in isomorphic-git.
So can you support proxy option in api especially the push and pull api?

**Comment by jcubic** [comment]
Maybe you can use `corsProxy` option.

**Comment by Herffin** [comment]
> Maybe you can use `corsProxy` option.

thx. But i read the docs, it said this is for users of isomorphic-git that enables cloning and pushing repos in the browser, so can i use it in web server?

**Comment by jcubic** [comment]
Just try, I think that the code is almost the same for both browser and server.

**Comment by wmhilton** [comment]
Is this a duplicate of #202 by any chance? If this is for Node, it should be solvable with a custom HTTP plugin.

**Comment by mojavelinux** [comment]
Yes, this is a duplicate of #202 (and related to #1491).

**Comment by jcubic** [comment]
Ok so I will close then.
