### ISSUE TITLE
git pull seem to corrupt my project

### ISSUE THREAD

**Issue by fraxken** [isomorphic-git/isomorphic-git#788]
Hi,

I'm using isomorphic-git for a Node.js CLI tool. We have a feature on that CLI that try to update the master branch when the commits on the remote is ahead of the local branch.

Everything execute with no errors, but when we go in the repository every git commands fail with a message like this one:

```
error: failed to validate delta base reference at offset 490 from .git/objects/pack/pack-31ef631484b7c201abb5edb1cd84209653789b00.pack   
fatal: packed object 33f32f92c45cfb866118b8c61fc002cfe85ff6dd (stored in .git/objects/pack/pack-31ef631484b7c201abb5edb1cd84209653789b00.
pack) is corrupt
```

Our project is open so you can take a look at the code and even install/link the CLI.

The code that call the pullMaster method:
https://github.com/SlimIO/Sync/blob/master/commands/install.js#L118

The pullMaster code (with the git.pull .. by the way the method work well after a clone).
https://github.com/SlimIO/Sync/blob/master/src/utils.js#L183

The package is at the latest version, we tried with Node 10 and Node 12. And i'm on Windows 10.

Best Regards,
Thomas

**Comment by wmhilton** [comment]
I'm running into this too now. :-( Haven't figured out what causes it yet though, but I can confirm it exists.

**Comment by antoniofarina** [comment]
Same issue 

`error: failed to validate delta base reference at offset 195 from .git/objects/pack/pack-68846b587ff750139f72650987d64459319dc9cd.pack
fatal: packed object cbb0dabd998432f270ee585976223f614beef5c3 (stored in .git/objects/pack/pack-68846b587ff750139f72650987d64459319dc9cd.pack) is corrupt
`

**Comment by wmhilton** [comment]
@antoniofarina I'm trying to solve this one (it's a doozy). The next time this happens can you send me the output of `ls -l .git/objects/pack`?

In particular, I have seen one case so far where there were _more_ `.idx` files than there were `.pack` files, which is downright eerie.

Actually @fraxken or anybody. Anybody who sees this error, please paste the output of `ls -l .git/objects/pack` to this issue. It is _most_ perplexing and difficult to reproduce.

**Comment by antoniofarina** [comment]
> @antoniofarina I'm trying to solve this one (it's a doozy). The next time this happens can you send me the output of ls -l .git/objects/pack?

Yes sure. 

Let me say that a case when it happens for sure is when, form some reason the `pull` is interrupted (`CRTL + C` for example). In that case 70% of possibility (not 100% !! ) to have a corruption.
It could be a good idea to to an hidden copy of the entire repo before a pull in order to be able to rollback in case of corruption (said this, may be it is an overkilling: at the end do a fresh clone could be an acceptable solution)

Thank you for your effort

**Comment by wmhilton** [comment]
I think this is fixed now.

**Comment by fraxken** [comment]
Hi,

Yes. Seem to work fine on my side now with the latest version.

Thanks for your work !

Best Regards,
Thomas
