### ISSUE TITLE
Error when importing (ES Module syntax) isomorphic-git

### ISSUE THREAD

**Issue by AxelTerizaki** [isomorphic-git/isomorphic-git#798]
Hello :)

I'm trying to use isomorphic-git in my typescript project. I'm using the ES Module syntax `import git from 'isomorphic-git';` and it seems to work fine until i want to actually use it.

For example, first thing I do is trying to set the `fs` plugin as seen in the docs, but I get the following error : 

```
TypeError: Cannot read property 'plugins' of undefined
```

It's not a major issue in any way since I can work around it by using the regular `require()` syntax as shown in the docs, but it'd be nice if this would be fixed.

Using Typescript 3.5.2, and node 12.4.0

Thanks for making such a good module.

**Comment by Aegis18** [comment]
> Hello :)
> 
> I'm trying to use isomorphic-git in my typescript project. I'm using the ES Module syntax `import git from 'isomorphic-git';` and it seems to work fine until i want to actually use it.
> 
> For example, first thing I do is trying to set the `fs` plugin as seen in the docs, but I get the following error :
> 
> ```
> TypeError: Cannot read property 'plugins' of undefined
> ```
> 
> It's not a major issue in any way since I can work around it by using the regular `require()` syntax as shown in the docs, but it'd be nice if this would be fixed.
> 
> Using Typescript 3.5.2, and node 12.4.0
> 
> Thanks for making such a good module.

try `import * as git from 'isomorphic-git'`

**Comment by wmhilton** [comment]
Yes, either use `import * as git` or import just the pieces you need, like

```
import { plugins, clone } from 'isomorphic-git'
```

Huh. Could have sworn I'd documented that but it appears I have not. I'll fix that in the README.
