### ISSUE TITLE
GitRefManager.updateRemoteRefs not handling remote with combined fetch and push URL

### ISSUE THREAD

**Issue by TomasHubelbauer** [isomorphic-git/isomorphic-git#84]
I have a config like this:

```ini
[core]
repositoryformatversion = 0
filemode = false
bare = false
logallrefupdates = true
symlinks = false
ignorecase = true

[remote "origin"]
url = https://gitlab.com/TomasHubelbauer/bloggo.git
```

This code in `GitRefManager.updateRemoteRefs` fails for me:

```javascript
if (!refspecs) {
  refspecs = await config.getall(`remote.${remote}.fetch`);
}
```

I _think_ the config should be fine? Should the logic here be extended to cover a case where both fetch and push URLs are represented like this? I am not too familiar with Git internals, so I am not sure exactly.

**Comment by wmhilton** [comment]
Ah! That scenario slipped through the cracks, because if you create a repo with "git init" it typically sets up a fetch "refspec" for you:
https://git-scm.com/book/en/v2/Git-Internals-The-Refspec

I'll implement a fallback default refspec to use if there's not one in the config file.

**Comment by wmhilton** [comment]
aaaahhh........ OK so, interesting thing is, git does something completely different than what you might expect if you actually use that config file as you have it written:

```sh
> mkdir issue-84
> cd issue-84
> git init
> cat <<EOF > .git/config
[core]
repositoryformatversion = 0
filemode = false
bare = false
logallrefupdates = true
symlinks = false
ignorecase = true

[remote "origin"]
url = https://gitlab.com/TomasHubelbauer/bloggo.git
EOF
> git fetch origin
remote: Counting objects: 1222, done.
remote: Compressing objects: 100% (538/538), done.
Receiving objects:  87% (1064/1222)   d 1169 (delta 654)
Receiving objects: 100% (1222/1222), 256.13 KiB | 2.81 MiB/s, done.
Resolving deltas: 100% (704/704), done.
From https://gitlab.com/TomasHubelbauer/bloggo
 * branch            HEAD       -> FETCH_HEAD
```

It didn't fetch the branches in the remote and store them in `refs/remotes/origin` at all!
```sh
> ls .git/refs
heads/  tags/
```

Instead it fetch the remote HEAD and wrote something in `.git/FETCH_HEAD` in... some new format that I'll have to add support for I guess.
```sh
> cat .git/FETCH_HEAD
c610ce1a1e0e383a757af94bb95baeb080d21412                https://gitlab.com/TomasHubelbauer/bloggo
```

Now if we modify the config file to include the fetch refspec and do the exact same fetch:
```sh
> echo "fetch = +refs/heads/*:refs/remotes/origin/*" >> .git/config
> git fetch origin
From https://gitlab.com/TomasHubelbauer/bloggo
 * [new branch]      master     -> origin/master
```

Now we see it saved the fetched branches where we'd normally expect them:
```sh
> ls .git/refs
heads/  remotes/  tags/
> ls .git/refs/remotes
origin/
> ls .git/refs/remotes/origin/
master
```

Interestingly, it updated FETCH_HEAD too:
```sh
> cat .git/FETCH_HEAD
c610ce1a1e0e383a757af94bb95baeb080d21412        not-for-merge   branch 'master' of https://gitlab.com/TomasHubelbauer/bloggo
```

I don't want to make isomorphic-git differ from canonical git's behavior. But I also haven't implemented the weirdness that is FETCH_HEAD. So for now... I think I'll just throw a warning if the config file is missing the "fetch" field for a remote and suggest using the default `fetch = +refs/heads/*:refs/remotes/origin/*`
