### ISSUE TITLE
support incomplete merges with merge conflicts

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#841]
It would be nice if isomorphic-git's `merge` could update the working directory and `.git/index` identically to how canonical git does when there are merge conflicts. I mean, no one likes manually resolving merge conflicts. But it's better than not being able to merge at all.

**Comment by thelinuxlich** [comment]
I hope someday this gets implemented :)

**Comment by tsnobip** [comment]
is there any roadmap regarding this feature? It's a pretty big blocker.
Is it not here yet because of technical issues or just because it's lower priority compared to other features?

**Comment by shd101wyy** [comment]
This is awesome! Thank you!!
