### ISSUE TITLE
Can't get a clean pull of non master branch

### ISSUE THREAD

**Issue by knownasilya** [isomorphic-git/isomorphic-git#898]
Please be sure to mention:
- Browser, Chrome latest on macOS
- from npm, ^v0.65.0

Have the following code:

```js
 yield git.clone({
      oauth2format: 'github',
      token: this.session.accessToken,
      dir: '/',
      corsProxy: 'https://cors.isomorphic-git.org',
      url: this.args.blog.repoUrl,
      depth: 1
    });
    yield git.checkout({ dir: '/', ref: 'site' });
    yield git.fetch({
      ref: 'site',
      remote: 'origin',
      dir: '/',
    });
    yield git.resetIndex({ dir: '/', ref: 'site', filepath: '/' })
    yield git.pull({
      dir: '/',
      ref: 'site',
    });
    console.log(yield git.listFiles({ dir: '/' }));
```

For this repo https://github.com/knownasilya/knownasilya.github.io and have a bunch of files that aren't commited. Is there a way to get a fresh clone of the `site` branch that I can apply changes to without having all the other changes there on a fresh pull? I tried reseting indexdb but the result is always the same.

The issue is that `master` is the built version of the site and `site` is the raw sourcecode to get there, so the two branches don't share code.

**Comment by wmhilton** [comment]
I'm afraid I don't have a good sense of what you're trying to do. Could you show me what the equivalent canonical (command line) git version of the script would look like? I can probably translate that more easily.

**Comment by knownasilya** [comment]
I think my issue is actually just regarding
```js
let branches = yield git.listBranches({ dir: '/', remote: 'origin' });
```

Which returns all branches local and remote, is there a way to get remote only?

**Comment by knownasilya** [comment]
`git branch -r` I think

**Comment by knownasilya** [comment]
Should have read the docs better..
