### ISSUE TITLE
isogit init in existing repo overwrites .git/config unconditionally

### ISSUE THREAD

**Issue by djencks** [isomorphic-git/isomorphic-git#899]
git init documentation and behavior indicate that git init in an existing repository do not remove information from .git/config.  isomorphic-git init unconditionally overwrites .git/config.

I'd suggest that checking for the existence of .git/config and not changing it if present would be more appropriate behavior.

**Comment by djencks** [comment]
Alternatively, if .git/config already exists, we could check for each of the keys we create and add them if missing.  Or we could do the entire operation of setting up .git/config using the config command.  If you'd prefer one of these approaches I'm happy to implement it.

**Comment by wmhilton** [comment]
> I'd suggest that checking for the existence of .git/config and not changing it if present would be more appropriate behavior.

I'm leaning towards going with that option. BUT... I know there's a fair amount of code out their that relies on the "quirk" of isomorphic-git where you can call `clone` and it just clobbers stuff. Or worse, there might be folk out there using `init` to reset saved remote branches etc.

So (and I sound like a broken record) I think this is a great idea, but lets put it behind a flag for now and wait to make it the default behavior in the 1.0 release. :-) Something like `init({ safe: true })` or `{ noOverwrite: true }`.

**Comment by djencks** [comment]
I picked noOverwrite.  You may have seen on the PR, npm run add-contributor didn't work for me.

**Comment by wmhilton** [comment]
> npm run add-contributor didn't work for me.

it's been very very flaky. something to do with Github API throttling limits or something I think? I would love to switch to a bot or something... [hang on, using google]

ah darnit they still haven't fixed the permissions on the all-contributors bot. I'll open [an issue](https://github.com/all-contributors/all-contributors-bot/issues/252)
