### ISSUE TITLE
Cloning a tag fails during checkout

### ISSUE THREAD

**Issue by juancampa** [isomorphic-git/isomorphic-git#93]
I can successfully clone a specific branch by passing a `ref` value. However when I try to clone a tag (lightweight) it fails. From what I can tell the fetch works but it fails during checkout trying to resolve the ref `origin/tag-name`

I'm cloning with:
```
    await git.clone({
      // ...
      ref: 'tag-name',
    });
```

I see that `fetch` has a `tags` argument but `clone` never passes it so my guess is that the initial fetch does not include the tags.

Thanks for this awesome library

**Comment by juancampa** [comment]
The callstack it fails with:
```
Error: Could not resolve reference origin/bd00408c-5693-4299-98a3-396274a2dacb
    at Function.resolve (managers.js:372)
    at <anonymous>
```

**Comment by wmhilton** [comment]
Yes, tag support isn't at 100% yet. I'll add a test for cloning by tag name and see I can get that to pass. It might be as simple as passing {tags: true} to fetch during clone.

**Comment by juancampa** [comment]
I had the same thought and tried defaulting `tags = true` but it didn't help so there might be something else.

**Comment by wmhilton** [comment]
OK, think I found a fix. It was a little more subtle than I expected. Passing `tags: true` to fetch was the first step. But then, because tags are not stored under "refs/heads/remotes" like remote branches but in "refs/tags", it was erroneously telling the server "I already have that commit" when it was trying to clone it.

**Comment by juancampa** [comment]
Whoa! thanks for the quick turnaround!
