### ISSUE TITLE
Checking out specific file(s) diverges significantly from standard git behavior

### ISSUE THREAD

**Issue by thatchej** [isomorphic-git/isomorphic-git#952]
Using Node, and `isomorphic-git@0.72.0`

The standard `git` behavior when checking out specific files is the following:

> Overwrite paths in the working tree by replacing with the contents in the index or in the `tree-ish` (most often a commit). When a `tree-ish` is given, the paths that match the `pathspec` are updated both in the index and in the working tree.

In a Javascript-world example, the command might look something like this: `git checkout master -- package.json` or `git checkout otherRemote -- package.json`. Git would then update _only_ `package.json` with the contents found on `master` or `otherRemote`, respectively. 

When using `isomorphic-git`'s passable options to `checkout`: `pattern` or `filepaths`, the behavior of this differs significantly, and subverts expectations.

When used in this way, `isomorphic-git` will remove **ALL** files not specified in the given options. Starting with a tree like so

```
/tmp/project
├── Dockerfile
├── README.md
├── package-lock.json
├── package.json
├── public
│   ├── favicon.ico
│   ├── index.html
│   └── manifest.json
└── src
    ├── App.css
    ├── App.js
```

after running 

```
await this.git.checkout({
  dir,
  ref: 'master',
  remote: 'otherRemote',
  filepaths: ['package.json']
});
```

one would be left with a file tree like so:

```
/tmp/project
├── package.json
├── public
└── src
```

**Is this intended behavior?** If so, is it possible to change these commands to match standard `git` behavior?

**Comment by thatchej** [comment]
@wmhilton, has anybody had an opportunity to think about this one? (Sorry if the direct tag is super faux-pas). This is a pretty large blocker for us and I haven't found any workarounds in the docs of any kind.

FWIW, if there isn't a desire to make this breaking change at the moment (even though I would argue it should be made to match `git`), a properly implemented version of the new `git restore` command could also take care of this use case

**Comment by wmhilton** [comment]
Oops. That was embarrassing. 😬 

>  (Sorry if the direct tag is super faux-pas).

Not at all! I just... well... I need to declare GitHub notifications bankruptcy:
![image](https://user-images.githubusercontent.com/587740/72469504-8779d580-37ad-11ea-9d6e-e7459f9ce8a5.png)

Thank you person who pinged me on Twitter...
https://twitter.com/olivierlacan/status/1217521533687603206?s=20

So polite too! Thanks for the patience y'all.

> I haven't found any workarounds in the docs of any kind.

I did discover a workaround while I was working on the fix! The newer `fastCheckout` command didn't have this bug :) It'll become the default implementation of `checkout` in version 1.0
