### ISSUE TITLE
Notes support

### ISSUE THREAD

**Issue by djencks** [isomorphic-git/isomorphic-git#958]
Implement basic git notes, all under a supplied notes ref:

* addNote as string or byte array to any object.  Ignore merge and move scenarios for now.
* listNotes (all or one)
* removeNote
* showNote return a note as a Buffer.

**Comment by TomasHubelbauer** [comment]
Notes support would be really neat indeed, I've meant to look into using them for storing issues/reviews etc. as a part of the Git repository but not the actual directory. Also supporting them would allow us to parse things from tools like [Git Appraise](https://github.com/google/git-appraise) which use notes in the aforementioned way.

**Comment by TomasHubelbauer** [comment]
@djencks do you think you could add examples for the notes related methods to the docs similarly to how other commands include examples?

**Comment by djencks** [comment]
I’ll try…. it may take a while.
