### ISSUE TITLE
Why does statusMatrix contain 1, 1, 1 records?

### ISSUE THREAD

**Issue by TomasHubelbauer** [isomorphic-git/isomorphic-git#973]
I'm a little bamboozled about why `statusMatrix` would contain the `1,1,1` records? My assumption is that the absence of a file in the array resulting from `statusMatrix` is equivalent to its existence with the `1,1,1` flag combination. Is this incorrect? If not, under what conditions is a file excluded from the resulting array and under what conditions is it included with the `1,1,1` record?

**Comment by wmhilton** [comment]
Files shouldn't ever be excluded. 😕

**Comment by TomasHubelbauer** [comment]
Oh so this should be a complete listing of the Git tracked entries, got it. Thank you!
