### ISSUE TITLE
Edge out of preview - time to drop IE support and release 1.0?

### ISSUE THREAD

**Issue by TomasHubelbauer** [isomorphic-git/isomorphic-git#975]
> The 1.0 release is planned to coincide with the stable release of the new Chromium-based Micorosoft Edge in January 2020, so that we can drop support for the old Edge browser.

Edge is out of preview: https://www.microsoft.com/en-us/edge

https://blogs.windows.com/windowsexperience/2020/01/15/new-year-new-browser-the-new-microsoft-edge-is-out-of-preview-and-now-available-for-download/

Related: #653

**Comment by wmhilton** [comment]
working on it :)

**Comment by wmhilton** [comment]
I keep finding "one more thing" I want to improve.

**Comment by TomasHubelbauer** [comment]
🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳
