### ISSUE TITLE
 Unparsable response from server when pushing to private repositories on Github

### ISSUE THREAD

**Issue by fawind** [isomorphic-git/isomorphic-git#982]
When trying to push a new commit to Github made using the isomorphic-git in the Browser, I get the following errors in the console:

```
error TypeError: Cannot read property 'length' of undefined
    at StreamReader.read (index.js:2661)
    at async read (index.js:6312)
    at async nextBit (index.js:6871)
index.js:6320 error TypeError: Cannot read property 'length' of undefined
    at StreamReader.read (index.js:2661)
    at async read (index.js:6312)
    at async parseReceivePackResponse (index.js:9953)
    at async Module.push (index.js:10312)
    at :8080/async <anonymous>:1
index.js:284 Uncaught (in promise) UnparseableServerResponseFail: Unparsable response from server! Expected "unpack ok" or "unpack [error message]" but received "". UnparseableServerResponseFail: Unparsable response from server! Expected "unpack ok" or "unpack [error message]" but received "".
    at parseReceivePackResponse (webpack:///./node_modules/isomorphic-git/dist/for-future/isomorphic-git/index.js?:9963:11)
    at async Module.push (webpack:///./node_modules/isomorphic-git/dist/for-future/isomorphic-git/index.js?:10312:20)
    at async <anonymous>:1:23
```

I'm using the Browser version (`0.70.6`) in combination with [lightning-fs](https://github.com/isomorphic-git/lightning-fs) (`3.4.0`) in a Webpack environment.

My workflow is as follows:

1. Clone the repo which works fine:
```js
await git.clone({
  dir: '/',
  corsProxy: 'https://cors.isomorphic-git.org',
  singleBranch: true,
  depth: 1,
  username: 'fawind',
  token: '<my-token>',
  url: '<my-repo>',
});
```

2. Edit and write changes to a file using `fs.writeFile()`.

3. Add the file and create a commit. This seems to work fine. The hash is logged and the commit is listed when using `git.log()`:
```js
await git.add({ dir: '/', filepath: 'README.md' })
await git.commit({ dir: '/', author: { name: 'fawind', email: '<my-email>' }, message: 'Update readme' })
```

4. Push the changes to Github:
```js
await git.push({
  dir: '/',
  ref: 'master',
  token: '<my-token>',
  oauth2format: 'github',
  corsProxy: 'https://cors.isomorphic-git.org',
})
```

I tried several variations of the push-parameters but I always get the above error message.
The docs and other examples seem to suggest that the browser-based version works fine with Github. Is there something obvious, I'm not seeing?

Thanks!

**Comment by fawind** [comment]
I did some further investigations. The error only occurs when pushing to a private repository. For public repositories, everything works as expected.

My Github token has sufficient permissions as I can clone and push private repos using the Git CLI and my username + token.

**Comment by wmhilton** [comment]
I bet you're using a Personal Access Token, not an OAuth2 token. Try removing
```js
  oauth2format: 'github',
```

It's confusing. I tried to simplify it in v1 by sticking with just `username + password` or `headers`.

**Comment by fawind** [comment]
I tried many variations of the command but could not get it to work.

However, after migrating to the v1 API, push/pull is now working with my private Github repo. I'll mark this as closed, thanks for your help!
